### ISSUE TITLE
getaddresshistory / getdetailedtransaction does not return fee

### ISSUE THREAD

**Issue by karel-3d** [trezor/blockbook#10]
Bitcore API returns fee, blockbook API does not.

In TXs without input values (for example nonsegwit btc) this is impossible to calculate just from the TX.

**Comment by wlc-** [comment]
It would be nice to have to have an option with getaddresshistory to also get inputs.

**Comment by martinboehm** [comment]
I will add it there. Historically we removed the functionality because it was not required for Trezor Wallet and it was expensive (multiple lookups for input transactions). However, with current index the cost is negligible and it makes sense to make the interface more compatible with Insight

**Comment by martinboehm** [comment]
The functionality was added by the commit f9809d75073dc42871ab0dda32f0a6768086ba5b.
