### ISSUE TITLE
bitcoin blockbook cannot sync

### ISSUE THREAD

**Issue by Pyxic** [trezor/blockbook#1000]
I got error
`Dec  5 10:43:29 blockbook-bitcoin-ram kernel: [34309405.119823] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/blockbook-bitcoi
n.service,task=blockbook,pid=1675177,uid=995                                                                                                                                                    
Dec  5 10:43:29 blockbook-bitcoin-ram kernel: [34309405.120099] Out of memory: Killed process 1675177 (blockbook) total-vm:34058408kB, anon-rss:29361508kB, file-rss:0kB, shmem-rss:0kB, UID:995
 pgtables:63152kB oom_score_adj:0` 

And after this blockbook sync very slow. Now blockbook lags behind node  by 6 blocks.
I get In logs:
`Dec 05 12:36:30 blockbook-bitcoin-ram blockbook[2109090]: E1205 12:36:30.523043 2109090 public.go:372] write tcp 127.0.0.1:9130->127.0.0.1:42594: write: broken pipe
Dec 05 12:36:46 blockbook-bitcoin-ram blockbook[2109090]: E1205 12:36:46.247408 2109090 public.go:372] write tcp 127.0.0.1:9130->127.0.0.1:47048: write: broken pipe
Dec 05 12:36:57 blockbook-bitcoin-ram blockbook[2109090]: E1205 12:36:57.032668 2109090 public.go:372] write tcp 127.0.0.1:9130->127.0.0.1:52694: write: broken pipe
Dec 05 12:37:05 blockbook-bitcoin-ram blockbook[2109090]: E1205 12:37:05.197576 2109090 public.go:372] write tcp 127.0.0.1:9130->127.0.0.1:54874: write: broken pipe
Dec 05 12:38:06 blockbook-bitcoin-ram blockbook[2109090]: E1205 12:38:06.750925 2109090 public.go:372] write tcp 127.0.0.1:9130->127.0.0.1:47920: write: broken pipe
Dec 05 12:38:50 blockbook-bitcoin-ram blockbook[2109090]: E1205 12:38:50.370601 2109090 public.go:372] write tcp 127.0.0.1:9130->127.0.0.1:33666: write: broken pipe
Dec 05 12:39:19 blockbook-bitcoin-ram blockbook[2109090]: E1205 12:39:19.508952 2109090 public.go:372] write tcp 127.0.0.1:9130->127.0.0.1:43402: write: broken pipe
Dec 05 12:39:56 blockbook-bitcoin-ram blockbook[2109090]: E1205 12:39:56.196834 2109090 public.go:372] write tcp 127.0.0.1:9130->127.0.0.1:56954: write: broken pipe
Dec 05 12:40:03 blockbook-bitcoin-ram blockbook[2109090]: E1205 12:40:03.325408 2109090 public.go:372] write tcp 127.0.0.1:9130->127.0.0.1:60058: write: broken pipe
Dec 05 12:40:57 blockbook-bitcoin-ram blockbook[2109090]: E1205 12:40:57.261435 2109090 public.go:372] write tcp 127.0.0.1:9130->127.0.0.1:50632: write: broken pipe
`

**Comment by martinboehm** [comment]
The errors in the log point to some networking issue. BTW they are not related to blockchain sync but to the explorer interface.

**Comment by Pyxic** [comment]
Why blockbook can sync very slow after Killed process?

**Comment by martinboehm** [comment]
Sorry, I cannot tell from the info you provided.

**Comment by Pyxic** [comment]
Everything worked after a few hours, thank you
