### ISSUE TITLE
When generaing reciceve adresses, it generates 21 insetad of 20

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/blockbook#1004]
Original issue from Suite: https://github.com/trezor/trezor-suite/issues/9634

Steps to reproduce:
- Open websocket in the broser
- Create new Account in the suite
- Look for `getAccountInfo` and it response
- The Receive addresses are 0-20 => 21 addresses

![image](https://github.com/trezor/blockbook/assets/152899911/975cbd72-9872-47e4-b031-1958787a69d2)

**Comment by martinboehm** [comment]
@peter-sanderson Is it really a problem? Blockbook is intentionally scanning one address more to be compatible with the legacy software it replaced.

**Comment by komret** [comment]
Not a problem, I fixed the text in Suite to say 21 instead of 20. This issue can be closed.

Before:
![Screenshot 2024-07-31 at 18 32 39](https://github.com/user-attachments/assets/ed6a70ed-8968-4207-955d-c835a06009e0)

**Comment by peter-sanderson** [comment]
@martinboehm Sorry for late response, I missed your message. Thanks for explanation.
