### ISSUE TITLE
Unnecessary check logic in get transaction API

### ISSUE THREAD

**Issue by johnsonco** [trezor/blockbook#1008]
https://github.com/trezor/blockbook/blob/master/db/txcache.go#L70

Hi team, I believe that the condition `if tx.BlockHeight > 0` in this line is unnecessary. `BlockHeight` will always be 0 because RPC [getrawtransaction](https://developer.bitcoin.org/reference/rpc/getrawtransaction.html#result-if-verbose-is-set-to-true) doesn't return block height information; it only returns the block hash. 

Could you please double-check?

<img width="866" alt="image" src="https://github.com/trezor/blockbook/assets/109326082/b7449fe2-9d07-4d37-9cfa-ce6f683b234f">

**Comment by martinboehm** [comment]
Thank you for your comment. I think that you are forgetting that Blockbook serves many coins and some of them return `tx.BlockHeight` from `GetTransaction`.

**Comment by johnsonco** [comment]
Could you please list some coins that return `tx.BlockHeight` from `GetTransaction`? To the experiences I had, these coins forked from BTC rarely update this part of source code.

**Comment by martinboehm** [comment]
I am not going to. The point is that the common code should handle a potential case that the coin specific code returns the `BlockHeight` (because it can).

**Comment by johnsonco** [comment]
I don't agree with your logic. If none of blockbook supported nodes return `BlockHeight`, then this line of code serves no purpose at all; it just adds interference. 

Imagine if there's an issue with this API, everyone will get stuck here, wasting time. I was indeed disrupted by this line of code and ended up spending an extra hour because of it.

**Comment by johnsonco** [comment]
All codes should have a reason to exist; if not, it should be removed
