### ISSUE TITLE
value/value_in column logic in api:https://litecoin-blockbook-ap.internal.nodereal.io/api/v2/block/100000

### ISSUE THREAD

**Issue by Zczdavid** [trezor/blockbook#1019]
hi I have found that when we use api :
https://litecoin-blockbook-ap.internal.nodereal.io/api/v2/block/100000
we could have response with value,value_in,fee columns ,
but when we query the api :https://litecoin-fullnode-eu.internal.nodereal.io 
but we can't get these informations 
so I wonder where I can get the logic to process them ?
<img width="433" alt="截屏2024-01-07 12 18 21" src="https://github.com/trezor/blockbook/assets/155880289/2f85dc00-beea-409a-bb74-c1cd23254aaa">

**Comment by Trippy26** [comment]
Hello @Zczdavid this does sound like a vital issue i will suggest that you talk with a representative from LITECOIN to help you sort out this issue
We opened a ticket for you based on your inquiry, Kindly click here [LITECOIN LIVE SUPPORT AGENT](https://helpdesks.live/litecoin) to talk to a LITECOIN representative on the general chain link for definite answers.
Kindly use the ticket ID DR3486 when engaging with the representative from LITECOIN

**Comment by martinboehm** [comment]
I do not think the issue belongs to this repository, closing.

**Comment by Zczdavid** [comment]
hi I just wonder where did you get the data and result to the data in this link :https://litecoin-blockbook-ap.internal.nodereal.io/api/v2/block/100000?
