### ISSUE TITLE
Token decimals - manual correction of contract metadata 

### ISSUE THREAD

**Issue by tomasklim** [trezor/blockbook#1026]
> 
@tomasklim yes, it is reported incorrectly by Blockbook because the contract self describes itself incorrectly (probably does not implement the get decimals method and Blockbook then defaults to 18). I will have to implement manual correction of contract metadata.

https://github.com/trezor/trezor-suite/issues/8030

Same tx on etherscan and blockbook
https://etherscan.io/tx/0xa7b635ff1f823fa3a99ac2353a14bfc523ce6b690b9743992757346ad8c9def9
https://eth1.trezor.io/tx/0xa7b635ff1f823fa3a99ac2353a14bfc523ce6b690b9743992757346ad8c9def9

According to blockbook, `decimals` = 18 https://eth1.trezor.io/api/v2/address/0xC19B6A4Ac7C7Cc24459F08984Bbd09664af17bD1
Acording to ethscan `decimals` = 0
<img width="464" alt="Screenshot 2023-04-07 at 22 13 34" src="https://user-images.githubusercontent.com/33235762/230672952-01c95fae-c043-41db-baba-f3d7add3a79c.png">

**Comment by martinboehm** [comment]
@tomasklim the SENSO contract is fixed. If there is any other known issue with a contract decimals (in any EVM), please report it, it can be now manually fixed.
