### ISSUE TITLE
Blockbook stopped indexing Sepolia after Hardfork 

### ISSUE THREAD

**Issue by akme** [trezor/blockbook#1028]
Blockbook stopped indexing Sepolia after Hardfork and stuck at height [5187022](https://sepolia1.trezor.io/block/5187022)

**Comment by martinboehm** [comment]
Thank you, investigating...

**Comment by martinboehm** [comment]
Our Sepolia seems to be syncing with the following config: Prysm/v4.2.1, Erigon/2.57.2, Blockbook from the master branch.
