### ISSUE TITLE
Blockbook = 0

### ISSUE THREAD

**Issue by Pymmdrza** [trezor/blockbook#1043]
The weakest and most problematic program that I have used so far and I regret it is this program that does not show any talent or diversity in it. address (different addresses) and finally, after spending a lot of time, if you don't have enough experience, you can't start this because there are thousands of obstacles in the way, so much so that some cases are poorly mentioned in it.
I now after 38 days when I wasted for this on 12 different servers I checked it now I removed it completely because it is very very weak and beginner and my advice to other friends to try other things with strong support More and more professional coding. Because you will face 100% problems in installation.

**Comment by martinboehm** [comment]
Thank you for your opinion

**Comment by Pymmdrza** [comment]
> Thank you for your opinion

My dear friend, I don't want you to be upset or take my opinion negatively. I want you to put yourself in the place of a user who wants to launch this program. In your opinion, have you put anywhere the complete 0 to 100 training of this project? Everywhere you see here, it only mentions some basic issues, such as `git clone https://github.com/trezor/blockbook` and `cd blockbook` and... Have you included a complete training page of your product once you have fully launched it, and all the commands you used there? did you insert You have worked hard and I am sure you have spent a lot of time on this project and I give you the right. Because I myself sometimes spend 3 to 4 months for a software to finish it and after they finish it, maybe I will spend another month just to publish and insert the correct instruction on how to use it, because if to our users If I can't show the efficiency of my software and they don't know how to work with it, all the time I spent on software programming will be wasted.
