### ISSUE TITLE
Ethereum sync stuck on block 18999999

### ISSUE THREAD

**Issue by 7-of-9** [trezor/blockbook#1056]
Blockbook web status page as below...

Any advice or pointers much appreciated. Blockbook is not on latest (can't get an installable build), but concensus and erigon clients both are... 

**Backend**
Chain | mainnet
Version | erigon/2.58.1/linux-amd64/go1.21.6
Consensus Version | Prysm/v5.0.1 (linux amd64)
Last Block | 18999999
Difficulty | 0

**Blockbook**  
Coin | Ethereum
Version / Commit / Build | 0.4.0 / b5cfbdfd / 2024-03-21T22:22:30+00:00
Synchronized | TRUE
Last Block | 18999999
Last Block Update | 24 days 2 hours ago
Mempool in Sync | TRUE
Last Mempool Update | 58 secs ago
Transactions in Mempool | 196
Current Fiat rates | 4 mins ago
Historical Fiat rates | 1 day 7 hours agotokens 6 hours 7 mins ago
Size On Disk | 195367295050

**Comment by martinboehm** [comment]
It does not look like a Blockbook issue, more like behaviour of Erigon. See for example https://github.com/ledgerwatch/erigon/issues/8796.
