### ISSUE TITLE
starting order of backend and blockbook services

### ISSUE THREAD

**Issue by dev-dantealighieri** [trezor/blockbook#1062]
in the [tutorial](https://trezor.io/learn/a/custom-backend-in-trezor-suite), you are mentioning that we should first run the backend, then after synchronization, run the blockbook service, why is that required?

my machine is good, can i start them at the same time, and let them sync ledger and index database at the same time?

thanks.

**Comment by vdovhanych** [comment]
While it will probably work, there might be an issue with data indexing for the blockbook db and a chance of data corruption. That is the main reason we suggest indexing an already synchronized backend.

**Comment by dev-dantealighieri** [comment]
@vdovhanych after synchronization, they continue to run together, does that mean there can be corruption after installation?

also it would be great if we can run those together, because both of them took significant amount of time

thanks, dante

**Comment by martinboehm** [comment]
If they run without any errors, there is no corruption. In general it is faster to sync Blockbook to fully synced backend but it can be done in parallel.
