### ISSUE TITLE
BCH hardfork

### ISSUE THREAD

**Issue by aghamir** [trezor/blockbook#1078]
Hi @martinboehm,
Can you bump version of bch fullnode from 26.1.0 to 27.0.0 to support their network update.
Thanks a lot

**Comment by martinboehm** [comment]
@Dehumanizer77

**Comment by Dehumanizer77** [comment]
Thanks for the heads-up, I'll do it on Monday

**Comment by Dehumanizer77** [comment]
https://github.com/trezor/blockbook/pull/1079
