### ISSUE TITLE
Allow to use eth_call for specific contract addresses (staking/unstaking)

### ISSUE THREAD

**Issue by tomasklim** [trezor/blockbook#1084]
To be able to implement this to Suite https://github.com/trezor/trezor-suite/issues/11402

We need to be able to call `eth_call` for specific contract addresses (I think blockbook already have those addresses somewhere)

1. Add some endpoint to blockbook to use `eth_call` and directly call node
2. Implement `eth_call` to connect
3. Use connect call in Suite

![Screenshot 2024-04-25 at 18 01 35](https://github.com/trezor/blockbook/assets/33235762/35313f88-8534-4de3-8bfe-809c618d4004)

https://satoshilabs.slack.com/archives/C0543DJBK0C/p1714131319854119

**Comment by tomasklim** [comment]
renamed to `rpcCall`

**Comment by martinboehm** [comment]
Finished by 76664cdbf37f008865586c4d716602cc00bf8398
