### ISSUE TITLE
API endpoint with latest block hash

### ISSUE THREAD

**Issue by cpuchainorg** [trezor/blockbook#1093]
Would be great if we have an additional API endpoint that would return recent block hashes only ( about 100 or 1000 would be good ).

This should be useful for http endpoints to detect reorgs without using websockets

**Comment by cryptosystems6300** [comment]
You dont need blockbook for this. Just ask the node directly: https://developer.bitcoin.org/reference/rpc/getbestblockhash.html

e.g. 

```
curl --location '<nod url>'  --header 'Content-Type: application/json' --data '{
    "jsonrpc": "2.0",
    "id": "somedummyid",
    "method": "getbestblockhash",
    "params": []
}'
```

**Comment by cpuchainorg** [comment]
@cryptosystems6300 You can search on their github why you shouldn't expose your bitcoin rpc to public... they aren't redundant to serve data in public...
