### ISSUE TITLE
list of tetsnet urls for trezor.io blockbook servers 2

### ISSUE THREAD

**Issue by morriswinkler** [trezor/blockbook#11]
referes to #4 

@martinboehm I think you misunderstood, I use the testnet to run tests on the trezor web wallet using a trezor hardware wallet. 

I see myself as a happy customer that does bug hunting in his spare time, I am asking for a list of testnet URI's to run against the different testnets. That is basically QA at no cost. 

I have no problem with URI's changing, can take a 404.

**Comment by martinboehm** [comment]
Sorry for my misunderstanding. We currently run only Bitcoin Testnet instances https://testnet-bitcore1.trezor.io/, https://testnet-bitcore2.trezor.io/, https://testnet-bitcore3.trezor.io/. All of there instances still run bitcore and will be switched to blockbook in the future. We do not have publicly accessible testnet instances of any other coins.

**Comment by morriswinkler** [comment]
@martinboehm thanks. Noted, would be good to have test instances for all currencies for at some point. I know that you are not an API provider and therefore not provide sandboxes. Still being able to easily test the hardware with all the currencies within there test net would be beneficial to build up better trust. Just an idea :)
