### ISSUE TITLE
ETH getBlock blockchain_link/websocket_error_message Error

### ISSUE THREAD

**Issue by ramezanzade1** [trezor/blockbook#1102]
When i call the below code i get this error:

error:{
code: "blockchain_link/websocket_error_message",
message: "Not supported"
}

code:
  const link = new BlockchainLink({
      name: 'MyBlockchainLink',
      worker: Blockbook,
      server: ['https://eth1.trezor.io/', 'https://eth2.trezor.io/'],
      keepAlive: true,
      debug: true,
    });

    try {
      const info = await link.getInfo();
      console.log(info);
      const blockHash = await link.getBlockHash(20103106);
      console.log(blockHash);
      const block = await link.getBlock(20103106);
      console.log(block);
    } catch (error) {
      console.error('Error fetching blockchain info:', error);
    }

**Comment by martinboehm** [comment]
Hi. The `getBlock` call is not and will not be supported on our ETH servers.
