### ISSUE TITLE
changing instance type

### ISSUE THREAD

**Issue by dev-dantealighieri** [trezor/blockbook#1119]
hi

i deployed my litecoin indexer on aws, can i change aws ec2 instance type from x86 to arm, rebuild the blockbook, and continue with already indexed data?

thanks, dante

**Comment by vdovhanych** [comment]
It should be possible technically, but this is not something we've had experience with.

**Comment by martinboehm** [comment]
Sure, there is no problem. Database format is compatible across platforms.

**Comment by dev-dantealighieri** [comment]
@martinboehm 

i change my ravencoin instances type from x86 to aarch64, i didnt changed the data, but currently i cannot even build, i get the following error

is there anything else i need to now for building to arm?

thanks

**Comment by vdovhanych** [comment]
Take a look at Bitcoin configuration, especially regtest. There are binaries being downloaded during the build, and I believe it downloads x86 binaries. That's why it fails for you with an exec format error.

**Comment by dev-dantealighieri** [comment]
hey,

how can i fix this, i just want to install onto arm64 machine, can you privde help on this topic?

**Comment by vdovhanych** [comment]
Add platform configuration to the coin config as I send you with the Bitcoin request example. After that, you can just run the build, and it should build the arm version for you.
