### ISSUE TITLE
[REQUEST] Multi-blockchain instance

### ISSUE THREAD

**Issue by eabz** [trezor/blockbook#117]
Hello. 
I recently found this project and I think is a very nice idea. 
We are currently working with HD Wallets under the [PolisPay APP](https://polispay.com). I see you are already working on direct API endpoints for xpub and I'll like to help.
I don't know if someone already asked it, but It will be awesome if we can have a multi-blockchain instance to prevent creating multiple instances for the same purpose.
I am looking the code and if I get some idea I'll try to help on it.

**Comment by martinboehm** [comment]
Hi. 

We are not going to support multi-blockchain instances. It is easy to install and manage multiple instances of Blockbook and it serves the same purpose.

Thank you for your offer to help us with xpub support but as it is almost done, we do not need it.
