### ISSUE TITLE
my application can't receive anything from getAddressHistroy 

### ISSUE THREAD

**Issue by KevinBaiSg** [trezor/blockbook#119]
I want to develop a wallet used Trezor hardware and election framework. I use the hd-wallet project to discovery the account, but can't receive anything from getAddressHistroy API. 
![image](https://user-images.githubusercontent.com/2813260/52530006-96077380-2d38-11e9-8d0d-4455dd1457a7.png)

this is issues in trezor hd-wallet project. https://github.com/trezor/hd-wallet/issues/34

**Comment by KevinBaiSg** [comment]
the backend supported discovery the account information by xpub?

**Comment by prusnak** [comment]
I strongly suggest you use our [gitter](https://gitter.im/trezor/community) talk if you want to chat. You are spamming all our repositories with your questions and it is not nice.

**Comment by martinboehm** [comment]
You have to specify the address for which you want to get the address history.
