### ISSUE TITLE
Ethereum wrong balance when only internal transactions exist

### ISSUE THREAD

**Issue by diogorac** [trezor/blockbook#125]
When an address only has internal transactions (no normal transactions), the balance is shown incorrectly to be 0.

Example:
* https://ropsten.etherscan.io/address/0x7caef9248c50524ed71ebada335518247dbc94bb
* Blockbook shows it to be 0.

It works fine if there is also a normal transaction on the address.

Example:
* https://ropsten.etherscan.io/address/0x7caef9248c50524ed71ebada265518247dbc94bb
* Blockbook shows the sum of normal transaction and internal transaction

**Comment by martinboehm** [comment]
Thanks for reporting. We do not currently query geth for balance for addresses without normal transactions, we will have to change it.

**Comment by adrienmo** [comment]
@martinboehm Any plans to support internal transactions in the transaction list results ?

**Comment by martinboehm** [comment]
Not at this moment.

**Comment by harusurv** [comment]
Is not any plans on this yet? Sadly without showing them its difficult to track the balance when using services like uniswap, because all come in form of internal transactions.

**Comment by harusurv** [comment]
> Not at this moment.

Is not any plans on this yet? Sadly without showing them its difficult to track the balance when using services like uniswap, because all come in form of internal transactions.
