### ISSUE TITLE
ZeroMQ version is different?

### ISSUE THREAD

**Issue by wakiyamap** [trezor/blockbook#126]
When newly installing blockbook,
the following error continues and blockbook does not start.
```
bitcoinrpc.go:113] mq: zmq4 was installed with ZeroMQ version 4.2.1, but the application links with version 4.3.1
blockbook.go:108] rpc: zmq4 was installed with ZeroMQ version 4.2.1, but the application links with version 4.3.1 Retrying...
```

``FROM debian:9`` is installed stretch(stable) version.
https://github.com/trezor/blockbook/blob/master/build/docker/bin/Dockerfile#L3

``libzmq3-dev`` is installed ``4.2.1-4+deb9u1`` on debian stretch(stable) version.
https://packages.debian.org/search?keywords=libzmq3-dev

Should I change the debian version of docker?

My docker version is here.

```
docker --version
Docker version 18.09.1, build 4c52b90
```

**Comment by martinboehm** [comment]
Strange, I do not have this problem.
I am building Blockbook using our docker build (`Docker version 18.06.1-ce`) on a machine running `Debian 4.9.110-3+deb9u6` and then running it on the same machine without any problems. Locally installed ZMQ:
```
sudo apt list --installed | grep libzmq3 
libzmq3-dev/stable,now 4.2.1-4 amd64 [installed]
```
I rebuilt Blockbook just now with docker caching disabled (using `make NO_CACHE=true all-bitcoin`), the build used the same ZMQ:
```
docker run 268237f49212 apt list --installed | grep libzmq3
libzmq3-dev/stable,now 4.2.1-4+deb9u1 amd64 [installed]
```
The newly built Blockbook runs fine on our machine.

**Comment by wakiyamap** [comment]
@martinboehm 
I borrowed a new VPS and done.
I made the same settings as the VPS that got this error, but it may be something wrong......

thanks!!

**Comment by lessless** [comment]
I have a similar problem with blockbook 0.3.6: 

```

$ git branch
* (HEAD detached at v0.3.6)
  master
  v0.4.0
```


```
$make NO_CACHE=true all-bitcoin
```

```
$docker images
REPOSITORY            TAG       IMAGE ID       CREATED          SIZE
blockbook-build-deb   latest    c89bea930623   12 minutes ago   6.92GB
blockbook-build       latest    82b7b3c9a905   15 minutes ago   6.8GB

$docker run  c89bea930623 apt list --installed | grep libzmq3

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libzmq3-dev/stable,now 4.3.4-1 amd64 [installed]

$apt list --installed | grep zmq

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libzmq3-dev/stable,stable,now 4.3.4-1 amd64 [installed]
libzmq5/stable,stable,now 4.3.4-1 amd64 [installed,automatic]
```



```
E1207 22:47:06.549357 2976000 bitcoinrpc.go:168] mq: zmq4 was installed with ZeroMQ version 4.3.4, but the application links with version 4.3.5
E1207 22:47:06.602100 2976000 blockbook.go:306] initializeMempool zmq4 was installed with ZeroMQ version 4.3.4, but the application links with version 4.3.5
```
