### ISSUE TITLE
Xpub API returns incorrect derivation path for bitcoin cash

### ISSUE THREAD

**Issue by hewigovens** [trezor/blockbook#146]
One example utxo, the coin_type in path should be `145`
```js
{
txid: "2b5bc25853a0890f574af7042006e5c22bfbb532271ac08aea6de43767518fa0",
vout: 0,
value: "1111",
height: 574741,
confirmations: 2629,
address: "bitcoincash:qzx2jjqx9y95ww50aarmwjcfnq84x0qkjq9m275jw7",
path: "m/44'/0'/0'/0/3"
}
```
From xpub: [xpub6CjmRV2DKxdbCrV7AX7tqKz1uc1g4H8UjFfkSJSCWvbuUDNP2JvtmYVNBh8hNwpoFxcQZxH7iTyENFtXQRrQTwsqopB1XjCkM9NT6PurE9C](https://bch-rpc.binancechain.io/api/v2/utxo/xpub6CjmRV2DKxdbCrV7AX7tqKz1uc1g4H8UjFfkSJSCWvbuUDNP2JvtmYVNBh8hNwpoFxcQZxH7iTyENFtXQRrQTwsqopB1XjCkM9NT6PurE9C)

**Comment by martinboehm** [comment]
Thanks for the report. Fixed.
