### ISSUE TITLE
Problem with pruned datas 

### ISSUE THREAD

**Issue by sergocap** [trezor/blockbook#15]
```9 sync.go:242] getBlockWorker 2 connect block error hash 00000000786da017b80e0e66d55facb9f291fc5b2d26b0d1c578dc10860561cf: -1: Block not available (pruned data). Retrying...```
I have bitcoin node with option prune=5000.  
can the blockbook work with such data?
this problem can be solved?

**Comment by martinboehm** [comment]
Sorry, blockbook must be connected to a full node with `txindex=1`, which is incompatible with `prune=5000`. The reason is that on the first start, the blockbook scans and indexes the whole blockchain, which is impossible on pruned nodes.
