### ISSUE TITLE
peercoin style transactions

### ISSUE THREAD

**Issue by barrystyle** [trezor/blockbook#150]
G'day,
I'm working with a project that uses the older peercoin style transactions (tx has its own ntime field immediately after version). Is there any simple way to decode these transactions or is this planned for blockbook in future?
baz

**Comment by martinboehm** [comment]
Hi. Could you give me an example of what do you need? If you need to access some specific tx data using API, Blockbook has an api call for that: [Get transaction specific](https://github.com/trezor/blockbook/blob/master/docs/api.md#get-transaction-specific).

**Comment by barrystyle** [comment]
The issue is; when using blockbook to parse an existing chain with these type of transactions - the ordering/offsets are different (due to peercoin's ntime field), which currently gives an error of 'DecodeTransactions: readScript: transaction input signature script is larger than the max allowed size [count 18374969410709356543, max 33554432]. Retrying...'

The difference can be seen here (Slimcoin uses peercoin format):
https://github.com/slimcoin-project/Slimcoin/wiki/Transaction-Format
https://en.bitcoin.it/wiki/Transaction

I've actually had success by implementing the fields directly in a fork of your library (https://github.com/barrystyle/btcd/commit/cc3d6c3b65bbcbb62682b33e8005b3d49c5b71b9) but wondered if there was a native method instead?

baz

**Comment by martinboehm** [comment]
I think this should be easy: do not use the `BitcoinParser` `ParseTx`/`ParseBlock`, which is not compatible with your coin. Take instead the approach we used in case of [zcash](https://github.com/trezor/blockbook/tree/master/bchain/coins/zec) and some other coins. The principle is that we do not parse the tx blob in Blockbook, we instead get the parsed tx as json from the backend.

**Comment by barrystyle** [comment]
oh.. perfect! yes this sounds like the way to go.. many thanks
