### ISSUE TITLE
Liquid - 'cannot get valid response from bitcoind'

### ISSUE THREAD

**Issue by dmorris99** [trezor/blockbook#151]
Hi all,

I'm having issues running `backend-liquid.service` (on Debian 9) -- it reports pretty quickly after startup, as follows:

```
2019-04-13 17:20:38 init message: Awaiting bitcoind RPC warmup
2019-04-13 17:20:38 opencon thread start
2019-04-13 17:20:38 msghand thread start
**2019-04-13 17:20:38 ERROR: Failure connecting to bitcoind RPC: couldn't connect to server: unknown (code -1) (make sure server is running and you are connecting to the correct RPC port)**
**2019-04-13 17:20:38 Error: ERROR: liquidd is set to verify pegins but cannot get valid response from bitcoind. Please check debug.log for more information.**
2019-04-13 17:20:38 Shutdown: In progress...
```

I'm running on clean install of Debian 9 on a large VM with 56gb of RAM, 

Any input is much appreciated.

**Comment by martinboehm** [comment]
Liquid is a sidechain of Bitcoin and the Liquid backend needs running Bitcoin backend. You have to install and synchronize Bitcoin backend first. You do not have to install Blockbook for Bitcoin though.

Also, Blockbook for Liquid is kind of an experimental implementation, use it at your own risk.

**Comment by dmorris99** [comment]
Thanks @martinboehm I thought it was something along these lines -- so, two backends need to be installed, bitcoin.service and liquid.service?

Understood that it's pretty new, but looks like an interesting side chain, so keen to play with it. Will update here and close once I have it all sync'd and running!

**Comment by dmorris99** [comment]
Confirmed as above - closing.
