### ISSUE TITLE
Bitcoin fee estimation: Implement whatthefee.io

### ISSUE THREAD

**Issue by martinboehm** [trezor/blockbook#153]
Implement the functionality described in https://github.com/trezor/trezor-wallet/issues/503

**Comment by slush0** [comment]
Comments from chat from Felix:

Formula is then fee_sat_per_vbyte = math.exp(fee_level/100).
Don't use the 80% or 95% column by default.
Ideally, If you target 2 hours and can do RBF, start with the 20% 1.5h cell. Then RBF if after 1.5 hours there is no confirmation with 80% 30m.
Of RBF is not possible, use the 50% column with a "safety net" of 2x target_time at 80% and 4x target_tine at 95%

**Comment by slush0** [comment]
Ideally we should log fees proposed by the Core and WTF.io to see how it behaves in different type of network condition.

**Comment by martinboehm** [comment]
For now fetching fees from whatthefee.io is disabled, we will decide later about its usage.
