### ISSUE TITLE
Ethereum sync too slow because "--syncmode full"

### ISSUE THREAD

**Issue by daviyang35** [trezor/blockbook#159]
Synchronizing Ethereum in "Full" mode is very slow. It requires the node to verify all historical data.

Using "--syncmode fast" can greatly improve the synchronization speed.

The "full" setting may be used to ensure the accuracy of the data. I hope to assess the risk of changing to fast mode. Or indicate in the documentation how to speed up Ethereum data synchronization. (like set fast mode)

**Comment by martinboehm** [comment]
Hi, we are aware of the `--syncmode fast` setting. The settings in our repo are the ones which we are using. In your setup, use whatever settings suit you best.
