### ISSUE TITLE
Depends: libgflags2v5 but it is not installable

### ISSUE THREAD

**Issue by christroutner** [trezor/blockbook#163]
Running through the [User Manual](https://wiki.trezor.io/User_manual:Running_a_local_instance_of_Trezor_Wallet_backend_(Blockbook)) I'm trying to install the Blockbook API for Bitcoin Cash. I was able to successfully run `make all-bcash` and build the deb file on a new installation of Ubuntu 18.04. However, when I try to install the generated .deb file (`blockbook-bcash_0.2.2_amd64.deb`), I get this error:

```
The following packages have unmet dependencies:
 blockbook-bcash : Depends: libgflags2v5 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Did some research and found [this page](https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/libgflags-dev_2.2.1-1_amd64.deb.html), which seems to indicate that the `libgflags2v5` library in Ubuntu 16.04, was renamed to `libgflags2.2` in Ubuntu 18.04.

I believe the renaming of the library is the reason for the error.

**Comment by martinboehm** [comment]
Hi. Our build process supports only Debian 9. However, there are people, who managed to run Blockbook on Ubuntu successfully, see for example this [issue](https://github.com/trezor/blockbook/issues/45).

**Comment by christroutner** [comment]
Thanks for the link to that Issue. I was able to follow those suggestions and change this line to Ubuntu:
https://github.com/trezor/blockbook/blob/3e67307a5d8ab2fa3d4988b3df15cdef9c5116ac/build/docker/bin/Dockerfile#L3

The install of the compiled .deb file after that completing successfully.

**Comment by christroutner** [comment]
For those who follow after me, I've forked this repository to target Ubuntu 18.04:
https://github.com/christroutner/blockbook

**Comment by martinboehm** [comment]
Hi, I will give an explanation of the workers issue that you describe in your blog: 

- it is either `-workers=1`, in which case Blockbook not only uses only one thread to fetch data from the backend, it also turns off the bulk import mode (which caches a lot of data in memory and also puts the database in inconsistent mode). So with `-workers=1` even if Blockbook is killed unexpectedly, there is a good chance that the DB will not be corrupted (we use RocksDB transactions to store data).

- or you set `workers` to any value greater than one and it turns on the bulk import mode (with caching and inconsistent DB)
