### ISSUE TITLE
Witness tx but flag byte is 00

### ISSUE THREAD

**Issue by TJvrDev** [trezor/blockbook#164]
When I launch blockbook with an alt coin, it connects to blocks on the chain up until it reaches block 35161, then it says:

```E0427 09:04:00.982947    4601 sync.go:302] getBlockWorker 5 connect block error 35161 11546c2fc7a57b99689596bf4002eb37a68afb67a4261de4e4442d2788647f52: MsgTx.BtcDecode: witness tx but flag byte is 00. Retrying...```

I'll include the log. Any ideas on why this could be happening?
[Blockbook_Log.log](https://github.com/trezor/blockbook/files/3123939/Blockbook_Log.log)

**Comment by martinboehm** [comment]
Hi, what altcoin is it? The problem probably is that the transaction structure is not compatible with the bitcoin parser.

**Comment by TJvrDev** [comment]
I appreciate the feedback, the alt coin is called Alaris. I have the Alaris files that are implemented into blockbook, they have similar naming conventions like the other coins implemented. Do you think the problem could be in alarisparser.go?

**Comment by martinboehm** [comment]
The problem is probably in the parser. I answered a similar question just a couple of days ago, see [here](https://github.com/trezor/blockbook/issues/150#issuecomment-482558833).

**Comment by TJvrDev** [comment]
I tried to alter alarisparser.go with the zcashparser.go logic, adding the PackTx & UnpackTx func's as well as adding the baseparser logic referencing bchain. It still gave the same errors after rebuilding/launching blockbook. Someone suggested finding blockbooks segwit logic and compare to the Alaris segwit id's. I'm looking into that now, if you have any other suggestion, im all ears.

**Comment by TJvrDev** [comment]
I made changes in alarisrpc.go to match the logic in zcashrpc.go and now I dont get the same block errors. The explorer is saying the application is in initial synchronization, so ill wait to see if its fixed. The latest log does have many skipping transaction in block due to tx not found. I'll include the latest log in this comment. 
[Lastest.log](https://github.com/trezor/blockbook/files/3125625/Lastest.log)

**Comment by martinboehm** [comment]
Please make a pull request so that I can see your code. I cannot help you by just looking to the log.

**Comment by TJvrDev** [comment]
After syncing, it looks like its good to go. I appreciate the help!

**Comment by TJvrDev** [comment]
Could I ask a follow up question? I'm running blockbook on a Ubuntu VM & im able to connect from the host (windows) using the port 9030 to get the json value of the blockbook application status. I'm working toward creating a connection to use the blockbook REST api. Do you have any recommendations on how to set up a port for this connection? 

I also created an alaris branch that has my implementation of the alaris coin:
https://github.com/TJvrDev/blockbook/tree/alaris

i'll create a pull request if it helps.

**Comment by martinboehm** [comment]
Hi, API is available on the public port. The internal port is used mainly for Prometheus monitoring. 

By looking to your pull request, you specified in the `configs/coins/alaris.json` 9153 as the public port. This port is already occupied by another coin. Could you please use ports xx58 in the config? See the [registry of ports](https://github.com/trezor/blockbook/blob/master/docs/ports.md) how ports are used by coins.

**Comment by TJvrDev** [comment]
I appreciate the feedback. Just to be sure I understand clearly, I need to change:
```internal port from 9053 to 9058 
public port from 9153 to 9158 
backend_message_queue from 38358
backend_rpc from 8336 to 8358```

Are there any other changes that need to be made besides in my alaris.json file?

**Comment by martinboehm** [comment]
The ports are correct. I see that you are using litecoin signature file for alaris backend, that may be wrong. Also, please remove `build/blockchaincfg.json` file from the pull request.

**Comment by TJvrDev** [comment]
Thanks again for the feedback, i've updated the ports and removed build/blockchain.cfg.json from the pull request.
