### ISSUE TITLE
Parity For Ethereum

### ISSUE THREAD

**Issue by a5m0** [trezor/blockbook#167]
Is it possible to use parity to warp sync the ethereum blockchain to get a significant speed improvement?

**Comment by martinboehm** [comment]
Hi, we have not tested Blockbook with parity and do no plant to do it. 
If parity RPC interface is compatible with geth, it may work. However, it could be easer to run geth with `--syncmode fast`. If you manage to run Blockbook either with parity or with geth --syncmode fast, please let us know.

**Comment by a5m0** [comment]
I am currently running it with geth --syncmode fast and I cannot tell much difference. I changed it to fast part way through though if that makes any difference. I will investigate RPC compatability for parity,

**Comment by martinboehm** [comment]
You have to run the --syncmode fast from the beginning, [see here](https://github.com/ethereum/go-ethereum/pull/1889). 
Also, I am not sure if the receipts will be created in this mode. If not, Blockbook will not be able to index ERC20 token transfers.
