### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by sergocap** [trezor/blockbook#17]
with `curl http://example.compute.amazonaws.com:19036` i get answer ....
But with axios or fetch have problem
`Failed to load http://example.compute.amazonaws.com:19036/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.` 
blockbook have any options for resolve it?

**Comment by martinboehm** [comment]
Yes, we do not set the header in blockbook. We run our production blockbook servers behind nginx, where we would set the header if needed.

**Comment by sergocap** [comment]
with `add_header Access-Control-Allow-Origin *;` all good. thanks
