### ISSUE TITLE
Blockbook Bitcoin Regtest Support?

### ISSUE THREAD

**Issue by stevenceasefire** [trezor/blockbook#175]
I saw that support got added to the Trezor firmware but am wondering whether this will also be added to the official Blockbook list of supported coins. I attempted to jury-rig support myself by updating a copy of the `blockbook/configs/coins/bitcoin_testnet.json` file with new labels and ports, adding a `BlockChainFactories["Regtest"] = btc.NewBitcoinRPC` entry to `/blockbook/bchain/coins/blockchain.go`, building/installing it per the instructions and then manually tweaking the `/opt/coins/nodes/bitcoin_regtest/bitcoin_regtest.conf` with regtest parameters but I'm beginning to think that was a laughably ignorant way to go about it.

I didn't get any apt install errors when installing blockbook and the backend and I'm getting accurate regtest blockchain information when I access the Blockbook public port through Firefox but all I get is "The bitcore server doesn't seem to reply." errors when I attempt to add it as Bitcore server for my Trezor One. All I see in the `blockbook.INFO` log are a bunch of client connects/disconnects and re-sync messages. Unfortunately I don't know Go as a programming language so beyond tweaking what's already baked into Blockbook, I'm at a loss. Am I anywhere close to a solution to adding regtest support myself or should just put this in as a minor feature request?

**Trezor.io Server Selection**
Firefox Request Headers:
```
Host: localhost:32130
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Version: 13
Origin: https://wallet.trezor.io
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: DCWSQNr5QzHg5wqToOpmIA==
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
```
Firefox Response Headers:
```
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: TyElMTylLN21wNKhnZYRa1ee0N4=
```

**blockbook.info Log**
```
I0512 23:02:24.310836     905 socketio.go:50] Client disconnected eA02jK0uJnZa2M_w5r5Z
I0512 23:02:43.584752     905 mempool_bitcoin_type.go:187] mempool: resync finished in 2.67623ms, 0 transactions in mempool
I0512 23:03:43.602365     905 mempool_bitcoin_type.go:187] mempool: resync finished in 488.994µs, 0 transactions in mempool
I0512 23:04:21.316745     905 socketio.go:45] Client connected -QvDGo-kAam8AmdLci1R
I0512 23:04:29.391556     905 socketio.go:50] Client disconnected -QvDGo-kAam8AmdLci1R
I0512 23:04:29.947622     905 socketio.go:45] Client connected f7UHKDzm_pi3EYv3PTMR
I0512 23:04:33.919840     905 socketio.go:50] Client disconnected f7UHKDzm_pi3EYv3PTMR
I0512 23:04:34.906692     905 socketio.go:45] Client connected WB0bDHUqW5ZqkncVtovv
I0512 23:04:43.622123     905 mempool_bitcoin_type.go:187] mempool: resync finished in 2.63455ms, 0 transactions in mempool
```

**Comment by martinboehm** [comment]
Hi. There is probably no problem in your Blockbook regtest implementation.
However, our wallet (https://wallet.trezor.io) does not support regtest. It is detecting coins using genesis block and your regtest genesis block does not match any known coin. Unfortunately, the error message it returns is a bit misleading.

**Comment by stevenceasefire** [comment]
Bummer! Thanks for letting me know, I know it's probably not a common use-case, but are any plans to support regtest coins?

**Comment by martinboehm** [comment]
I don't think that we are going to support regtests, however it is better to ask this question in https://github.com/trezor/trezor-wallet repo.
