### ISSUE TITLE
Blockbook for litecoin provides only initial JSON response

### ISSUE THREAD

**Issue by artall64** [trezor/blockbook#177]
I took the latest version from the master branch and launched it a cloud.
From the very beginning, it gives me JSON responses (not HTML)
```
{
    "blockbook": {
        "coin": "Litecoin",
        ....
    },
    "backend": {
        "chain": "main",
        ....
    }
}
```
You can see it here: https://46.101.116.26:9034
I wait for one sync, for one day and it seems the last indexed block is equal to the last block from the litecoin blockchain.

My problem now that I gate get any response from the node besides default one. For example:
https://46.101.116.26:9034/api/v2/block-index/10000

gives default response as any other request.

Probably problem is on my end, but I wondering on right place to start investigation.
At first, should I expect that version `0.2.2` is working for `litecoin`? 
Because at the docs I see you have `litecoin` version `0.1.1` up and running:
https://ltc1.trezor.io/

Also I see that `dbColumns` field in the response contains a lot of `"rows": 0` fields. 
Should it be like that?
I've attached JSON response that I get:
[response.json.txt](https://github.com/trezor/blockbook/files/3186088/response.json.txt)

**Comment by martinboehm** [comment]
Hi, you are accessing Blockbook on the internal port, which is used mainly for Prometheus monitoring. Use the public port 9134, i.e. https://46.101.116.26:9134/.

Also, the dbColumns statistics are collected approximately once every 24 hours from start, they are probably not yet computed.

**Comment by artall64** [comment]
Thanks, a lot! I've just found exact list of ports here: https://github.com/trezor/blockbook/blob/master/docs/ports.md
