### ISSUE TITLE
MonetaryUnit trezor custom backend using blockbook

### ISSUE THREAD

**Issue by sotblad** [trezor/blockbook#179]
Hey! I'm trying to get MonetaryUnit into trezor. I've integrated it into blockbook successfully, it seems to be running as it's supposed to.
But the thing is that when I submit https://blockbook.monetaryunit.org on wallet.trezor.io/#/settings "Bitcore Server URL", it returns an error message on that page "`The bitcore server doesn't seem to reply. Please select another server.`" and I'm getting these errors on chrome's console:
<img width="641" alt="Screen_Shot_2019-05-18_at_18 10 29" src="https://user-images.githubusercontent.com/26393434/57971555-520bb680-7998-11e9-899d-6640f6907c0a.png">
There are no errors in the blockbook logs.
I'm getting something like this this on blockbook.INFO:
`I0512 23:04:21.316745     905 socketio.go:45] Client connected -QvDGo-kAam8AmdLci1R`
`I0512 23:04:29.391556     905 socketio.go:50] Client disconnected -QvDGo-kAam8AmdLci1R`

This is very similar to #175 , but MonetaryUnit is not regtest.

**Comment by martinboehm** [comment]
Hi, it is probably very similar to #175. I think our wallet does not recognize MonetaryUnit, please ask this question in trezor/trezor-wallet repo.

**Comment by martinboehm** [comment]
Also, you can check our guide how to add new coins https://wiki.trezor.io/Developers_guide:Contributing

**Comment by sotblad** [comment]
Hey, thanks for the answer. Closing this and will later open an issue in the trezor-wallet repo
