### ISSUE TITLE
internalState: DB version 4 of column 'default' does not match the required version 5. DB is not compatible.

### ISSUE THREAD

**Issue by zekylaf** [trezor/blockbook#190]
Hi, I am moving from v0.2.2 to v0.3.0. Must I resync full DB?

Thanks

**Comment by martinboehm** [comment]
Hi, unfortunately yes, see https://github.com/trezor/blockbook/releases/tag/v0.3.0. There is a new index (UTXO) and the old DB is incompatible. I hope that this is the last DB update (at least for a long time).

**Comment by zekylaf** [comment]
Ok, thanks for answer!
