### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pavoltravnik** [trezor/blockbook#194]
Is it possible to use Blockbook in different project?
There is license "GNU Affero General Public License v3.0" in the code and statement
"Blockbook - blockchain indexer for TREZOR wallet https://trezor.io/. Do not use for any other purpose." on the webpage.
I have different open source project and indexer would be really handy to use.

**Comment by martinboehm** [comment]
Blockbook license is AGPL-3.0, you are free to build and run Blockbook on your server. However, we do not permit 3rd parties to use our infrastructure, for that reason there is the statement on the webpage.

**Comment by pavoltravnik** [comment]
That makes sense. Thank you very much for clarification.
