### ISSUE TITLE
Bitcoin Cash testnet backend starts on wrong port

### ISSUE THREAD

**Issue by artall64** [trezor/blockbook#199]
When I setup blockbook for Bitcoin Cash Testnet. It doesn't starts.
Thats happen because backend service starts on port that is different from the one that specified in https://github.com/artall64/blockbook/blob/master/docs/ports.md

If I perform `netstat -lptun | grep bitcoin` I see the following
```
tcp        0      0 127.0.0.1:48331         0.0.0.0:*               LISTEN      32209/bitcoind
tcp        0      0 127.0.0.1:18332         0.0.0.0:*               LISTEN      32209/bitcoind
tcp6       0      0 ::1:18332               :::*                    LISTEN      32209/bitcoind
```
According to the doc instead of  `18332` service should listen port `18031` - and that is the actual port that is specified in blockbook service config.

**Comment by martinboehm** [comment]
Please check that  Bitcoin Cash Testnet Backend is are using the right config - the easiest is to use our package for the backend.

**Comment by artall64** [comment]
I'll check it out, but in that issue I refer to default setup. I've just deploy BitcoinCash Testnet block book on new new VM without editing any of configs. It should be easy to reproduce.

**Comment by martinboehm** [comment]
Hmm, it is this issue: https://github.com/Bitcoin-ABC/bitcoin-abc/issues/314

An easy fix is to append to the end of the backend config file the following lines and restart the service:

```
[test]
rpcport=18031
```

**Comment by martinboehm** [comment]
Hi, we changed the way the Bitcoin Cash Testnet Backend package is built, it should work now without the above written fix.

**Comment by artall64** [comment]
Thanks, Cool!

**Comment by artall64** [comment]
Thanks, Cool!
