### ISSUE TITLE
Unable to use getXpubData for Ritocoin

### ISSUE THREAD

**Issue by Scotty0448** [trezor/blockbook#203]
Ritocoin has xpub values that are 112 chars long. However, the getXpubData function in xpub.go is testing to make sure that xpub values are 111 chars long and returns ErrUnsupportedXpub for Ritocoin.

**Comment by martinboehm** [comment]
I see. We will remove the check and leave it to the `hdkeychain.NewKeyFromString` to check the validity of xpub (or to your presumably overloaded derivation).
