### ISSUE TITLE
Custom cert file extension

### ISSUE THREAD

**Issue by codemaestro64** [trezor/blockbook#204]
Presently cert files must end with a .crt  extension. It'll be nice and more flexible to allow for the use of cert files with different extensions

**Comment by raedah** [comment]
This is needed for decred which uses rpc.cert

**Comment by martinboehm** [comment]
I understand your point.

However, if you are using Debian packages built using our build system, Blockbook is configured to use symlinks `/opt/coins/blockbook/<coin>/cert/blockbook.crt` and `/opt/coins/blockbook/<coin>/cert/blockbook.key`. They by default point to our self generated test certificate but you can relink them to different files with whatever extension you want.
