### ISSUE TITLE
Front-end error handling/display.

### ISSUE THREAD

**Issue by dmigwi** [trezor/blockbook#210]
I was expecting this red band layout to be the standard all across the pages for errors and other important notifications display on the front-end.

![Screenshot from 2019-06-20 22-35-24](https://user-images.githubusercontent.com/22055953/59876906-6256ed00-93ad-11e9-8888-34563e65d283.png)

But instead some errors from our implementation showed up on the front-end in an inconsistent manner from the general page layout. IMO the errors on the front-end show up like a crash just happened while none of that happened at the back-end. The back-end seems to handle errors gracefully.

![Screenshot from 2019-06-20 22-54-05](https://user-images.githubusercontent.com/22055953/59877384-718a6a80-93ae-11e9-9b96-0049e6a1e21a.png)

Is there some setting we need to add so as to enhance the error display?

**Comment by dmigwi** [comment]
Here are some of the suggestions on the error display layout if none exist.
- The font size showing the word "Error" is too huge, more than the actual error message.
- `data <nil>` is unnecessary information to display on the front-end.
- The red band layout shown while syncing could be used here.
- The font type used in error display could be made to match the general page font and layout.

**Comment by martinboehm** [comment]
Hi, thank you for your suggestions. I assume that you are running Blockbook without the parameter `-debug`, which returns extended error info to the client. Please could you give me more info about the error, i.e. what action causes it and what is logged to the log?

**Comment by dmigwi** [comment]
Hi, thanks for that new param `-debug` that I did not consider before.

The error was due to an issue in the implementation of `GetTransaction` method which has since been resolved. My point of concern was the error display itself for which we all know that the back-end systems that the blockbook depends on could start returning errors.

**Comment by martinboehm** [comment]
In non debug mode Blockbook returns only "Internal server error" for internal errors, see https://github.com/trezor/blockbook/blob/104f6f9a9d711b5e4f9f1ba4ed30527eada83bc3/server/public.go#L366

As for the layout part, while the error page is certainly not beautiful, it follows the general layout of the application - page title <h1> followed by some data, in this case the error text.
