### ISSUE TITLE
Purge Blocks to a specific height

### ISSUE THREAD

**Issue by dmigwi** [trezor/blockbook#213]
In decred we have a reorganization (or reorg) of the blockchain where a set of blocks are replaced with another set which has more work. The number of blocks replaced is the depth of the reorg. The old set of blocks goes to side chains not available on re-sync.

Can we have an implementation accessible to the `bchain.coin` package that allows a number of blocks to be dropped?

**Comment by martinboehm** [comment]
I do not exactly understand what you need. 
Blockbook does support reorgs. It detects that it is on wrong chain, removes old blocks from the DB and re-syncs to the new chain.
Please explain more in detail what do you want to achieve.

**Comment by dmigwi** [comment]
That sounds helpful and I will check the reorg implementation supported.

**Comment by martinboehm** [comment]
There is a configuration parameter https://github.com/trezor/blockbook/blob/104f6f9a9d711b5e4f9f1ba4ed30527eada83bc3/configs/coins/bitcoin.json#L57
which specifies the maximum depth of reorg that Blockbook supports, by default 300 blocks. If reorg is deeper, Blockbook will report an error and the whole DB will have to be reindexed.

If you think that there is a chance of deeper reorgs, change it to some higher number for your coin.

**Comment by dmigwi** [comment]
Hi! @martinboehm, How exactly does the block reorg / purging some unwanted blocks during the sync work?

I tried sending an older block than requested through `GetBlock` in an effort to remove the unwanted blocks during sync but I got this error:

```bash
F0626 05:24:47.817345   21867 sync.go:271] writeBlockWorker skipped block, expected block 80741, new block 80740
```

My implementation using the reorg concept isn't that great but I wondering if their is a way to drop some blocks and probably reset the height from where the sync should proceed from?

**Comment by martinboehm** [comment]
You have to return a newest block hash using `chain.GetBestBlockHash` and then different (then already synchronized) block hash at Blockbook's synchronized height (`chain.GetBlockHash`). Blockbook then decreases in a loop height by one and compares the hash in DB with hash returned by `chain.GetBlockHash` until it finds math. All blocks that did not match are removed and synchronization starts again. See the code here https://github.com/trezor/blockbook/blob/b1810dc06bd7dc4f88fca8100cae860de6b21c53/db/sync.go#L87-L110
and the content of the `handleFork` method.

**Comment by dmigwi** [comment]
This reorg implementation seems to work only before the first sync runs, Is there a way to do it while the first sync is in progress?

**Comment by dmigwi** [comment]
This is the case scenario that I am trying to fix.

The proof of stake implementation which could benefit from the reorg during sync works like this:

When a block is mined on decred block chain as the best block, it doesn't have the confirming votes cast to validate it. The next consecutive block mined either validates or invalidates that block whereby the txs in the invalidated block are mined in other following blocks.

I was hopeful that a reorg implementation during sync would help me address that unique concern on decred's part since I don't have access to the db so as to drop/delete txs in the invalidated block.

**Comment by dmigwi** [comment]
Also does one have to restart the code for reorg to work?

**Comment by martinboehm** [comment]
>This reorg implementation seems to work only before the first sync runs, Is there a way to do it while the first sync is in progress?

On the contrary, during the inital sync we do not expect any reorg as the initial sync is starting with old blocks with many confirmations. Only in the end, close to the chain top there can be a reorg.

>When a block is mined on decred block chain as the best block, it doesn't have the confirming votes cast to validate it. The next consecutive block mined either validates or invalidates that block whereby the txs in the invalidated block are mined in other following blocks.

I do not really see any difference to let's say Bitcoin but I probably do not understand the decred implementation enough.

>Also does one have to restart the code for reorg to work?

No, you do not have to restart.

**Comment by dmigwi** [comment]
>On the contrary, during the inital sync we do not expect any reorg as the initial sync is starting with old blocks with many confirmations. Only in the end, close to the chain top there can be a reorg.

ok. Noted. Is there a way that I could remove the transaction details of an invalidated block that falls within the max reorg depth during the first sync?

**Comment by dmigwi** [comment]
I wish there was a function similar to this code, accessible to the coins package which could help me delete the unwanted transactions in the invalidated block during the first sync. I am experiencing some bugs due to the hacks I have resorted to in order to avoid transactions in invalidated blocks from being saved in the rocksdb.

https://github.com/trezor/blockbook/blob/b1810dc06bd7dc4f88fca8100cae860de6b21c53/db/rocksdb.go#L1282-L1340
