### ISSUE TITLE
Please add CORS headers in public API endpoints

### ISSUE THREAD

**Issue by Polve** [trezor/blockbook#214]
I use some of the public APIS like https://tbtc1.trezor.io/api/v1/ for fast prototype of apps but I can't use the endpoints from the browser because it misses CORS headers.

Could you add them? Something like

>   Access-Control-Allow-Origin: *

should do it

**Comment by martinboehm** [comment]
Hi. We have opened our Testnet servers https://tbtc1.trezor.io and https://tbtc2.trezor.io, so that the community can check the Blockbook functionality.

We will not open Blockbook endpoints for any mainnet coin. For production use, it is necessary to install Blockbook on own infrastructure.
