### ISSUE TITLE
how orphans are processed if the data on them is indexed

### ISSUE THREAD

**Issue by salisbury-espinosa** [trezor/blockbook#232]
i found that bitcoin and ethereum can rollback
(
https://github.com/trezor/blockbook/blob/49b50f3353450bb31eeb243cc51c6a79e438d91e/docs/rocksdb.md
```
blockTxs

Maps block height to data necessary for blockchain rollback. Only last 300 (by default) blocks are kept. The content of value data differs for Bitcoin and Ethereum types.

Bitcoin type
The value is an array of txids and input points in the block.
```
)
what about the rest of the coins?
https://github.com/trezor/blockbook/blob/7f63acaaffec10a0b40bb3f3dc01d483885e3460/bchain/baseparser.go#L16

is `BlockAddressesToKeep`  counted in these coins for rollback in the case of orphan?

**Comment by martinboehm** [comment]
All other coins can rollback too. They inherit the rollback code from Bitcoin or Ethereum. The `BlockAddressesToKeep` setting can override the default 300 blocks for any coin.
