### ISSUE TITLE
Upgrading data version of database?

### ISSUE THREAD

**Issue by samadsajanlal** [trezor/blockbook#234]
I have an older version of blockbook running which utilizes data format version 3. The current release is up to version 5. The coin I run BB for is bitcoin-based (called GameCredits). 

Are there any official data migration/upgrade steps so that I don’t have to reindex the entire chain into blockbook? It would save me multiple days of effort since the server I have is low on computing resources.

Thanks

**Comment by martinboehm** [comment]
Hi. Unfortunately, there is no migration procedure. You have to delete the old database and reindex again. A special migration procedure would probably need similar (or larger) amount of resources as full reindex.
