### ISSUE TITLE
add RBF field to transaction response

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/blockbook#237]

**Comment by martinboehm** [comment]
After discussion with @szymonlesisz, we decided to detect RBF transactions using sequence values, as specified in BIP125. No change in Blockbook necessary.

**Comment by szymonlesisz** [comment]
reopening, 
I think this info should be visible at least in the explorer and it should be visible enough (using some colour field?) that pending transaction is not final and it could be overriden
