### ISSUE TITLE
Decred: xpub_magic fails to parse

### ISSUE THREAD

**Issue by dajohi** [trezor/blockbook#243]
Decred needs to use https://github.com/decred/dcrd/tree/master/hdkeychain

**Comment by martinboehm** [comment]
I do not know exactly what the problem is, however if you need some special functionality for address derivation, you will have to override `BitcoinParser.DeriveAddressDescriptors` and `BitcoinParser.DeriveAddressDescriptorsFromTo` in the decred parser and implement it.

**Comment by dajohi** [comment]
yep, working on a patch :)

**Comment by dajohi** [comment]
https://github.com/decred/dcrd/pull/1800

**Comment by dajohi** [comment]
Not sure how to pull that in unless blockbook repo converts to go modules and drops dep.

**Comment by martinboehm** [comment]
What exactly is the reason that you cannot use our hdkeychain? If it is minor, you could make a pull request to this repo https://github.com/martinboehm/btcutil.

**Comment by martinboehm** [comment]
If you rebase your PR to the latest master, it should reference the btcutil library with your changes.

**Comment by martinboehm** [comment]
I think I can close this as the Decred pull request is proceeding.
