### ISSUE TITLE
Litecoin address parsing issue

### ISSUE THREAD

**Issue by cpacia** [trezor/blockbook#254]
This seems like an oversight on the part of litecoin devs but it's also not handled in the btcutil lib used by blockbook...

The issue is _legacy_ litecoin addresses can start with `ltc1` which is also the same prefix used by segwit. The address deserialization code makes the decision whether to deserialize as legacy or segwit based on the prefix. If you generate a legacy address that starts with `ltc1` then blockbook tries and fails to deserialize it as segwit. This prevent tx/utxo queries for that address and renders it unspendable for the wallet. 

The probability of generating such a legacy address is roughly 1 in 45,000. 

I can submit a PR to the btcutil dependency to fix the problem if you would like.

**Comment by martinboehm** [comment]
Yes please, submit the PR to the btcutil.

**Comment by martinboehm** [comment]
@cpacia Could you give me a transaction showing this issue, please?
