### ISSUE TITLE
Monacoin testnet backend starts on wrong port

### ISSUE THREAD

**Issue by wakiyamap** [trezor/blockbook#265]
It seems that the same problem as this issue(https://github.com/trezor/blockbook/issues/199) is occurring.
I confirmed the same symptoms with Litecoin.

I have a question here. Should I make a conf for the coin like Bitcoin cash?

**Comment by martinboehm** [comment]
If the problem could be solved by using a different (but existing) config template, use it please, otherwise create a new conf.

**Comment by wakiyamap** [comment]
OK. Thanks!!
