### ISSUE TITLE
explorer: Very wrong values on some addresses

### ISSUE THREAD

**Issue by karel-3d** [trezor/blockbook#27]
This testnet address 

2N8hwP1WmJrFF5QWABn38y63uYLhnJYJYTF

has very different end balance than it should.

It should have 0.2 btc, it has around 1 000 000 btc on blockbook explorer

**Comment by martinboehm** [comment]
The problem is fixed by commit f2274ce43ce3403bf14994ce367048f59c4310c2. However, there still might be rounding errors in the balance, which will be resolved by usage of bigints for amounts.
