### ISSUE TITLE
Address API - some ETH tokens info is missing

### ISSUE THREAD

**Issue by wrwr** [trezor/blockbook#271]
Response for: `/api/v2/address/0x07e211d8595c2a06cc5c23e7294f718cedc2c751`:
```{
  "page": 1,
  "totalPages": 1,
  "itemsOnPage": 1000,
  "address": "0x07e211d8595c2a06cc5c23e7294f718cedc2c751",
  "balance": "0",
  "unconfirmedBalance": "0",
  "unconfirmedTxs": 0,
  "txs": 3,
  "txids": [
    "0x0bce46606f9aa866d69d191fbd1b3e2852285564230667b25b3caf4c5e939d50",
    "0xc0b5b8276eeb6042001e8b5ca38a90cfb9d0450f9fea2e607c5dd3c69865e947",
    "0xa5ac5b27ae20d201053f400c34694eae8cd29486b8da44b08704c6196173a358"
  ],
  "nonce": "0",
  "tokens": [
    {
      "type": "ERC20",
      "name": "0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359",
      "contract": "0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359",
      "transfers": 1
    },
    {
      "type": "ERC20",
      "name": "ERC20",
      "contract": "0xc3761eb917cd790b30dad99f6cc5b4ff93c4f9ea",
      "transfers": 1,
      "symbol": "ERC20",
      "decimals": 18,
      "balance": "66256"
    },
    {
      "type": "ERC20",
      "name": "Amber Token",
      "contract": "0x4dc3643dbc642b72c158e7f3d2ff232df61cb6ce",
      "transfers": 1,
      "symbol": "AMB",
      "decimals": 18,
      "balance": "100000000000000000"
    }
  ]
}
```
There is no `symbol`, `decimals` and `balance` for the first token. It's [Dai Stablecoin v1.0](https://etherscan.io/token/0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359). Corresponding contract methods exist and return valid data (by `eth_call`) but Blockbook API does not return them

**Comment by martinboehm** [comment]
I checked it and the methods `name` and `symbol` do not return valid data for the contract 0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359. Neither Blockbook nor Web3.js are able to parse the data returned by it.

See the difference in data returned by method `name` between (a randomly chosen) ERC20 Chroma contract 0x915044526758533dfb918eceb6e44bc21632060d and data returned by Dai Stablecoin v1.0.

Chroma 0x915044526758533dfb918eceb6e44bc21632060d returns 3x32 bytes (0, length of data, data):
```
0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000064368726f6d610000000000000000000000000000000000000000000000000000
```

Dai Stablecoin v1.0 0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359 returns 32 bytes (only data):
```
0x44616920537461626c65636f696e2076312e3000000000000000000000000000
```

Theoretically, Blockbook could detect this type of returned data and parse it, I am just not sure if it is the right thing to do.

**Comment by martinboehm** [comment]
The contract name 0x52903256dd18d85c2dc4a6c999907 INS Promo (INSP) is not parsed. 
Also, for contract which are not parsed, the balance is not shown.

**Comment by martinboehm** [comment]
The contract 0x52903256dd18d85c2dc4a6c999907c9793ea61e3 is self destructed. The blockchain has no information about it anymore so it is not possible to get its name or balance.
Etherscan is obviously storing info about self destructed contract in a database outside of blockchain as it can show info about it.
