### ISSUE TITLE
repeated utxos (unconfirmed and confirmed)

### ISSUE THREAD

**Issue by brucexiu** [trezor/blockbook#275]
I called v1/utxo/<addr>?confirmed=false 
And I got two repeated utxo. One is unconfirmed and the other is confirmed.

```json
[
  {
    "result": [
      {
        "txid": "f578781d91f63046ab2550ec06e763b38e6fa6480be72213f3aa93d8588e6761",
        "confirmations": 0,
        "txindex": 1,
        "amount": 71652062,
        "address": "1KepomkPWUuwkHdG27yqziedtxgSkGPWmR"
      },
      {
        "txid": "f578781d91f63046ab2550ec06e763b38e 6fa6480be72213f3aa93d8588e6761",
        "confirmations": 1,
        "txindex": 1,
        "amount": 71652062,
        "address": "1KepomkPWUuwkHdG27yqziedtxgSkGPWmR"
      }
    ],
    "id": 1
  }
]
```

A mutex is used when adding and updating utxos, but not fetching utxos. I think that caused the issue.

**Comment by martinboehm** [comment]
Hi, the option `confirmed=false` (a default option) means unconfirmed together with confirmed. The option `confirmed=true` means only confirmed.

**Comment by brucexiu** [comment]
@martinboehm

Yes. 
But please look carefully at the two utxos. The two utxos have the same txid and txindex. Actually they are the same.

Thanks for your reply.
