### ISSUE TITLE
Feature: Historical fiat rate

### ISSUE THREAD

**Issue by slush0** [trezor/blockbook#277]
For rich UI we would need to know historical fiat rate for particular coin at the time of the transaction. For such use case I propose MVP in a form of timestamp->price index with related API calls. I consider USD rate enough for this time (as other currencies can be converted on the fly from the USD rate), but it would be awesome if data structures would not be limited to USD or single currency by itself.

I suppose Coingecko is a good source for fetching historical prices as we use this feed in Wallet already. There's also Go library for Coingecko already: https://www.coingecko.com/api/documentations/v3

**Comment by martinboehm** [comment]
API:
input: {timestamps[], currency}
output: {input_timestamp, data_timestamp, input_currency_rate, USD_rate}[]

**Comment by martinboehm** [comment]
Done, will be part of 0.3.2 release.
