### ISSUE TITLE
Feature: Actual fiat rates

### ISSUE THREAD

**Issue by slush0** [trezor/blockbook#278]
Related to #277, it would be useful to enrich client API to pub/sub mechanism for updating current fiat rates in Wallet. Currently the Wallet uses Coingecko's native API, but there're many reasons to proxy this logic over Blockbook:

a) Lower load to provider's service
b) Consolidate traffic from Wallet, so Wallet always talks to only one service (blockbook).
c) Allow easy debugging/switching/caching the backend service in case provider goes offline.
d) Using existing Blockbook connection with push mechanism would also increase accuracy of the rate in Wallet. Currently Wallet polls provider service every few minutes.

**Comment by martinboehm** [comment]
API:

current rate (possible to subscribe/unsubscribe via Websocket):
input: {currency}
output:  {data_timestamp,currency_rate,USD_rate}

list of currencies:
input:
output: currency[]

**Comment by martinboehm** [comment]
Done, will be part of 0.3.2 release.
