### ISSUE TITLE
explorer: rawtx

### ISSUE THREAD

**Issue by karel-3d** [trezor/blockbook#28]
From all the functionality in explorer, I would like some easy way to see raw tx, just hex

similar to bitcore

https://testnet.blockexplorer.com/api/rawtx/778a2656159c9542d3c3d8182e866e08c58bde08a9acd188de6cc450b2d48fb7

**Comment by martinboehm** [comment]
Implemented in commit https://github.com/trezor/blockbook/commit/175c84187098d8110eb4dc39a3a9aafd250daf2c. Both html view of a tx and the json api return tx hex.
