### ISSUE TITLE
Feature: Hide large input or output for utxo transaction

### ISSUE THREAD

**Issue by minkcrypto** [trezor/blockbook#281]
For example

![캡처](https://user-images.githubusercontent.com/52137633/64078353-9e46f080-cd14-11e9-9079-2d5a339c6a12.PNG)

This should be summarized

![캡처](https://user-images.githubusercontent.com/52137633/64078379-c6365400-cd14-11e9-9415-7a18d769bf28.PNG)

Like this one

**Comment by martinboehm** [comment]
We are aware that some explorers merge inputs or outputs of the same address, however we are not going to implement this feature at this moment.
