### ISSUE TITLE
New node versions 

### ISSUE THREAD

**Issue by d1vo1t** [trezor/blockbook#290]
Once a full node is built using a certain version ie zcash v2.0.6 and how do we upgrade to v2.0.7? 
1 I can understand I need to stop the service 
2 may be clone the new zcash version 
3 where do I update so that block book picks up v2.0.7

**Comment by martinboehm** [comment]
It is easy, just stop the backend, upgrade it and start it again. You do not even have to stop Blockbook. You can use our docker build to generate package for zcash v2.0.7 backend, it is already in master.
