### ISSUE TITLE
blockbook-zcash service fails to start 

### ISSUE THREAD

**Issue by f4r4** [trezor/blockbook#299]
1- Checked the backend-zcash service and its in full sync and working 
2- When I checked blockbook-zcash service this was the output 
```
Oct 03 05:25:22 ns3142437 systemd[1]: blockbook-zcash.service: Failed with result 'exit-code'.
Oct 03 05:25:22 ns3142437 systemd[1]: blockbook-zcash.service: Service hold-off time over, scheduling restart.
Oct 03 05:25:22 ns3142437 systemd[1]: Stopped Blockbook daemon (Zcash).
Oct 03 05:25:22 ns3142437 systemd[1]: blockbook-zcash.service: Start request repeated too quickly.
Oct 03 05:25:22 ns3142437 systemd[1]: Failed to start Blockbook daemon (Zcash).
Oct 03 05:25:22 ns3142437 systemd[1]: blockbook-zcash.service: Unit entered failed state.
Oct 03 05:25:22 ns3142437 systemd[1]: blockbook-zcash.service: Failed with result 'exit-code'.
```

3. last log on blockbook/zcash/logs/

```
Log file created at: 2019/10/03 05:25:22
Running on machine: ns3142437
Binary: Built with gc go1.12.4 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1003 05:25:22.225649   21536 blockbook.go:185] internalState: database is in inconsistent state and cannot be used
```

4. Memory 
```
              total        used        free      shared  buff/cache   available
Mem:             65          34           3           0          27          32
Swap:             3           1           2

```

5. BTC & BCASH fullnode + rocksdb are in full sync 

Please advice on how to debug this ?

**Comment by martinboehm** [comment]
Hi, here is a copy from our main README file:

Error internalState: database is in inconsistent state and cannot be used

Blockbook was killed during the initial import, most commonly by OOM killer. By default, Blockbook performs the initial import in bulk import mode, which for performance reasons does not store all the data immediately to the database. If Blockbook is killed during this phase, the database is left in an inconsistent state.

See above how to reduce the memory footprint, delete the database files and run the import again.

Check [this](https://github.com/trezor/blockbook/issues/89) or [this](https://github.com/trezor/blockbook/issues/147) issue for more info.
