### ISSUE TITLE
Insight API backwards compatibility, call to /api/txs?address=

### ISSUE THREAD

**Issue by snitko** [trezor/blockbook#3]
Hi, Insight api has this call: https://insight.bitpay.com/api/txs?address=3FRpHy6ZwWDTUGrXY9YFTqnC1P9WMho7MF while blockbook doesn't seem to support it:

https://btc-bitcore1.trezor.io/api/txs?address=3FRpHy6ZwWDTUGrXY9YFTqnC1P9WMho7MF

Perhaps you can suggest another API request that would accomplish the task of getting new transactions to an address.

**Comment by orangeman** [comment]
does not look like insight api https://github.com/trezor/blockbook/blob/master/server/https.go#L45-L51 but looks like a nice API :-)

The readme says 

> create/integrate blockchain explorer

Are there any concrete plans to integrate existing explorers / APIs?

**Comment by martinboehm** [comment]
Sorry, blockbook is developed as backend for Trezor wallet only and will not support complete bitcore API. In addition to that, the implemented interfaces can change in future without notice. We discourage everybody from using it as general blockchain API.
