### ISSUE TITLE
Invalid BlockHeight for unconfirmed transactions

### ISSUE THREAD

**Issue by s-mohammad-dabir** [trezor/blockbook#301]
Hello,
If you request an unconfirmed transaction block hash with "{Block book server URL}/api/v2/tx/{Unconfirmed TX hash}" in the response json you will get the property "blockHeight" with 0 value. 
As you know 0 is the block height of "Gensis block" and block height of an unconfirmed transaction is -1. Maybe the "0" for confirmations of an unconfirmed made the developer confused.

**Comment by martinboehm** [comment]
Hi, could you please give me an example how to reproduce the described behaviour.

**Comment by s-mohammad-dabir** [comment]
Hello,
First create an unconfirmed transaction (or just find one in a live blockexplorer). Then create a request to an alive blockbook node in this format:
http(s)://<Blockbook Url>/api/v2/tx/<Unconfirmed Transaction hash>

Then you have a json response including this properties:

```
{
    "txid": "<txid of you unconfirmed tx>",
    ...
    ...
    **"blockHeight": 0,
    "confirmations": 0,**
    ...
}
```

Value of confirmations is correct. Because transaction is unconfirmed, but -1 is expected for block height instead of 0 (Block height of gensis block).

In other parts of blockbook api like websocket api, -1 is used for height of unconfirmed tranasctions.

Thank you for your consideration.

**Comment by martinboehm** [comment]
Thank you, now I see it. We will fix it. 

Btw you can see a list of unconfirmed transactions in Blockbook. It is a bit hidden, but if you go to the Status page, there is a link with the number of transactions in the mempool, which leads to the list of transactions.

**Comment by s-mohammad-dabir** [comment]
Great job. Thank you
