### ISSUE TITLE
Can't start blockbook-bitcoin.service after server migration

### ISSUE THREAD

**Issue by dappway** [trezor/blockbook#302]
sudo systemctl status blockbook-bitcoin.service

● blockbook-bitcoin.service - Blockbook daemon (Bitcoin)
   Loaded: loaded (/lib/systemd/system/blockbook-bitcoin.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Mon 2019-10-07 14:10:28 UTC; 1 day 3h ago
 Main PID: 10074 (code=killed, signal=ILL)
      CPU: 20ms

жов 07 14:10:28 belcobtm-prod systemd[1]: blockbook-bitcoin.service: Failed with result 'signal'.
жов 07 14:10:28 belcobtm-prod systemd[1]: blockbook-bitcoin.service: Service hold-off time over, scheduling restart.
жов 07 14:10:28 belcobtm-prod systemd[1]: Stopped Blockbook daemon (Bitcoin).
жов 07 14:10:28 belcobtm-prod systemd[1]: blockbook-bitcoin.service: Start request repeated too quickly.
жов 07 14:10:28 belcobtm-prod systemd[1]: Failed to start Blockbook daemon (Bitcoin).
жов 07 14:10:28 belcobtm-prod systemd[1]: blockbook-bitcoin.service: Unit entered failed state.
жов 07 14:10:28 belcobtm-prod systemd[1]: blockbook-bitcoin.service: Failed with result 'signal'.

**Comment by martinboehm** [comment]
Sorry, from the log you posted, without any other context, I have no idea what is going on. I think you will have to investigate yourself.
