### ISSUE TITLE
blockbook-bitcoin.service slow sync

### ISSUE THREAD

**Issue by h3105** [trezor/blockbook#308]
Hello there,
In search for a coin-indexer for my company I found blockbook, and tried to sync few coins.
It all went well (even with Ethereum) but now I am struggling with following issue:
The synchronisation of the blockbook mempool takes a very long time.
In numbers:
The blockbook-bitcoin.service is syncing at a pace of 4772.4 block per day.
Based on my calculation blockbook will take aprox another 21.57 days to fully sync the mempool with the backend.

Blockbook is running in following environment:

xenserver => Debian 9 "Stretch" VM

37GB RAM
12 vCPU's
more then 1TB storage

Output from curl -k https://serveraddress:9030/api:
```
{
    "blockbook": {
        "coin": "Bitcoin",
        "host": "xxx",
        "version": "0.3.1",
        "gitCommit": "83b1552",
        "buildTime": "2019-10-07T08:10:33+00:00",
        "syncMode": true,
        "initialSync": true,
        "inSync": false,
        "bestHeight": 498527,
        "lastBlockTime": "2019-10-28T15:28:40.240936238+01:00",
        "inSyncMempool": false,
        "lastMempoolTime": "0001-01-01T00:00:00Z",
        "mempoolSize": 0,
        "decimals": 8,
        "dbSize": 136521011644,
        "dbColumns": [
            {
                "name": "default",
                "version": 5,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "height",
                "version": 5,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "addresses",
                "version": 5,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "blockTxs",
                "version": 5,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "transactions",
                "version": 5,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "addressBalance",
                "version": 5,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "txAddresses",
                "version": 5,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            }
        ],
        "about": "Blockbook - blockchain indexer for Trezor wallet https://trezor.io/. Do not use for any other purpose."
    },
    "backend": {
        "chain": "main",
        "blocks": 601387,
        "headers": 601387,
        "bestBlockHash": "0000000000000000000a0b54027781c324083e5880724cce245af2e718f30c38",
        "difficulty": "13691480038694.45",
        "sizeOnDisk": 279867830914,
        "version": "180100",
        "subversion": "/Satoshi:0.18.1/",
        "protocolVersion": "70015"
    }
}
```

Is there anything I am overlooking, or anything I can do to fasten the synchronisation?

**Comment by martinboehm** [comment]
The initial sync of bitcoin is certainly the most time consuming from all coins and requires the most resources. Your server specs look reasonable. Is the storage SSD?

**Comment by h3105** [comment]
Unfortunately we only use HDD's in our blades. So do you think the slow sync-speed falls back to the storage-type?

**Comment by martinboehm** [comment]
Yes, the initial sync is doing a huge amount of lookups in the database, you will probably have to be patient.
We run all our Blockbooks on SSDs and do not have experience with HDDs. Please let us know how it runs, after the initial sync.

**Comment by h3105** [comment]
Thank you for your response. Unfortunately the synchronisation is getting slower over time.
At actual rate it will take another 26 days to fully sync.
Can I stop the backend? Im concerned that at this rate the indexer won't be able to catch-up with the backend.

**Comment by martinboehm** [comment]
Unfortunately, the speed of sync is not linear as the size of the database in which the lookups are done is growing (and also the number of transactions per block grew to certain extent, especially during the peek price times).

You can stop the backend at any time. However, I would not worry that the indexer would not be able to catch up with the backend as long as one block is indexed faster than in 10 minutes on average.

**Comment by h3105** [comment]
I'll put in more infos as soon as blockbook fully synchronized.

**Comment by h3105** [comment]
Finally blockbook finished syncinc after almost 2 month's. As far as I can see, it seems to work allright.
Now im analysing ways of deploying blockbook on different server's and i came up with following:
Storing a dump of the RocksDB and the backend-data - If I need a new server I can download the data on a new server and setup blockbook. Anyway I think it's still kind of a troublesome process..

Do you have an idea for a better workflow to transfer the synced data to a new server?

**Comment by martinboehm** [comment]
Thank you for the report. 
To transfer the database, stop Blockbook and then copy the DB files to a new server.

**Comment by Sonmezturk** [comment]
I'm in the same situation, now it is loading blocks very slowly. When I look at the backend, it follows two years behind. What can I do to speed it up?

**Comment by Sonmezturk** [comment]
> I'm in the same situation, now it is loading blocks very slowly. When I look at the backend, it follows two years behind. What can I do to speed it up?

CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
Stepping:                        7
CPU MHz:                         3600.423
BogoMIPS:                        5999.96
