### ISSUE TITLE
How to send an raw transaction in Ethereum via blockbook?

### ISSUE THREAD

**Issue by borisowsky** [trezor/blockbook#31]
When I try to send an raw Ethereum transaction via websockets `sendTransaction` method, I get error 'SendRawTransaction: not implemented'. https://github.com/trezor/blockbook/blob/master/bchain/coins/eth/ethrpc.go#L502-L504 - as long its not implemented, how to send transactions in blockbook for Ethereum?

**Comment by martinboehm** [comment]
Blockbook support for Ethereum is still in unfinished, experimental phase. Currently you cannot send transactions. Do not use Blockbook for Ethereum yet.

**Comment by borisowsky** [comment]
@martinboehm okay, thanks.
