### ISSUE TITLE
Add support for SLX, a fork of PIVX

### ISSUE THREAD

**Issue by olegmitrakhovich** [trezor/blockbook#336]
Hello,

Would it be hard to make blockbook work with SLX cryptocurrency? https://github.com/slatecurrency/slate

SLX is a fork of PIVX. It looks like PIVX already works with blockbook, so maybe there is no need to even code anything just setup blockbook as PIVX but run a slated instance instead.

**Comment by martinboehm** [comment]
Sure, go ahead and create a pull request.

**Comment by olegmitrakhovich** [comment]
thank you for the response, is there a pull request number for PIVX? @martinboehm

**Comment by martinboehm** [comment]
PIVX pull request is in this repo, I am quite sure that you can do the github search for it yourselves :)

**Comment by olegmitrakhovich** [comment]
thank you for the response, I found the two commits later :)

https://github.com/random-zebra/PIVX-BlockExplorer/commit/818288cd164df1fad4f727dd7369eb41b1dbc5f2

https://github.com/random-zebra/PIVX-BlockExplorer/commit/24bedfec266eb18f75f5c520875ed46f8a348b9f

**Comment by olegmitrakhovich** [comment]
I made this fork https://github.com/SlateEntertainmentGroup/SLX-blockbook. I don't fully understand how the <coin>parser_test.go works. I am getting this error:

--- FAIL: TestParseBlock (0.00s)
    slateparser_test.go:449: ParseBlock() block size: got 463, want 492
    slateparser_test.go:453: ParseBlock() block time: got 1504351235, want 1578427428
    slateparser_test.go:457: ParseBlock() number of transactions: got 0, want 2

where is the "463" and "1504351235" are coming from? 

Any help is appreciated. please and thank you :)  @martinboehm

**Comment by martinboehm** [comment]
The data to parse are loaded by helperLoadBlock from the folder testdata.

**Comment by olegmitrakhovich** [comment]
thank you for the response that got me a lot further. 

I am now fully synced and attempting to install blockbook with "sudo apt install ./blockbook-slate_0.3.1_amd64.deb". I am getting this error: 

"The following packages have unmet dependencies:
 blockbook-slate : Depends: libgflags2v5 but it is not installable
E: Unable to correct problems, you have held broken packages."

I did some research and found this issue:

https://github.com/trezor/blockbook/issues/45

I did go into this dockerfile and replaced "debian: 9" with "debian: 10" (I am running "Debian GNU/Linux 10 (buster)". here is the commit:

https://github.com/SlateEntertainmentGroup/SLX-blockbook/commit/38478386ae50c6ba6f6f6a790acd40557d641386

I am still getting the same error (depends: libgflags2v5)

Not sure if I have to rebuild and resync again or something else is going on? @martinboehm

**Comment by olegmitrakhovich** [comment]
rebuilding did work, blockbook installed successfully :)  

"internalState: database is in inconsistent state and cannot be used" is my next error but I think its due to low memory, I checked other issues looks like increasing memory helped.

**Comment by olegmitrakhovich** [comment]
adding more memory did work! the explorer works great so far on main net....but how do I switch over between nets? I want it to sync with testnet.

**Comment by martinboehm** [comment]
Install a 2nd instance of Blockbook for the testnet.

**Comment by olegmitrakhovich** [comment]
not sure how to do that, do I just "make all-slate --testnet" ? I added all the code already to make blockbook support slate on testnet. @martinboehm

**Comment by martinboehm** [comment]
make all-slate_testnet

**Comment by olegmitrakhovich** [comment]
perfect. thank you for the quick response. @martinboehm

**Comment by olegmitrakhovich** [comment]
weird, when I do systemctl start backend-slate.service ... it looks like its trying to connect to main net.. I can see in debug.log that it's trying to connect to nodes on main net and keeps getting refused. I also tried systemctl start backend-slate_testnet.service ... that also didn't work. any ideas? @martinboehm

**Comment by olegmitrakhovich** [comment]
what about "systemctl start backend-slate.service" how is that command different when starting blockbook on testnet? at this point "systemctl start backend-slate.service" just starts to sync with main net. @martinboehm

**Comment by martinboehm** [comment]
`make all-slate_testnet` will create two debian packages, one for backend, one for blockbook. They are called something like `backend-slate-testnet_version.deb` and `blockbook-stalate-testnet_0.3.1_amd64.deb`. You install and run the backend first, let is synchronize and then install the blockbook package. If your config in slate_testnet.json is correct, everything will work fine.

**Comment by olegmitrakhovich** [comment]
thank you for the help. In my slate_testnet.json file I had "protect_memory": false ... and it should have been "protect_memory": true .... testnet explorer is working great now. I will clean up some of my commits and make a pull request soon.

**Comment by martinboehm** [comment]
Closing. Make a PR when you are ready.
