### ISSUE TITLE
Go Modules Support

### ISSUE THREAD

**Issue by dmigwi** [trezor/blockbook#341]
Decred (DCR) would like to upgrade their binary dependency from v1.4.0 to v1.5.0. We currently can't be able to successfully make that upgrade because some features of the go modules semantic versioning don't work very well with dep dependency management tool.

@martinboehm, a while back you gave this [response](https://github.com/trezor/blockbook/issues/205#issuecomment-503016557).  By now its clear that Go Modules do have a wide support since it simplifies a lot of the things that are currently done to set up and run a project. 

Has the issue priority changed since then? If not would you kindly consider adding some more priority to the issue? 

Go modules support will be very helpful to decred and many other supported coins.

**Comment by martinboehm** [comment]
Yes, it is probably time to switch to Go Modules. I will let you know here when it is done.

**Comment by dmigwi** [comment]
Hi @martinboehm, If no one is working on this task now, I could submit a PR with the needed fix for you to validate and merge.

**Comment by martinboehm** [comment]
Great, go ahead!

**Comment by martinboehm** [comment]
Blockbook now uses go modules.
