### ISSUE TITLE
Transaction filter have swapped inputs/outputs

### ISSUE THREAD

**Issue by petrkr** [trezor/blockbook#346]
When I will go to some address and select filter "inputs" (or outputs) that shown is exactly opposite.

Means selected "inputs" will show all outputs from that address and when select "outputs" all incoming transaction are shown.

tested on btc1.trezor.io

Regards

**Comment by martinboehm** [comment]
I think it is correct:
Here https://tbtc1.trezor.io/address/2Mztwj4sfaMNW6TBZeyLi4LxjBXh4BuSYWy?filter=inputs the address 2Mztwj4sfaMNW6TBZeyLi4LxjBXh4BuSYWy appears on the left side,
here https://tbtc1.trezor.io/address/2Mztwj4sfaMNW6TBZeyLi4LxjBXh4BuSYWy?filter=outputs
on the right side

**Comment by petrkr** [comment]
No mather on which side address appears.
Consider have address "A"
when I am on page with address "A" and select filter "Inputs" I suppose to see all INPUTs TO that address. Meaning all incoming transactions. So I should see that "A" address on right side as "destination" and lot of sources on left.

same for output, that means "output", "sent", "spend" transactoin FROM that address "A", so I should see addreess "A" on left side with lot of outputs on right.

**Comment by martinboehm** [comment]
It is a matter of opinion, we will not change it.

**Comment by petrkr** [comment]
I do not see what kind of 'opinion' making have it opposite way? There is no logic to have it like this, so I think it is not about opinion, it is regular BUG.
