### ISSUE TITLE
The explorer search bar does not show on mobile phones

### ISSUE THREAD

**Issue by bentonoliver** [trezor/blockbook#348]
### Projects
btc1.trezor.io (probably all of them)

### Expected Behavior
There should be a visible and usable search bar for addresses and transactions, etc.

### Actual Behavior
![image](https://user-images.githubusercontent.com/37402943/72362043-bed77c00-36f2-11ea-98cd-e2678ed62d13.png)![image](https://user-images.githubusercontent.com/37402943/72362073-cac33e00-36f2-11ea-9984-6b8cd9cde051.png)

The search bar does not show on smartphones with smaller screens (smaller than a tablet).

### Reproduction Steps
Access btc1.trezor.io on a mobile phone

### Environment
Chrome, Duckduckgo on Samsung Galaxy S7

**Comment by martinboehm** [comment]
Already fixed in issue #327, will be in the next release
