### ISSUE TITLE
FYSA - Confirmed Homebrew Package Dependencies

### ISSUE THREAD

**Issue by skaht** [trezor/blockbook#35]
Confirmed the following OSX Homebrew package/formula dependencies used to build and run **blockbook** that connected to a Dash Core version v0.12.3.2 (64-bit) full node: 
 
    1. pkg-config:
    2. zlib:
    3. bzip2:
    4. lz4:
    5. gflags:
    6. go:
    7. lxc: go
    8. dep: go
    9. zeromq: pkg-config 
    10. snappy: pkg-config
    11. rocksdb: snappy lz4 gflags     
    12. wget: pkg-config libidn2 openssl

Additional dependency details above resulted from a quick `brew info <formula>` dependency analysis.

**Comment by martinboehm** [comment]
Thank you, we will add it to Blocbook documentation.
