### ISSUE TITLE
Blockbook failure on Bitcoin-SV Genesis Testnet

### ISSUE THREAD

**Issue by g574** [trezor/blockbook#350]
Hi,
There will be a [hard fork on Bitcoin SV](https://bitcoinsv.io/genesis-hard-fork/).
To test it I installed Bitcoin SV v1.0.0 on the Genesis Testnet and Blockbook v0.3.1.
I know Blockbook does not support the SV testnet right now so I created a new file in `configs/coins/`
and I adjusted `bchain/coins/bch/bcashrpc.go` because it mentions SV separately.
There is a 1 Gb block at height 5095 on the testnet. When Blockbook hits 5095 it throws the following error message:
```
I0117 13:20:51.125098       1 mempool_bitcoin_type.go:187] mempool: resync finished in 1.118259ms, 0 transactions in mempool
I0117 13:20:51.126364       1 sync.go:111] resync: local at 5094 is behind
E0117 13:21:28.426895       1 blockbook.go:507] syncIndexLoop readScript: transaction output public key script is larger than the max allowed size [count 999999000, max 33554432]
/app/go/src/blockbook/bchain/coins/bch/bcashrpc.go:104: hash 00000000594e67e882de82f9e65f1758b57c16308f2ecef8fa7f209226e9df33, will retry...
I0117 13:21:30.929609       1 sync.go:111] resync: local at 5094 is behind
I0117 13:21:51.147487       1 mempool_bitcoin_type.go:187] mempool: resync finished in 4.9087ms, 0 transactions in mempool
E0117 13:22:07.044668       1 blockbook.go:511] syncIndexLoop readScript: transaction output public key script is larger than the max allowed size [count 999999000, max 33554432]
/app/go/src/blockbook/bchain/coins/bch/bcashrpc.go:104: hash 00000000594e67e882de82f9e65f1758b57c16308f2ecef8fa7f209226e9df33
I0117 13:22:20.912099       1 mempool_bitcoin_type.go:187] mempool: resync finished in 1.830315ms, 0 transactions in mempool
I0117 13:22:20.912490       1 sync.go:111] resync: local at 5094 is behind
E0117 13:22:55.976122       1 blockbook.go:507] syncIndexLoop readScript: transaction output public key script is larger than the max allowed size [count 999999000, max 33554432]
/app/go/src/blockbook/bchain/coins/bch/bcashrpc.go:104: hash 00000000594e67e882de82f9e65f1758b57c16308f2ecef8fa7f209226e9df33, will retry...
I0117 13:22:58.477962       1 sync.go:111] resync: local at 5094 is behind
I0117 13:23:20.930424       1 mempool_bitcoin_type.go:187] mempool: resync finished in 991.812µs, 0 transactions in mempool
E0117 13:23:33.609984       1 blockbook.go:511] syncIndexLoop readScript: transaction output public key script is larger than the max allowed size [count 999999000, max 33554432]
/app/go/src/blockbook/bchain/coins/bch/bcashrpc.go:104: hash 00000000594e67e882de82f9e65f1758b57c16308f2ecef8fa7f209226e9df33
I0117 13:24:20.950256       1 mempool_bitcoin_type.go:187] mempool: resync finished in 2.500996ms, 0 transactions in mempool
```

My understanding is that the "max allowed size" is set by a [Go variable type](https://github.com/golang/image/blob/master/math/fixed/fixed.go) and it is not configurable in Blockbook.
So is there anything I can do to set it up? Will Blockbook support Bitcoin SV after the hard fork?

**Comment by martinboehm** [comment]
Hi, max allowed block size in Blockbook is set in our fork of the btcd library, as you can see in this commit https://github.com/martinboehm/btcd/commit/8c3dd97a460f9860d22acf2512e02567b7f56447.
It is currently set to `1 << 28`, which is 268MB bytes. As it is of the type uint32, it could be theoretically set to maximum 4GB (`(1 << 32) - 1`).

However I see that you hit a different limit - the size of the public key script, which is currently set to 32MB.

To your question - I think Blockbook will support Bitcoin SV fine as long as will does not exceed the above mentioned limits. I think that the limits are actually set quite reasonable (what is the purpose of an output script which is almost 1GB long?) but we could extend them in case there is a need for it.

**Comment by martinboehm** [comment]
I think Blockbook Bitcoin-SV v1.0.0 runs fine, see https://github.com/trezor/blockbook/issues/363
