### ISSUE TITLE
disconnect append utxo, while spending does not remove

### ISSUE THREAD

**Issue by sidhujag** [trezor/blockbook#355]
I think what you are doing is, when you spend an output you are marking UTXO as spent by changing vout to -1 https://github.com/trezor/blockbook/blob/f0ccab3e01b9789b18700115d9e7d89257f86aaa/db/rocksdb.go#L768 but not removing so you can track balance history but when you disconnect you are appending again here https://github.com/trezor/blockbook/blob/f0ccab3e01b9789b18700115d9e7d89257f86aaa/db/rocksdb.go#L1364

Should it not simply just set the vout from -1 back to the vout index instead of appending again? I'm not seeing where you actually remove spent utxo's in a cleanup anywhere?

**Comment by martinboehm** [comment]
Hi, the spent UTXOs are filtered out when we are packing the AddressBalance structure to be stored in the DB, see https://github.com/trezor/blockbook/blob/f0ccab3e01b9789b18700115d9e7d89257f86aaa/db/rocksdb.go#L1080

**Comment by sidhujag** [comment]
thanks
