### ISSUE TITLE
[Question] How can I change directory of blockbook's data?

### ISSUE THREAD

**Issue by pthor11** [trezor/blockbook#357]
I've tried to change paths from this file from blockbook/configs/environ.json

Backend and Blockbook works well, but when I tried get eth_blockNumber by curl to rpc via 8136 port, I got result 0x0 all the time. I thought I did not change the data directory properly. Hope anyone could help me, thanks.

{
    "version": "0.3.1",
    "backend_install_path": "/opt/coins/nodes",
    "backend_data_path": "/opt/coins/data",
    "blockbook_install_path": "/opt/coins/blockbook",
    "blockbook_data_path": "/opt/coins/data"
}

**Comment by martinboehm** [comment]
Hi. I don't know where the problem could be and actually how is the problem related to the data directories. 
Is Blockbook fully synchronized with the geth backend. Is geth actually fully synchronized to the blockchain? It takes a long time (weeks on a fast machine) and huge amount of disk space (close to 1TB) to fully sync Ethereum.

**Comment by pthor11** [comment]
I changed the geth sync script from: "--syncmode fast --cache 10240 --maxpeers 1000" back to "--syncmode fast --cache 1024" then voila, it worked! 
If I transfer the data directories, such as backend and blockbook data to another machine, it would still works?
