### ISSUE TITLE
Support for ETC Agharta upgrade

### ISSUE THREAD

**Issue by dstranz** [trezor/blockbook#360]
Do you have a plan to upgrade Blockbook getc version to latest one?

* Newest version of getc is required to support Agharta network upgrade
* Blockbook use hardcoded getc 6.0.9 version
https://github.com/trezor/blockbook/blob/master/configs/coins/ethereum-classic.json#L23

BTW it's said that getc already reached end of life. Maybe it's better to upgrade to one of the following backends?
Parity Ethereum https://github.com/paritytech/parity-ethereum/releases
Multi-Geth https://github.com/etclabscore/multi-geth/releases
Multi-Geth https://github.com/multi-geth/multi-geth/releases
Hyperledger Besu https://github.com/hyperledger/besu/releases

**Comment by martinboehm** [comment]
Yes, we plan to do it. We want to use one of the multi-geth backends. Any idea which one of the two we should choose?

**Comment by dstranz** [comment]
@martinboehm I don't know 😕  but original one has more stars, so maybe it's better and more reliable.

**Comment by dstranz** [comment]
@martinboehm: We've replaced our ETC backend with `multi-geth/multi-geth` and it works fine with Blockbook.

**Comment by martinboehm** [comment]
Great news, thank you! Is the getc database compatible with multi-geth or did you have to resync it from start?

**Comment by dstranz** [comment]
@martinboehm We resync it from start.

**Comment by congnt171** [comment]
@dstranz  How can you change right now? 
I have problem with sync ETC right now.
Thanks!

**Comment by martinboehm** [comment]
@congnt171 FYI, before we manage switch to multi-geth, we run manually compiled getc https://github.com/etclabscore/go-ethereum/releases/tag/v6.1.2, which does support Agharta

**Comment by martinboehm** [comment]
Multi-geth is supported now, from this commit https://github.com/trezor/blockbook/commit/7e35bac99cd9fd7b44ca2baf09931ea340515360.
