### ISSUE TITLE
Bcash SV new fork and new version 

### ISSUE THREAD

**Issue by f4r4** [trezor/blockbook#363]
Please update the config file to bsv v1.0.1

**Comment by martinboehm** [comment]
Could you make a pull request with the new version, please?

**Comment by f4r4** [comment]
I tried to install it by editing the binary_url and verification_source after the installation I get this issue ! when I try to start the service :( 

`Job for backend-bcashsv.service failed because the control process exited with error code.
See "systemctl status backend-bcashsv.service" and "journalctl -xe" for details.`

**Comment by martinboehm** [comment]
What error do you see when you run `journalctl -xe`?

**Comment by f4r4** [comment]
sudo systemctl status backend-bcashsv.service
```
Feb 07 09:11:23 ns3083435 systemd[1]: backend-bcashsv.service: Unit entered failed state.
Feb 07 09:11:23 ns3083435 systemd[1]: backend-bcashsv.service: Failed with result 'exit-code'.
Feb 07 09:11:23 ns3083435 systemd[1]: backend-bcashsv.service: Service hold-off time over, scheduling restart.
Feb 07 09:11:23 ns3083435 systemd[1]: Stopped Bcash backend daemon.
Feb 07 09:11:23 ns3083435 systemd[1]: backend-bcashsv.service: Start request repeated too quickly.
Feb 07 09:11:23 ns3083435 systemd[1]: Failed to start Bcash backend daemon.
Feb 07 09:11:23 ns3083435 systemd[1]: backend-bcashsv.service: Unit entered failed state.
Feb 07 09:11:23 ns3083435 systemd[1]: backend-bcashsv.service: Failed with result 'exit-code'.

```

journalctl -xe
```
Feb 07 09:13:51 ns3083435 systemd[1]: backend-bcashsv.service: Start request repeated too quickly.
Feb 07 09:13:51 ns3083435 systemd[1]: Failed to start Bcash backend daemon.
-- Subject: Unit backend-bcashsv.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit backend-bcashsv.service has failed.
-- 
-- The result is failed.
Feb 07 09:13:51 ns3083435 systemd[1]: backend-bcashsv.service: Unit entered failed state.
Feb 07 09:13:51 ns3083435 systemd[1]: backend-bcashsv.service: Failed with result 'exit-code'.
```

**Comment by martinboehm** [comment]
Hmm, that is not very informative. Try to scroll for more info using `journalctl -xe -u backend-bcashsv.service`.

**Comment by f4r4** [comment]
Its the same message is there any other log information apart from journalctl

**Comment by martinboehm** [comment]
Unfortunately this is probably the only source of information. If you create PR, I could try to run it on my server.

**Comment by f4r4** [comment]
Okay done pull request created

**Comment by judong** [comment]
hello @martinboehm @f4r4  setting config file ,set add:
/opt/coins/nodes/bcashsv/bcashsv.conf

```
excessiveblocksize=512000000
maxstackmemoryusageconsensus=512000000
```

next

`systemctl start backend-bcashsv.service`

OK

**Comment by f4r4** [comment]
@judong Same output 
`
Job for backend-bcashsv.service failed because the control process exited with error code.
See "systemctl status backend-bcashsv.service" and "journalctl -xe" for details.
`

**Comment by judong** [comment]
@f4r4 run 
`/opt/coins/nodes/bcashsv/bin/bitcoind -datadir=/opt/coins/data/bcashsv/backend -conf=/opt/coins/nodes/bcashsv/bcashsv.conf -pid=/run/bcashsv/bcashsv.pid`
output print.

**Comment by f4r4** [comment]
/opt/coins/nodes/bcashsv/bin/bitcoind: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /opt/coins/nodes/bcashsv/bin/bitcoind)

**Comment by judong** [comment]
im system ubuntu 18.04 no error.

https://github.com/bitcoin-sv/bitcoin-sv/blob/master/doc/build-unix.md

Take a look at this

**Comment by f4r4** [comment]
As new version of bitcoinsv uses latest glibc therfore this issue is related to the glibc library and openssl
its not recommended to upgrade the glibc library since other programs might be using them I will try to update debian version to 10

**Comment by judong** [comment]
OK use ubuntu 18.04 system....

**Comment by f4r4** [comment]
Using ubuntu now removed the .lock file from and then started the backend-bcahsv now I get 
`Error: Cannot obtain a lock on data directory /home/meemoo/bsvdata/backend Bitcoin SV is probably already running. No such file or directory. `

**Comment by judong** [comment]
@f4r4 
systemctl stop backend-bcashsv.service 
Have a try

**Comment by f4r4** [comment]
Permission issue ! if I am to use a different directory then that directory permission should match the service file ! 
btw BSV working on Ubuntu 18.04 ! thanks guys for the advice, help and support
