### ISSUE TITLE
{"error":"Invalid address, string not all lowercase or all uppercase"}

### ISSUE THREAD

**Issue by atomlab** [trezor/blockbook#364]
Hi, can you help  me to understand the reason this error?

Blockbook for QTUM

```
curl https://10.0.6.83:9188/api/v2/address/Qc1Lgy5dStWUG6gbYRqS7XreD6ZiJmj3yA -k
{"error":"Invalid address, string not all lowercase or all uppercase"}
```

logs
`grep Qc1Lgy5dStWUG6gbYRqS7XreD6ZiJmj3yA  /opt/coins/blockbook/qtum/logs/blockbook.*`
> /opt/coins/blockbook/qtum/logs/blockbook.WARNING:E0205 11:34:39.734030    3341 socketio.go:672] jOCnO8x8BHGYKo_EMakt onSubscribe invalid address Qc1Lgy5dStWUG6gbYRqS7XreD6ZiJmj3yA: string not all lowercase or all uppercase, req: "bitcoind/addresstxid",["Qc1Lgy5dStWUG6gbYRqS7XreD6ZiJmj3yA"]

>/opt/coins/blockbook/qtum/logs/blockbook.qtum-bb-01.blockbook-qtum.log.WARNING.20191017-201753.3341:E0205 11:34:39.734030    3341 socketio.go:672] jOCnO8x8BHGYKo_EMakt onSubscribe invalid address Qc1Lgy5dStWUG6gbYRqS7XreD6ZiJmj3yA: string not all lowercase or all uppercase, req: "bitcoind/addresstxid",["Qc1Lgy5dStWUG6gbYRqS7XreD6ZiJmj3yA"]

blockbook status
`# curl -k  https://10.0.6.83:9188/api/`
>{"blockbook":{"coin":"Qtum","host":"qtum-bb-01","version":"0.3.1","gitCommit":"5d398cc","buildTime":"2019-10-17T14:58:36+00:00","syncMode":true,"initialSync":false,"inSync":true,"bestHeight":542237,"lastBlockTime":"2020-02-06T16:42:55.244493222Z","inSyncMempool":true,"lastMempoolTime":"2020-02-06T16:42:55.188023445Z","mempoolSize":1,"decimals":8,"dbSize":10115655859,"about":"Blockbook - blockchain indexer for Trezor wallet https://trezor.io/. Do not use for any other purpose."},"backend":{"chain":"main","blocks":542237,"headers":542237,"bestBlockHash":"95cb827c9953f209ea9289cf4579a46bf7db788c536d7b7abc8efc286f325cca","difficulty":"3678335.191946767","sizeOnDisk":2619384212,"version":"180100","subversion":"/Satoshi:0.18.1/","protocolVersion":"70017"}}

**Comment by martinboehm** [comment]
Hi, the address Qc1Lgy5dStWUG6gbYRqS7XreD6ZiJmj3yA is incorrectly detected as segwit address.
Could you please try to rebuild a newer version of the Blockbook? I see that your version is from Oct 10, 2019, commit 5d398cc. Just a couple of days later, in the commit https://github.com/trezor/blockbook/commit/262ca3e2e489eea0c07f4ce57d8c6827d60126dd, we upgraded the address parsing library. I think it should correctly handle your case.

**Comment by atomlab** [comment]
Great! It works! Thank you.
