### ISSUE TITLE
[BSV explorer] 'Address' request return the address in the old format

### ISSUE THREAD

**Issue by Atomicwallets** [trezor/blockbook#369]
The request return the address in the old format
`/api/address/18kNhhKcrpdJbjf9vNi9mbPzRFV8T371Sj`

Response
`{"page":1,"totalPages":1,"itemsOnPage":1000,"addrStr":"bitcoincash:qp20ec0glxz8v6w4ntv6knws2r2mlu0kqqyrranjq8","balance":"0.0031687",`

**Suggestion**
If asked address in a new format - return new format address
If asked address in old format - return old format address

**Comment by judong** [comment]
hello ,old format address
config opt/coins/nodes/bcashsv/bcashsv.conf
add
`usecashaddr=0`
config 

/opt/coins/blockbook/bcashsv/config/blockchaincfg.json

delete
`      "address_format": "cashaddr",`

delete db 
over.

**Comment by martinboehm** [comment]
@judong Hi. Could you please verify that the following change https://github.com/trezor/blockbook/commit/10ab17c2c7cd47d0f158c66b76ecb4110d041b1a fixes the address issue? Thanks.

**Comment by judong** [comment]
@martinboehm hi. Yes, it solved the problem. ^ _ ^
