### ISSUE TITLE
Account balance is 0

### ISSUE THREAD

**Issue by Adman** [trezor/blockbook#37]
I added new coin with blockbook servers to coins.json. Then, I sent some tokens to address generated by trezor emulator. Now, I would like to see balance of the account using connect's method `getAccountInfo`. I can clearly see transactions returned by blockbook server, but the balance is still zero. Is blockbook responsible for summing up transactions and returning final balance, or is this a problem on trezor-connect's side?

**Comment by martinboehm** [comment]
Blockbook in the master branch is not summing up the transactions. We are preparing this functionality, but it is not yet finished.

**Comment by knaperek** [comment]
How was this done before? Has it **always** been the responsibility of Blockbook to provide the final balance, or was it the **job of trezor connect** before?
Is it perhaps possible to make trezor-connect do the caluclation of final balance **by itself**, not relying on Blockbook?

**Comment by martinboehm** [comment]
It was so far not the responsibility of Blockbook to provide the final balance. Blockbook is replacement of Bitcore **socket.io** interface, which is not providing the final balance. Blockbook provides data to our wallet (wallet.trezor.io). The wallet computes the final balance from all transactions belonging to the address.
