### ISSUE TITLE
How to enable CORS support?

### ISSUE THREAD

**Issue by dwasyluk** [trezor/blockbook#375]
We have a WebView based client that needs to access the api in a blockbook instance we are hosting. We read https://github.com/trezor/blockbook/issues/214 that indicates there is some way to enable CORS on blockbook as its enabled on several instances Trezor is running for devs.

We see that the go middleware for CORS is also already part of the project (https://github.com/rs/cors) but when we try to enable it via the following code the server crashes on startup.

```
c := cors.New(cors.Options{
    AllowedOrigins: []string{"*"},
    AllowCredentials: true,
    // Enable Debugging for testing, consider disabling in production
    Debug: true,
})
```

Stacktrace:
```
E0228 13:05:26.937437   15988 blockbook.go:116] main recovered from panic: interface conversion: http.Handler is http.HandlerFunc, not http.ServeMux
goroutine 1 [running]:
runtime/debug.Stack(0x74, 0x0, 0x0)
    /opt/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
    /opt/go/src/runtime/debug/stack.go:16 +0x22
main.main.func1()
    /go/src/blockbook/blockbook.go:117 +0xbb
panic(0xfea7e0, 0xc000618000)
    /opt/go/src/runtime/panic.go:522 +0x1b5
blockbook/server.(PublicServer).ConnectFullPublicInterface(0xc00009c680)
    /go/src/blockbook/server/public.go:131 +0x3691
main.mainWithExitCode(0x0)
    /go/src/blockbook/blockbook.go:323 +0x17bf
main.main()
    /go/src/blockbook/blockbook.go:121 +0x3e
```

How can we properly enable CORS support?

**Comment by wakiyamap** [comment]
I put proxy with nginx.
https://gist.github.com/wakiyamap/15122fc22fdc4fda01cc34439824f7a0

**Comment by dwasyluk** [comment]
@wakiyamap thanks for tip, seems like that may be the simplest solution for now. I am still curious how to use the is cors middleware in the blockbook .lock file correctly.

**Comment by martinboehm** [comment]
@dwasyluk Hi, we (Trezor) also run our production Blockbooks behind nginx. CORS support (and other network related configurations) is by intention not implemented in Blockbook, as it is better provided by a specialized app like nginx.
