### ISSUE TITLE
Zcash fee error

### ISSUE THREAD

**Issue by csiocompany** [trezor/blockbook#377]
Zcash estimatefee api or websocket always return -1

**Comment by martinboehm** [comment]
This is the value that the Zcash backend returns. The problem is, the estimate fee algorithm is not able to do the estimations if there are too few transactions in the previous blocks. If you run our setup of the Zcash backend/blockbook, you can easily verify this yourself by running this command:
```
/opt/coins/nodes/zcash/bin/zcash-cli -datadir=/opt/coins/data/zcash/backend -conf=/opt/coins/nodes/zcash/zcash_client.conf estimatefee 10
```
