### ISSUE TITLE
Query address transactons by contract

### ISSUE THREAD

**Issue by kolya182** [trezor/blockbook#379]
Currently if i want to get transactions history of a specific contract:
https://eth1.trezor.io/api/v2/address/:address?details=txs&page=1&pageSize=1000
and filter out like `tokenTransfers.filter(t => t.token === "0x58b6A8A3302369DAEc383334672404Ee733aB239")`
This way is very insufficient.

Would be possible to add option like `contract=<contract_address> to request, that will only return transaction related to contract?

Cc: @martinboehm

**Comment by martinboehm** [comment]
It is there, you can use it.
