### ISSUE TITLE
Query address transactions performance

### ISSUE THREAD

**Issue by JohnsonCaii** [trezor/blockbook#381]
Hi, I am trying to use blockbook to build a stable backend service.

Currently, I've found a problem when using the following API:
```
/api/v2/address/2N66NHXuUhhYzeGycfNXQLatx8UKtvVRFa6?page=1&pageSize=15&details=txs
```
The corresponding code: 
https://github.com/trezor/blockbook/blob/master/api/worker.go#L775
```
tx, err := w.txFromTxid(txid, bestheight, option, nil)
```
I think those code should be hard code like this:
```
tx, err := w.txFromTxid(txid, bestheight, AccountDetailsTxHistoryLight, nil)
```
The reason is RocksDB already has all the tx data, so we can obtain it directly rather than requests to node backend which can improve a lot of performance especially when the network is very busy.

**Comment by martinboehm** [comment]
Hi. Your assumption is wrong, Blockbook does not have all the tx data in the RocksDB index. The most important data missing in the index are the outpoints (txid+vout) spent by input.

However, I added an option `details=txslight`, which does what you want.
