### ISSUE TITLE
Inconsistent Update Times for Unconfirmed UTXOs

### ISSUE THREAD

**Issue by christroutner** [trezor/blockbook#386]
Is Blockbook intended to work with unconfirmed UTXOs? It seems to frequently get into a state where it does not update its index of unconfirmed UTXOs. e.g. If I spend a UTXO, then get UTXO data for that address, it will give me the spent UTXO and not the new UTXO.

This state seems inconsistent. I've been developing [this benchmark test](https://github.com/christroutner/benchmark-bch/blob/master/docs/test02-indexer.md) which tests the ability of an indexer (like Blockbook) to update its database when dealing with rapidly spent child UTXOs. Blockbook has performed really well in this test.

However, when using Blockbook on a daily basis for my wallets, it will frequently get into a state where it only updates the UTXOs on every block confirmation. Until a block confirms, it will only return stale UTXO data and will not update its UTXO index until a block confirmation occurs. 

If you have suggestions on what I can do to investigate this behavior further, please let me know. If there are older Issues that capture this behavior and possible solutions, please point me in that direction.

I'm using Blockbook v0.3.0. I noticed there has been a couple version updates. Is this an issue that might have been fixed in a new version?

**Comment by christroutner** [comment]
I'm still seeing long-lived stale UTXOs in the latest version.

**Comment by martinboehm** [comment]
Hi, could you be more specific? Give me an example, please?

**Comment by christroutner** [comment]
Sure, I can give an example. 

I have this command-line wallet I've created for BCH and SLP tokens called [slp-cli-wallet](https://github.com/christroutner/slp-cli-wallet). The `send` command will use Blockbook to find UTXOs candidates for spending. It will then call this [selectUtxo() subfunction](https://github.com/christroutner/slp-cli-wallet/blob/master/src/commands/send.js#L206) to select the best UTXO for spending.

As part of the check, the [UTXO is validated](https://github.com/christroutner/slp-cli-wallet/blob/master/src/commands/send.js#L224-L231) with the full node, using the [getTxOut](https://github.com/christroutner/slp-cli-wallet/blob/master/src/util.js#L221) RPC call.

The UX has been that the wallet app consistently throws errors about stale UTXOs. These are UTXOs returned by Blockbook, that have been recently spent and are not actually valid UTXOs. If I try to generate a transaction using them, they will be rejected by the network. 

I can wait several minutes but the stale UTXOs will still be returned by Blockbook. The UTXO index will be updated after a block confirmation, but then the issue will immediately return. For a while, it made me think that Blockbook simply didn't function with unspent UTXOs.

When this behavior for a wallet appears, it repeats consistently. But sometimes the behavior doesn't appear. Sometimes I can spend several child-UTXOs without any issues. But when the issue does appear, it can persist for quite a while.

I'm pretty sure this issue is isolated to Blockbooks processing of unconfirmed UTXOs.

**Comment by martinboehm** [comment]
Several minutes of stale data looks very strange. Is Blockbook using the backend's ZeroMQ? When you start Blockbook, there should be a line in the log with info about MQ. For the ports defined in https://github.com/trezor/blockbook/blob/b4bddc8c0e03a29a4332a6173be7bf73b0ff4a99/configs/coins/bcash.json#L10 it should be
```
I0313 17:20:44.197663   69004 mq.go:60] MQ listening to tcp://127.0.0.1:38331
```
Also, in the log, there should be every couple of seconds a line about mempool:resync and a line about sync of block immediately after a new block is mined. Copy from our bcash log, with mempool and block sync:
```
I0313 17:18:55.814338   15865 mempool_bitcoin_type.go:187] mempool: resync finished in 2.893625ms, 192 transactions in mempool
I0313 17:18:57.649598   15865 mempool_bitcoin_type.go:187] mempool: resync finished in 3.624352ms, 194 transactions in mempool
I0313 17:18:59.276724   15865 mempool_bitcoin_type.go:187] mempool: resync finished in 2.210822ms, 195 transactions in mempool
I0313 17:19:07.226860   15865 mempool_bitcoin_type.go:187] mempool: resync finished in 2.992693ms, 196 transactions in mempool
I0313 17:19:13.593022   15865 mempool_bitcoin_type.go:187] mempool: resync finished in 5.179965ms, 7 transactions in mempool
I0313 17:19:13.739985   15865 sync.go:111] resync: local at 626266 is behind
I0313 17:19:14.010373   15865 socketio.go:720] broadcasting new block hash 00000000000000000145a8f365ddcdec5cf7a76f0b0a5061198eace6f296ac1c to 0 channels
I0313 17:19:14.010410   15865 websocket.go:749] broadcasting new block 626267 00000000000000000145a8f365ddcdec5cf7a76f0b0a5061198eace6f296ac1c to 0 channels
I0313 17:19:14.010422   15865 sync.go:231] resync: synced at 626267 00000000000000000145a8f365ddcdec5cf7a76f0b0a5061198eace6f296ac1c
I0313 17:19:14.010431   15865 sync.go:62] resync: finished in 271.982249ms
I0313 17:19:15.507313   15865 mempool_bitcoin_type.go:187] mempool: resync finished in 1.69703ms, 8 transactions in mempool
```
As you can see in the log, there could be a very short period of time when the mempool/blocks are out of sync, because the backend already removed the mined mempool txs but Blockbook has not yet finished the synchronization, but in the case above it took about 250ms.

For further explanation, if the ZeroMQ connection is not working, Blockbook uses a fallback synchronization mode, which (by default) once every 15 minutes checks for new blocks and once every minute checks the mempool. Please make sure that you are not running in this mode.

**Comment by christroutner** [comment]
I may not have the ZMQ configured properly. Thank you for the guidance. I'll check on this and update the thread once I've investigated it.

**Comment by christroutner** [comment]
Here is the config file I'm using:

```
{
    "coin_name": "Bcash",
    "coin_shortcut": "BCH",
    "coin_label": "Bcash",
    "rpc_url": "http://172.17.0.1:8332",
    "rpc_user": "bitcoin",
    "rpc_pass": "password",
    "rpc_timeout": 25,
    "parse": true,
    "message_queue_binding": "tcp://172.17.0.1:28332",
    "subversion": "",
    "address_format": "",
    "block_addresses_to_keep": 300
}
```

So I've got `message_queue_binding` instead of `backend_message_queue`.

Looking at the output of Blockbook, it does appear that it's picking up on the ZMQ message:

```
Log file created at: 2020/03/13 23:24:00
Running on machine: b0a86e29506d
Binary: Built with gc go1.12.4 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0313 23:24:00.447582       7 blockbook.go:135] Blockbook: {Version:0.3.2 GitCommit:4edc0c4 BuildTime:2020-03-10T05:19:38+00:00 GoVersion:go1.12.4 OSArch:linux/amd64}, debug mode false
I0313 23:24:00.450526       7 bcashrpc.go:61] rpc: block chain mainnet
I0313 23:24:00.450552       7 mempool_bitcoin_type.go:50] mempool: starting with 1*1 sync workers
I0313 23:24:00.450559       7 rocksdb.go:148] rocksdb: opening /opt/coins/data/bcash/blockbook/db, required data version 5, cache size 536870912, max open files 16384
I0313 23:24:25.666888       7 rocksdb.go:1696] loaded 626278 block times
W0313 23:24:25.668777       7 blockbook.go:212] internalState: database was left in open state, possibly previous ungraceful shutdown
I0313 23:24:25.713231       7 worker.go:1610] GetSystemInfo finished in 16.003592ms
I0313 23:24:25.713444       7 internal.go:69] internal server: starting to listen on https://:9030
I0313 23:24:25.723852       7 public.go:122] public server starting to listen on https://:9130
I0313 23:24:25.724624       7 sync.go:111] resync: local at 626277 is behind
I0313 23:25:57.326138       7 sync.go:231] resync: synced at 626317 00000000000000000150ffee74fe153bb659c372fe5659acb4a51ff635aa03af
I0313 23:25:57.326157       7 sync.go:62] resync: finished in 1m31.602355143s
I0313 23:25:57.346140       7 mq.go:60] MQ listening to tcp://172.17.0.1:28332
I0313 23:25:57.467547       7 mempool_bitcoin_type.go:187] mempool: resync finished in 121.371784ms, 25 transactions in mempool
I0313 23:25:57.467579       7 blockbook.go:530] syncIndexLoop starting
I0313 23:25:57.467587       7 blockbook.go:559] syncMempoolLoop starting
I0313 23:25:57.467658       7 blockbook.go:587] storeInternalStateLoop starting with db stats recompute period 26h31m38.45094917s
I0313 23:25:57.467684       7 blockbook.go:707] FiatRates config (/opt/coins/blockbook/bcash/config/blockchaincfg.json) is empty, so the functionality is disabled.
I0313 23:25:59.896613       7 mempool_bitcoin_type.go:187] mempool: resync finished in 1.456075ms, 26 transactions in mempool
I0313 23:26:09.810898       7 mempool_bitcoin_type.go:187] mempool: resync finished in 1.641015ms, 28 transactions in mempool
I0313 23:26:14.959470       7 mempool_bitcoin_type.go:187] mempool: resync finished in 1.23826ms, 29 transactions in mempool
I0313 23:26:19.357250       7 mempool_bitcoin_type.go:187] mempool: resync finished in 136.869279ms, 30 transactions in mempool
I0313 23:26:21.643272       7 mempool_bitcoin_type.go:187] mempool: resync finished in 99.372443ms, 32 transactions in mempool
...
```

I'm picking up on the line with `mq.go:60] MQ listening to tcp://172.17.0.1:28332`

**Comment by christroutner** [comment]
I double checked the server settings. It turned out my mainnet servers were configured correctly, which is where I am seeing the issue. But the testnet server was not, the ZMQ was misconfigured.

We've both highlighted where Blockbook announced the ZMQ connection at startup, but is there a periodic output that would indicate that it is *successfully* getting data from ZMQ? It's one thing to try to connect, but another to actually get live data.

**Comment by christroutner** [comment]
I'm setting up a new Blockbook server for FullStack.cash. I'll update this Issue if I continue to see the stale UTXO issue.

**Comment by christroutner** [comment]
I'm still consistently getting stale UTXO data from Blockbook. If you see any problems with the configurations above, please let me know. I don't know what further steps I can take from here to try and isolate the issue. Please let me know if you have any suggestions. It's important to the Bitcoin Cash community that I solve this problem, so I'm willing to keep pursuing this issue if you can guide me.

**Comment by christroutner** [comment]
I took a another look at all this. It seems that I could really use a way to verify if Blockbook is accurately receiving ZMQ data. It appears that everything is configured correctly, but if I could verify that Blockbook is actually receiving the data, I could rule out if the issue is Blockbook or the network connection.

**Comment by christroutner** [comment]
I've been using ABC v0.21.2 full node. I'm wondering if the output of the full node has divered from the expected ZMQ template. Perhaps that could explain why Blockbook doesn't seem to be able to pick up on the ZMQ connection?

**Comment by christroutner** [comment]
I'm closing this issue, though I may reopen it. I haven't seen this issue in a while, and I suspect the root cause may have been the wrapper for the `getTxOut` RPC call. So not the call itself, but I think the wrapper may have been incorrectly passing arguments to the call. I've since refactored the code, and haven't seen the issue reemerge.
