### ISSUE TITLE
ETC: Make error

### ISSUE THREAD

**Issue by congnt171** [trezor/blockbook#387]
Hi, I try to using Blockbook for sync and running Ethereum Classic but have error on make.
wget https://github.com/etclabscore/core-geth/releases/download/v1.11.0-core/core-geth-linux.zip
--2020-03-10 11:09:58--  https://github.com/etclabscore/core-geth/releases/download/v1.11.0-core/core-geth-linux.zip
Resolving github.com (github.com)... 140.82.118.3
Connecting to github.com (github.com)|140.82.118.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-03-10 11:09:58 ERROR 404: Not Found.

**Comment by martinboehm** [comment]
They released a new version and removed the old binary. It is fixed now...
