### ISSUE TITLE
Bitcoin SV testnet block parsing error

### ISSUE THREAD

**Issue by APshenkin** [trezor/blockbook#388]
1 blockbook.go:267] resyncIndex hash 00000000000001e2166111b3aa0eed6aad8b3da1fa49561b4c6845cb36b61e11: readScript: transaction output public key script is larger than the max allowed size [count 41236249, max 33554432]

This block contains tx with large OP_RETURN script
https://test.whatsonchain.com/block/00000000000001e2166111b3aa0eed6aad8b3da1fa49561b4c6845cb36b61e11

How we can change limit for transaction output?

**Comment by APshenkin** [comment]
Seems like to support this, message size here should be increased

https://github.com/martinboehm/btcd/blob/master/wire/message.go#L27

**Comment by martinboehm** [comment]
Hi, this commit 4338d10dcbd7745364f782c52eb55739e456fd9d could fix your issue. Please try.
