### ISSUE TITLE
Accept4: too many open files; retrying in 1s

### ISSUE THREAD

**Issue by wo4zhuzi** [trezor/blockbook#393]
"Accept4: too many open files; retrying in 1s" appears after synchronization, resulting in slow query

**Comment by martinboehm** [comment]
Hi, I don't know this error message. Please describe the problem more.

**Comment by wo4zhuzi** [comment]
> Hi, I don't know this error message. Please describe the problem more.

I think I know the reason. I put the program in the process management tool 'supervisor' to run. 'Supervisor' has a limit of the maximum number of processing by default, and I restarted after modifying the configuration of 'supervisor'. Thank you for your Reply.
