### ISSUE TITLE
License permissions

### ISSUE THREAD

**Issue by eabz** [trezor/blockbook#394]
Hello, 

I have been using blockbook as the backend of our mobile app. 

The way we use it is just by adding the coin into a fork and then run an instance of if.
In other to increase the usage of our instances as a public service we are planning to do a rebrand of the blockbook to match our own brand.

We want to know if this is allowed by the license you are using and what are the limitations. 

Just to make sure, we are just modifying the brand (logos and colors) we are going to keep the copyright of Trezor on the footer and the links will point to the source on our own organization that is an actual fork of this instance. 

I just want to know if this is possible and if we need permission to do so.

**Comment by martinboehm** [comment]
Hi, Blockbook's license is AGPL-3.0. So yes, you can do the rebranding in the way you suggest.
