### ISSUE TITLE
"GET /api/v1/utxo/" to support multiple address requests in one call

### ISSUE THREAD

**Issue by olegmitrakhovich** [trezor/blockbook#396]
Would it be possible to add support to the "utxo" call to support multiple addresses in one call? This will save making multiple trips when requesting "utxos".  Kind of like what they have on https://chainz.cryptoid.info/api.dws:                                                                                                             "unspent becomes available, this API is similar to blockchain.info's, it has a single active parameter in which you can pass multiple addresses separated by '|'. It returns information about unspent outputs of those addresses."

**Comment by martinboehm** [comment]
Hi. Sorry, we will not be adding this functionality, it is not useful for our use case.
