### ISSUE TITLE
Ether token issue

### ISSUE THREAD

**Issue by csiocompany** [trezor/blockbook#398]
Ether transaction is not displaying in blockbook when transaction comes as token.

Address with such transaction 0x228dd088094cc07222051f6b09ed467a9e8e8316.

So, it can not be accessed and verified through API interface.

**Comment by kolya182** [comment]
https://etherscan.io/address/0x228dd088094cc07222051f6b09ed467a9e8e8316
Here is correct request:
https://eth2.trezor.io/api/v2/address/0x228dd088094cc07222051f6b09ed467a9e8e8316?details=txs
@csiocompany Pease close this issue

**Comment by csiocompany** [comment]
> https://etherscan.io/address/0x228dd088094cc07222051f6b09ed467a9e8e8316
> Here is correct request:
> https://eth2.trezor.io/api/v2/address/0x228dd088094cc07222051f6b09ed467a9e8e8316?details=txs
> @csiocompany Pease close this issue


Are you serious?

Here is output transaction. And where is input one??
Please make sure your answer is correct before answering!

```
{
	"page": 1,
	"totalPages": 1,
	"itemsOnPage": 1000,
	"address": "0x228DD088094CC07222051f6B09ed467A9E8E8316",
	"balance": "0",
	"unconfirmedBalance": "0",
	"unconfirmedTxs": 0,
	"txs": 1,
	"nonTokenTxs": 1,
	"transactions": [{
		"txid": "0xecfd22c940af0ff9c21f3f509668624ebab96c872cad37510a529bbf6ae37bae",
		"vin": [{
			"n": 0,
			"addresses": ["0x228DD088094CC07222051f6B09ed467A9E8E8316"],
			"isAddress": true
		}],
		"vout": [{
			"value": "85422100000000000",
			"n": 0,
			"addresses": ["0x2567283fF0631Ac13699D3B759a055dd237D3F96"],
			"isAddress": true
		}],
		"blockHash": "0x26cefb295966381496a964789a9f126aabbff2c56188f86c0bca14bd2d92231b",
		"blockHeight": 9708265,
		"confirmations": 134023,
		"blockTime": 1584703316,
		"value": "85422100000000000",
		"fees": "186900000000000",
		"ethereumSpecific": {
			"status": 1,
			"nonce": 0,
			"gasLimit": 21000,
			"gasUsed": 21000,
			"gasPrice": "8900000000"
		}
	}],
	"nonce": "1"
}
```

**Comment by martinboehm** [comment]
@csiocompany Hi, Blockbook at this moment does not recognize internal transactions.

**Comment by csiocompany** [comment]
> @csiocompany Hi, Blockbook at this moment does not recognize internal transactions.

So, does it mean that Trezor wallet does not support internal transactions too?

**Comment by martinboehm** [comment]
@csiocompany Trezor can certainly sign a transaction containing internal transaction, however I am not aware that our wallet supports creation of such transactions.
