### ISSUE TITLE
Question about data field in EthereumSpecific 

### ISSUE THREAD

**Issue by hewigovens** [trezor/blockbook#399]
Can we add support for data field?
https://github.com/trezor/blockbook/blob/f0ccab3e01b9789b18700115d9e7d89257f86aaa/api/types.go#L171-L177

**Comment by hewigovens** [comment]
@martinboehm any plan to support data field in `EthereumSpecific`?

**Comment by hewigovens** [comment]
what we really need is data length, so I can add a `DateLen` field to avoid storing data

**Comment by martinboehm** [comment]
I am a bit confused - do you need `DataLen` or `Data`?

**Comment by martinboehm** [comment]
And also, by `data` you mean the content of the field `"input"`, for example the text starting with `"0xa9059cbb000000000000...`, right?:

```
{
  "tx": {
    "nonce": "0xa",
    "gasPrice": "0xc1b71080",
    "gas": "0x160fe",
    "to": "0x8E870D67F660D95d5be530380D0eC0bd388289E1",
    "value": "0x0",
    "input": "0xa9059cbb000000000000000000000000c2c3b3f86fe2c37873714b61df9c9df5d022bd3200000000000000000000000000000000000000000000000d8d726b7177a80000",
    "hash": "0x681f4b8eb7ccdbd99f896967c9493024c4d266d305785f7524b1e203483c2fdc",
    "blockNumber": "0x965668",
    "from": "0x04cd850C7E35ac0e42A35dd6124f5934B5B41500",
    "transactionIndex": "0x7"
  },
  "receipt": {
    "gasUsed": "0xe321",
    "status": "0x1",
    "logs": [
      {
        "address": "0x8E870D67F660D95d5be530380D0eC0bd388289E1",
        "topics": [
          "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
          "0x00000000000000000000000004cd850c7e35ac0e42a35dd6124f5934b5b41500",
          "0x000000000000000000000000c2c3b3f86fe2c37873714b61df9c9df5d022bd32"
        ],
        "data": "0x00000000000000000000000000000000000000000000000d8d726b7177a80000"
      }
    ]
  }
}
```

**Comment by hewigovens** [comment]
Yes, input data starts with "0xa9059cbb..." (this looks like an ERC20 `transfer` call)

> I am a bit confused - do you need `DataLen` or `Data`?

We'd like to have full `Data`, considering data might be too large, a minimum `DataLen` is also acceptable
