### ISSUE TITLE
rpc: bad status, what does this mean

### ISSUE THREAD

**Issue by Muggle-Du** [trezor/blockbook#407]
<img width="1160" alt="截屏2020-04-24 下午5 27 33" src="https://user-images.githubusercontent.com/25078682/80197432-36ea0200-8651-11ea-881d-6929020dd260.png">
ethereum backend wsport is open , but i get this error

**Comment by martinboehm** [comment]
It is not really clear from the image but the port 9030 corresponds to bitcoin ports in our standard settings so maybe it is not correct for ethereum.
