### ISSUE TITLE
How to calculate testTxPacked?

### ISSUE THREAD

**Issue by atomlab** [trezor/blockbook#418]
Hi. Can you explain me please how to calculate `testTxPacked`? As I understand it's base64 encoded string from `testTx1`. For Zcash for example. Thank you!

https://github.com/trezor/blockbook/blob/8a926a0799b0712b356826d2643b99ec387a2e80/bchain/coins/zec/zcashparser_test.go#L21

**Comment by atomlab** [comment]
I have understand. It's just  `getrawtransaction`. 

>curl -s -H 'Content-type:text/plain' -X POST -d '{"jsonrpc": 2.0, "id": 1, "method": "getrawtransaction", "params": ["e64aac0c211ad210c90934f06b1cc932327329e41a9f70c6eb76f79ef798b7b8"]}' http://rpc:rpc@127.0.0.1:8032

output
>{"result":"02000000019c0126.....7e1802","error":null,"id":1}

**Comment by atomlab** [comment]
I have mistaken.

**Comment by martinboehm** [comment]
In case of zcash, the transaction is packed by https://github.com/trezor/blockbook/blob/eb4e10ac677b8c3763fd0c2a5e7f971e4d8cedd1/bchain/baseparser.go#L171

**Comment by gdiscord** [comment]
Trying to integrate a coin and would like to know how to manually construct the packed transaction.
My understanding is that it needs to be used in the [coin]parser_test.go file before the build can successfully complete?

Would appreciate a clear instruction on how to go about it.

thanks
