### ISSUE TITLE
Manual build on armhf: gorocksdb: Ctype_char larger than address space

### ISSUE THREAD

**Issue by zciendor** [trezor/blockbook#42]
Following the [manual build instructions](https://github.com/trezor/blockbook/blob/docs/docs/build.md#manual-build) I run into the following error on **ARM 32-bit (armhf)**:

```
$ cd $GOPATH/src/blockbook
$ go build
# blockbook/vendor/github.com/tecbot/gorocksdb
vendor/github.com/tecbot/gorocksdb/db.go:199: type [1073741824]*_Ctype_char larger than address space
vendor/github.com/tecbot/gorocksdb/db.go:199: type [1073741824]*_Ctype_char too large
```

I opened an issue with the gorocksdb project: https://github.com/tecbot/gorocksdb/issues/145

**Comment by martinboehm** [comment]
I strongly discourage you to build and run Blockbook on a 32bit machine. The memory requirements to do the initial import of Bitcoin are around 32GB and for testnet are smaller but still substantial. After the import the memory requirements are smaller (500MB-5GB) depending on the coin and usage so you will have memory troubles all the time.

**Comment by zciendor** [comment]
> The memory requirements to do the initial import of Bitcoin are around 32GB

Wow, that's insane! Does it index every address ever used in Bitcoin or why is that so heavy?

Might be helpful (for others) if the resource requirements were mentioned on the wiki page [User manual:Running a local instance of Trezor Wallet](https://wiki.trezor.io/User_manual:Running_a_local_instance_of_Trezor_Wallet)
Currently, you kind of get the impression that running a local instance of Trezor Wallet with Blockbook is a little web app which only bridges `bitcoind` daemon with the Trezor wallet web interface.

Would it be possible to use the [Trezor Web-Wallet](https://wallet.trezor.io/data/mytrezor-archive.tgz) with a backend like [Electrum Personal Server](https://github.com/chris-belcher/electrum-personal-server)? We're looking for a nice and lean web-based wallet experience for the self-sovereign user who doesn't want to rely on the servers hosted at trezor.io.

**Comment by martinboehm** [comment]
Yes, index every address ever used in Bitcoin is exactly what it does.

We are in process of updating the documentation, the memory/disk/platform requirements will be there.

Right now it is not possible to use Trezor Web Wallet with "lightweight" backend. We have some plans to make it possible to use the Trezor Web Wallet with SPV node, but it is not yet done.
