### ISSUE TITLE
Enable CI for pull request

### ISSUE THREAD

**Issue by hewigovens** [trezor/blockbook#421]
I just noticed that only master branch has CI, It's better to have it for all pull requests

**Comment by martinboehm** [comment]
We do not want to run our CI for code for which we do not have any control. The pull request could even modify the CI pipeline itself.

**Comment by hewigovens** [comment]
how can you make sure that pull request won't break master code then?

**Comment by martinboehm** [comment]
By reviewing and checking it before merge.
