### ISSUE TITLE
BSV synchronization failed

### ISSUE THREAD

**Issue by wo4zhuzi** [trezor/blockbook#422]
BSV "00000000000000000378547fbe30031f8a98e54574983978c601c75ac0bbade8" block is too large, synchronization failed

E0513 16:04:38.630493   10870 blockbook.go:291] resyncIndex hash 00000000000000000378547fbe30031f8a98e54574983978c601c75ac0bbade8: context deadline exceeded (Client.Timeout or context cancellation while reading body)
I0513 16:04:38.630642   10870 rocksdb.go:287] rocksdb: close

**Comment by martinboehm** [comment]
This looks like it timed out while waiting for the response from the backend. Maybe try to increase the `rpc_timeout` in the config file, it is set by default to 25 seconds.

**Comment by wo4zhuzi** [comment]
@martinboehm After changing the time, there are new problems "http: unexpected EOF reading trailer"

**Comment by martinboehm** [comment]
Maybe you could ask @xiaoyuer97 for their setup because they obviously managed to index the large block
https://bchsvexplorer.com/block/00000000000000000378547fbe30031f8a98e54574983978c601c75ac0bbade8
