### ISSUE TITLE
BSV rpcapi too slow

### ISSUE THREAD

**Issue by lougon** [trezor/blockbook#428]
BSV because the number of transactions in multiple blocks has reached more than 200000, and some blocks have reached 1.1 million (block 634643). When paging, the interface on the chain will be frequently called w.chain.GetBlockInfo (hash), resulting in poor performance

If the amount of data per page is 1000, 1100 times of txhash calls are needed to read 1.1 million data

Can I add a cache optimization?

**Comment by lougon** [comment]
Can you add a cache optimization?

**Comment by lougon** [comment]
The main slow interface is
api/block/

**Comment by wo4zhuzi** [comment]
Are you finished synchronizing your data? I can't sync to 634643. What's your server configuration? Do you need to do anything else? @lougon

**Comment by judong** [comment]
use nginx cache you block rpc.

**Comment by martinboehm** [comment]
Hi. Sorry, we will not be adding caching for GetBlockInfo. The functionality is not interesting for our use case.
