### ISSUE TITLE
How to modify the starting block of "backend" synchronization

### ISSUE THREAD

**Issue by caokun8008** [trezor/blockbook#434]
Thank you for your answers and help, how to modify the starting block of "backend" synchronization, ETH seems to be too slow to synchronize, I want to start synchronization from 10000000 height, how should I configure it? Thanks a lot.

**Comment by caokun8008** [comment]
I had execute "systemctl start backend-ethereum.service" two days ago.
And i opened the /opt/coins/data/ethereum/backend/ethereum.log
tail -f ethereum.log,i see
INFO [05-18|10:36:13.132] Imported new chain segment               blocks=47    txs=5418  mgas=265.377  elapsed=8.003s    mgasps=33.159  number=4310742 hash=b72454…58b6c4 age=2y8mo5d   dirty=255.37MiB
INFO [05-18|10:36:21.137] Imported new chain segment               blocks=49    txs=4509  mgas=249.026  elapsed=8.004s    mgasps=31.110  number=4310791 hash=3947c2…ae52bf age=2y8mo5d   dirty=255.30MiB
INFO [05-18|10:36:26.986] Deep froze chain segment                 blocks=336   elapsed=425.113ms number=4220819 hash=fa8035…78ba1e
INFO [05-18|10:36:29.446] Imported new chain segment               blocks=39    txs=4375  mgas=217.497  elapsed=8.308s    mgasps=26.177  number=4310830 hash=339958…e01746 age=2y8mo5d   dirty=255.21MiB
INFO [05-18|10:36:37.465] Imported new chain segment               blocks=42    txs=5158  mgas=242.702  elapsed=8.018s    mgasps=30.266  number=4310872 hash=96ea13…8c09ea age=2y8mo5d   dirty=255.35MiB
INFO [05-18|10:36:45.611] Imported new chain segment               blocks=48    txs=4960  mgas=263.585  elapsed=8.146s    mgasps=32.356  number=4310920 hash=36bd52…337bab age=2y8mo5d   dirty=255.52MiB
INFO [05-18|10:36:53.973] Imported new chain segment               blocks=48    txs=5326  mgas=275.895  elapsed=8.362s    mgasps=32.993  number=4310968 hash=054cd0…9498a9 age=2y8mo5d   dirty=255.32MiB
INFO [05-18|10:37:02.201] Imported new chain segment               blocks=42    txs=5704  mgas=249.947  elapsed=8.227s    mgasps=30.378  number=4311010 hash=6b9e4b…991818 age=2y8mo5d   dirty=255.14MiB

I use the default blockFrom to synchronize data from a block with a height equal to 0, but because the synchronization to the latest block height is too slow, I want to start synchronization from a higher block height, where should I modify my configuration File, what options should be modified, I have read the configuration file, and found no related configuration options. Who can help me, thank you very much!

**Comment by martinboehm** [comment]
You have to check the geth documentation if and how is this possible. 
In general, I would not recommend this approach as you will loose part of the transaction history.

We do not have any experience with running Blockbook in this mode.
