### ISSUE TITLE
Ethereum syncmod light problem

### ISSUE THREAD

**Issue by dvlpr-n** [trezor/blockbook#435]
I want to run an Ethereum backend in light-mode so in `backend-ethereum.service` I changed `geth -syncmod full` to `geth -syncmod light`. After restarting `blockbook` and `backend` services, The `blockbook` service is not updated with new blocks. Is it work in just full syncmod or there is another problem? Thanks in advance.

**Comment by martinboehm** [comment]
We run `geth -syncmod full` as have had problems running it in `-syncmod light`. However I must say that we did not investigate the issue much, we just waited a bit more for the blockchain to synchronize.
If you figure something out, please let us know.

**Comment by dvlpr-n** [comment]
Thanks @martinboehm. I could not run it in the `light` mode. There is another mode called `fast`. I will try it ASAP and will notice the result here.

**Comment by dvlpr-n** [comment]
I checked it in `fast` mode and it didn't work again. It seems that the blockbook works only in `full` mode.
