### ISSUE TITLE
ZEC Testnet redirected on Ethereum + Questions

### ISSUE THREAD

**Issue by Droppix** [trezor/blockbook#439]
Hi,

Few questions :

1/ I noticed that tzec1.trezor.io/api and tzec2.trezor/api are redirected on a Etheurem mainnet blockchain and not Zec testnet. It's normal?

2/ Do you have an api for LTC/BCH/DASH/ZEC Testnet ?

3/ Estimate Fees: I try your api https://ltc1.trezor.io/api/v2/estimatefee/3, how do you estimate this result? {"result":"0.00001"} (Average day, ...)?

Thanks

**Comment by martinboehm** [comment]
1) thank you, we disabled the incorrectly registered server
2) we do not run any publicly accessible testnet apart from BTC Testnet and ETH Testnet Ropsten
3) the value returned from estimate fee is computed by the backend, as a result of the backend RPC call estimatefee or estimatesmartfee

**Comment by Droppix** [comment]
ok, thanks
