### ISSUE TITLE
ZCash issue fees?

### ISSUE THREAD

**Issue by Droppix** [trezor/blockbook#440]
Hi,

I compare the fees for one transaction (on different apis or explorer): 62c15aec8bc923c247933278b66d67c6c7c764874ef62992be885

```
https://zec1.trezor.io/api/v2/tx/62c15aec8bc923c247933278b66d67c6c7c764874ef62992be88567ce4829eaf
-> Fees = 480010000 sathosis : issue?

https://api.zcha.in/v2/mainnet/transactions/62c15aec8bc923c247933278b66d67c6c7c764874ef62992be88567ce4829eaf
-> "fee": 0.0001 -> 10000 sathois

https://blockchair.com/zcash/transaction/62c15aec8bc923c247933278b66d67c6c7c764874ef62992be88567ce4829eaf
-> Fees = 0.0001 -> 10000 sathois
```
Is this a mistake or did I not understand?

Thanks

**Comment by martinboehm** [comment]
Hi, Blockbook currently does not recognize the amounts transferred from or to shielded pool. I will check what could be done about it.

**Comment by Droppix** [comment]
Hi,

That would be good, because I need to calculate "a precise average" on the fees (e.g. every hour), and obviously with the shielded pool, it distorts my calculation.
Also, do you think it would be possible to add in the transaction structure "the size of the each transaction" (https://zec1.trezor.io/api/v2/block/xxxx -> txs)?

Thanks

**Comment by Droppix** [comment]
Hi,

I come back to my 2 questions:

1/ Do you think you can add something (structure tx) to distinguish that amount transferred from/to shield pool?
2/ Can you add the transaction size in the structure tx? (https://xxx.trezor.io/api/v2/block/xxxx -> txs)

Thanks

**Comment by martinboehm** [comment]
Hi,
1) yes, we will fix this, it is sort of a bug. The fix requires a change in the common Blockbook code, it will take some time to finish and test.
2) unfortunately, the data in the block request are fetched from db index, which does not contain transaction size. I do not see an easy and performant way (without changing the db index) to get the tx sizes.

**Comment by Droppix** [comment]
Hi,

1/ Great!
2/ Ok, I understand...

Otherwise, I added some small changes (addition of the Dogecoin testnet + Bitcoin Gold testnet, checked + tested), if you're interested ...

https://github.com/Droppix/blockbook/blob/master/configs/coins/dogecoin_testnet.json
https://github.com/Droppix/blockbook/blob/master/bchain/coins/dogecoin/dogecoinparser.go
https://github.com/Droppix/blockbook/blob/master/bchain/coins/blockchain.go
https://github.com/Droppix/blockbook/blob/master/configs/coins/bgold_testnet.json
