### ISSUE TITLE
"unknown" version, gitCommit and buildTime

### ISSUE THREAD

**Issue by g574** [trezor/blockbook#442]
Hi,
when I call the /api/v2/ endpoint, I get - among others - the version, gitCommit and buildTime fields.
It used to work fine under v0.3.2 but since v0.3.3 these fields are "unknown".
I built Blockbook like this:
```
export GOPATH=/go
cd /go/src/blockbook
dep ensure -vendor-only
BUILDTIME=$(date --iso-8601=seconds); \
    GITCOMMIT=$(git describe --always --dirty); \
    LDFLAGS="-X blockbook/common.version=${BLOCKBOOK_VERSION} -X blockbook/common.gitcommit=${GITCOMMIT} -X blockbook/common.buildtime=${BUILDTIME}"
    go build -ldflags="-s -w ${LDFLAGS}"
```
I suppose it is related to the Go modules but I don't know how to fix it.
I've tried adding `GO111MODULE=on go mod vendor` and a few minor changes but it didn't work.
Could you help me fix it?

**Comment by martinboehm** [comment]
There is a change related to the Go modules, Blockbook package is now `github.com/trezor/blockbook`. You have to have the LDFLAGS like this:

```
LDFLAGS := -X github.com/trezor/blockbook/common.version=$(VERSION) -X github.com/trezor/blockbook/common.gitcommit=$(GITCOMMIT) -X github.com/trezor/blockbook/common.buildtime=$(BUILDTIME)
```

**Comment by g574** [comment]
@martinboehm , Thanks a lot. It's displayed correctly now.
