### ISSUE TITLE
How to change Decimal from 8 to 7?

### ISSUE THREAD

**Issue by atomlab** [trezor/blockbook#444]
Hi. I'm working on [BCD](https://github.com/eveybcd/BitcoinDiamond) coin implementation. BCD use  decimals **7** instead of **8** like other btc like forks. 

How can I change it? 

I had tried change this with [this](https://github.com/Atomicwallet/blockbook/commit/33d5c96c933e2dab7deacbf52005f71c40ad36f8#diff-c12d0966fb23f66730f5a7751d128a11) commit.  Development [BCD](https://github.com/Atomicwallet/blockbook/tree/bcd) branch. I had changed `AmountDecimalPoint`. Do you think this would work? At now it's not working as I expect.

**Example 1**
Get balance. I expect to see `"balance":"11132430"`  instead of  `"balance":"111324300"`
```
curl https://bcd-blockbook-dev.atomicnodes.com/api/v2/address/1BG4k5kqr39ckwb5iYDrqmwUUo2ZRcWmCh
```
>{"page":1,"totalPages":1,"itemsOnPage":1000,"address":"1BG4k5kqr39ckwb5iYDrqmwUUo2ZRcWmCh","balance":"111324300","totalReceived":"8246816880","totalSent":"8135492580","unconfirmedBalance":"0","unconfirmedTxs":0,"txs":7,"txids":["d1c8208a4e4eb33179975cdf4d2e5125b91159f4de5c69acd7f412b770f53e18","8050d476a6d304edd751753f3a7980ffbf0ac788fc404aafcc5ad1e768ca0f68","2a01d2a3b0ac6ca114d2f58e1cec1338f129a72d3aa63a220dfbd1440e69f5d6","9d9a1e7302cd0bbdd6065efd10e4362ed20309bda27c8bdb52d69dce142a9737","f6682c99fa9a400373c08055f008d8d4dba326dfeb6ef6aefda254bad7a42889","a84c3a956ba7f44b08886b0c3ee05fa50888f98d9e5a0d74d9369128ec19efd3","d79476271cbd980521c1545f0cfa1779004feae5cb74eed5ea1f59c7cf6963ff"]}

**Example 2**

I expect to see `"decimals":7`
```
curl https://bcd-blockbook-dev.atomicnodes.com/api/
```

>{"blockbook":{"coin":"Bdiamond","host":"bcd-02","version":"devel","gitCommit":"33d5c96-dirty","buildTime":"2020-06-09T15:43:00+00:00","syncMode":true,"initialSync":false,"inSync":true,"bestHeight":623960,"lastBlockTime":"2020-06-21T11:34:06.402935116Z","inSyncMempool":true,"lastMempoolTime":"2020-06-21T11:39:06.482648849Z","mempoolSize":0,"decimals":8,"dbSize":135073847729,"about":"Blockbook - blockchain indexer for Trezor wallet https://trezor.io/. Do not use for any other purpose."},"backend":{"chain":"main","blocks":623960,"headers":623960,"bestBlockHash":"376b3d8b1bc0366b1effb9d1fd8cbca3b12572c64bd419b0d02225997f7c1981","difficulty":"12265261.65523242","sizeOnDisk":164070925437,"version":"1030000","subversion":"/Bitcoin Diamond:1.3.0/","protocolVersion":"70015"}}

**Comment by martinboehm** [comment]
Hi, try to create the parser the following way:
```
func NewBdiamondParser(params *chaincfg.Params, c *btc.Configuration) *BdiamondParser {
	p := &BdiamondParser{BitcoinParser: btc.NewBitcoinParser(params, c)}
	p.AmountDecimalPoint = 7
	return p
}
```

**Comment by atomlab** [comment]
Thank you for response. I have build the blockbook with this fix. 


```
curl https://bcd-blockbook-dev.atomicnodes.com/api/
```
`"decimals":7`
>{"blockbook":{"coin":"Bdiamond","host":"bcd-02","version":"devel","gitCommit":"ddfe603-dirty","buildTime":"2020-06-26T14:51:33+00:00","syncMode":true,"initialSync":false,"inSync":true,"bestHeight":625074,"lastBlockTime":"2020-06-29T15:27:34.575113398Z","inSyncMempool":true,"lastMempoolTime":"2020-06-29T15:37:29.665808563Z","mempoolSize":1,"decimals":7,"dbSize":126737179336,"about":"Blockbook - blockchain indexer for Trezor wallet https://trezor.io/. Do not use for any other purpose."},"backend":{"chain":"main","blocks":625074,"headers":625074,"bestBlockHash":"95ddfd6e28aa396a5572236bc7fc4c09c96ba4925b6b4cd98c9e5e8ae6fc5264","difficulty":"7528311.586327783","sizeOnDisk":164072556681,"version":"1030000","subversion":"/Bitcoin Diamond:1.3.0/","protocolVersion":"70015"}}

But I don't understand why utxo contain `"value":"111345600"`.

```
 curl https://bcd-blockbook-dev.atomicnodes.com/api/v2/utxo/18FJiWfxD98wbg8HssqYdqNaU3v3uTdTyz
```
>[{"txid":"cb1fa614b87a52d3e28ce1c3a689e4385ccdd95e6119084e7381da795f8ce471","vout":1,"value":"111345600","height":619364,"confirmations":5713},{"txid":"b5ea3cccfb033ac0b191eca36059553b3a6b9f6ea4e700ab357f152738281081","vout":0,"value":"349900","height":604217,"confirmations":20860}]

I expected
```
11132430/10 000 000 = 1.113243 (decimals 7)
```
But now
```
111324300/100 000 00 = 11.13243
```

**Comment by Atomicwallets** [comment]
@martinboehm Can you help please?

**Comment by martinboehm** [comment]
Hi, I was a bit baffled by the problem you report. But now I realized, did you redo the initial sync of the database after the change in the parser?

**Comment by atomlab** [comment]
> Hi, I was a bit baffled by the problem you report. But now I realized, did you redo the initial sync of the database after the change in the parser?

You are right, the new blocks parsed correctly. I have run initial sync again and waiting sync finish to check it.

**Comment by martinboehm** [comment]
@atomlab Hi, is the problem resolved?

**Comment by atomlab** [comment]
@martinboehm Yes, problem resolved after sync of the database. Thank you!
