### ISSUE TITLE
Address API ERROR: Some Ethereum address data are missing

### ISSUE THREAD

**Issue by Muggle-Du** [trezor/blockbook#452]
After geth and blockbook are started, I try to call the address api with this address: 0x0681d8Db095565FE8A346fA0277bFfdE9C0eDBBF
then I got an error like this:
Error
Internal server error: EthereumTypeGetErc20ContractInfo ad:ef68e7c694f40c8202821edf525de3782458639f: execution reverted, data <nil>
and then I try to query with contract address "ad:ef68e7c694f40c8202821edf525de3782458639f", and this error occoured:
Error
No matching records found for 'ef68e7c694f40c8202821edf525de3782458639f'
It seems there is no data about this contact address in the rocksdb database, so how could I fix the database or how could I fix this problem. Could I check the database and resync the missing data? @martinboehm

**Comment by martinboehm** [comment]
Hi, I do not see the described behaviour in our server, see:
https://eth1.trezor.io/address/0x0681d8Db095565FE8A346fA0277bFfdE9C0eDBBF
https://eth1.trezor.io/address/0xEF68e7C694F40c8202821eDF525dE3782458639f
Is your Blockbook properly synchronized?

**Comment by Muggle-Du** [comment]
yean, both address seems alright in https://eth1.trezor.io, while some errors occurred in my local deplyment.
Can you give some specific information based on the error massage ?
I've put blockbook in a docker container and the status seems good
<img width="1199" alt="截屏2020-07-05 下午6 21 57" src="https://user-images.githubusercontent.com/25078682/86530643-db5bb080-beec-11ea-951a-5ba52257e68e.png">
How can I check the status of the database?
Thanks for your fast response!

**Comment by Muggle-Du** [comment]
Or has anybody met with the same question as me? If I delete the database and resync , can I fix this problem?

**Comment by Muggle-Du** [comment]
Since EthereumTypeGetErc20ContractInfo was a bchain function , did this mean the worker failed to get address' txs from database and truned to get txs from ethereum rpc client?

**Comment by Muggle-Du** [comment]
and for this address "0xfdb16996831753d5331fF813c29a93c76834A0AD", I got:
Error
Internal server error: EthereumTypeGetErc20ContractInfo ad:b5a5f22694352c15b00323844ad545abb2b11028: invalid opcode: opcode 0xfe not defined, data <nil>
this is another error different from the previous one

**Comment by Muggle-Du** [comment]
Both error seems errors returned from geth client, so does this mean something is wrong with rpc or geth client?

**Comment by martinboehm** [comment]
I see that you are using an unstable version of geth.
We are using Geth/v1.9.13-stable-cbc4ac26/linux-amd64/go1.14.2.
It is quite possible that there is some problemn i the version you are using.

**Comment by Muggle-Du** [comment]
thanks. I'll try the v1.9.13 geth client

**Comment by Muggle-Du** [comment]
Geth/v1.9.13-stable-cbc4ac26/linux-amd64/go1.14.2 works, though I'm using the corresponding docker image.
Thanks!
