### ISSUE TITLE
"could not find project Gopkg.toml, use dep init to initiate a manifest" error, after running "make all-<coin>"

### ISSUE THREAD

**Issue by olegmitrakhovich** [trezor/blockbook#454]
I recently attempted to add support for another coin called BYTZ. When I did "make all-bytz", after 10 minutes of building I am getting this error:

make[1]: Leaving directory '/opt/rocksdb'
Removing intermediate container 7ff1ab51e6c0
 ---> d8921692c2b4
Step 17/23 : RUN strip /opt/rocksdb/ldb /opt/rocksdb/sst_dump &&     cp /opt/rocksdb/ldb /opt/rocksdb/sst_dump /build
 ---> Running in fedab1c6d1d1
Removing intermediate container fedab1c6d1d1
 ---> 6534a38a1260
Step 18/23 : RUN go get github.com/golang/dep/cmd/dep
 ---> Running in 5c2b9f195feb
Removing intermediate container 5c2b9f195feb
 ---> 664592d5da5f
Step 19/23 : RUN go get github.com/gobuffalo/packr/...
 ---> Running in ab4683853311
Removing intermediate container ab4683853311
 ---> 280b34d9bfcb
Step 20/23 : RUN     cleanup() { rm -rf $GOPATH/src/blockbook; } &&     trap cleanup EXIT &&     cd $GOPATH/src &&     git clone https://github.com/trezor/blockbook.git &&     cd blockbook &&     dep ensure -vendor-only &&     cp -r vendor /build/vendor
 ---> Running in 7ee87af6b019
Cloning into 'blockbook'...
could not find project Gopkg.toml, use dep init to initiate a manifest
The command '/bin/sh -c cleanup() { rm -rf $GOPATH/src/blockbook; } &&     trap cleanup EXIT &&     cd $GOPATH/src &&     git clone https://github.com/trezor/blockbook.git &&     cd blockbook &&     dep ensure -vendor-only &&     cp -r vendor /build/vendor' returned a non-zero code: 1
make[1]: *** [Makefile:46: .bin-image] Error 1
make[1]: Leaving directory '/home/omitrakhovich/BYTZ-blockbook'
make: *** [Makefile:43: build-images] Error 2

Really strange, I made blockbook work with other coins before and this is a new error.

**Comment by martinboehm** [comment]
Assuming you started with reasonably current version from master, it looks like you docker is using some cached images. Did you try `make clean-all`?
It seems to use old modules tool `dep` but the Blockbook project switched to go modules recently.

**Comment by olegmitrakhovich** [comment]
thanks for the answer, I was using an older version of blockbook which I forked in december of 2019 ... I did get past the error by adding:
# download pre-loaded depencencies
RUN \
    cleanup() { rm -rf $GOPATH/src/github.com/trezor ; } && \
    trap cleanup EXIT && \
    mkdir -p $GOPATH/src/github.com/trezor && \
    cd $GOPATH/src/github.com/trezor && \
    git clone https://github.com/trezor/blockbook.git && \
    cd blockbook && \
    env GO111MODULE=on go mod vendor && \
    cp -r vendor /build/vendor

but now I have bigger issues, I think need to fork again with all the recent changes and try again with go modules. Thank you for the answer, it put me in the right direction. @martinboehm
