### ISSUE TITLE
replace packr with go:embed (after go 1.15 is out)

### ISSUE THREAD

**Issue by prusnak** [trezor/blockbook#459]
Going through the dependencies I noticed that the author of packr recommends people to switch to pkger.

See the notice at the top of the https://github.com/gobuffalo/packr/blob/master/README.md file

pkger project: https://github.com/markbates/pkger

This is super low-priority, but might simplify some things. If it doesn't simplify anything, I guess it's not worth the hassle.

**Comment by prusnak** [comment]
It seems that Go 1.15 will introduce a native `go:embed` way how to bundle static files into the binaries: more info https://go.googlesource.com/proposal/+/master/design/draft-embed.md

If this really ships we might want to switch to this standard method of bundling files.

**Comment by martinboehm** [comment]
Thanks for info. I think we should wait for go 1.15.

Anyway, we are using packer only for non essential functionality of embedding TOS and about texts into Blockbook to simplify customisability.

**Comment by martinboehm** [comment]
Done in v0.3.6
