### ISSUE TITLE
dpkg: dependency problems prevent configuration of blockbook-digibyte

### ISSUE THREAD

**Issue by divyamsolanki9** [trezor/blockbook#461]
`dpkg -i blockbook-digibyte_0.3.4_amd64.deb`
```
(Reading database ... 52467 files and directories currently installed.)
Preparing to unpack blockbook-digibyte_0.3.4_amd64.deb ...
Unpacking blockbook-digibyte (0.3.4) over (0.3.4) ...
dpkg: dependency problems prevent configuration of blockbook-digibyte:
 blockbook-digibyte depends on libgflags2v5; however:
  Package libgflags2v5 is not installed.
 blockbook-digibyte depends on libsnappy1v5; however:
  Package libsnappy1v5 is not installed.
 blockbook-digibyte depends on libzmq5 (>= 4.2.0); however:
  Package libzmq5 is not installed.
 blockbook-digibyte depends on psmisc; however:
  Package psmisc is not installed.

dpkg: error processing package blockbook-digibyte (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 blockbook-digibyte
```

**Comment by olegmitrakhovich** [comment]
does `apt install blockbook-digibyte_0.3.4_amd64.deb` work ? @divyamsolanki9

**Comment by divyamsolanki9** [comment]
@olegmitrakhovich 
`cd blockbook/build`
`apt install blockbook-digibyte_0.3.4_amd64.deb`

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package blockbook-digibyte_0.3.4_amd64.deb
E: Couldn't find any package by glob 'blockbook-digibyte_0.3.4_amd64.deb'
E: Couldn't find any package by regex 'blockbook-digibyte_0.3.4_amd64.deb'
```

**Comment by olegmitrakhovich** [comment]
sorry try `sudo apt install ./blockbook-digibyte_0.3.4_amd64.deb` @divyamsolanki9

**Comment by olegmitrakhovich** [comment]
I hope you are following this ... https://wiki.trezor.io/User_manual:Running_a_local_instance_of_Trezor_Wallet_backend_(Blockbook)

**Comment by divyamsolanki9** [comment]
@olegmitrakhovich Yes. I am following same.
OS - Debian

**Comment by olegmitrakhovich** [comment]
did `sudo apt install ./blockbook-digibyte_0.3.4_amd64.deb` work? @divyamsolanki9

**Comment by divyamsolanki9** [comment]
No, didn't worked. Here's the log
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'blockbook-digibyte' instead of './blockbook-digibyte_0.3.4_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 blockbook-digibyte : Depends: libgflags2v5 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by olegmitrakhovich** [comment]
are you using Debian 9? ... this sounds a lot like this issue here https://github.com/trezor/blockbook/issues/163

**Comment by divyamsolanki9** [comment]
@olegmitrakhovich Yes. Debian 9. Which OS do you recommend to use ?

**Comment by divyamsolanki9** [comment]
@olegmitrakhovich @martinboehm 
I am using Debian 10

**Comment by olegmitrakhovich** [comment]
you need Debian 9 to install blockbook ... however, as a quick fix `nano blockbook/build/docker/bin/Dockerfile' and change line 3 to `FROM debian:10` ... make and try installing again.

**Comment by divyamsolanki9** [comment]
Didn't worked. I'll redo to Debian 9 and check

**Comment by divyamsolanki9** [comment]
@olegmitrakhovich Worked with Debian 9.
What's the procedure to access out of localhost on WAN IP

**Comment by olegmitrakhovich** [comment]
sorry not sure what you mean... can you explain more? @divyamsolanki9

**Comment by divyamsolanki9** [comment]
@olegmitrakhovich How can I access explorer data apart from Localhost ?

**Comment by divyamsolanki9** [comment]
@olegmitrakhovich  How to access explorer data apart from Localhost ?

**Comment by olegmitrakhovich** [comment]
so if you deployed on some sort of a VM with an IP address, just type https://<ip address>: 9142 in your browser ... all the ports are in your configs folder for digibyte: 
   "ports": {
    "backend_rpc": 8042,
    "backend_message_queue": 38342,
    "blockbook_internal": 9042,
    "blockbook_public": 9142
