### ISSUE TITLE
How to rebuild index?

### ISSUE THREAD

**Issue by darkhorse-spb** [trezor/blockbook#464]
Good day,

I'm experiencing the following problem with ETC for the second time:

```
I0806 03:34:29.393523       6 sync.go:108] resync: local is forked at height 10939869, local hash 0xd8d26e78e85bf8f6ef803c0148bc4e42b5717c0cfeb347d8f64de52e0795f183, remote hash0xf62650a53f76467a77eff540d8f8682ec1beeb5558b7ea5c66ec6a270914793a   
I0806 03:34:34.071590       6 sync.go:405] sync: disconnecting blocks 10935623-10939869  
E0806 03:34:34.072478       6 blockbook.go:536] syncIndexLoop /go/src/blockbook/db/rocksdb_ethereumtype.go:440: Cannot disconnect blocks with height 10935623 and lower. It is necessary to rebuild index.
```

Could you please advice how it should be done?

**Comment by martinboehm** [comment]
You have to stop the service, delete current database files and start again. If you have some older backup of the database, restore it to speed up the sync. 
Also, we increased the max size of reorg to 10000 blocks https://github.com/trezor/blockbook/commit/ab285c6b05b18e599861b7ac6f34ee146a67edee, if you build a new version of Blockbook. But this will help you in the next big reorg, now you have to resync the database.

**Comment by darkhorse-spb** [comment]
Thank you, Martin!

**Comment by aman-rac** [comment]
@martinboehm adding ` "block_addresses_to_keep": 100000` to blockchaincfg.json didn't work for the ethereum_ropsten resync because of block#10679538, this error persisted, is this expected?
