### ISSUE TITLE
Unsubscribing Address Transactions On Server Emit

### ISSUE THREAD

**Issue by passabilities** [trezor/blockbook#472]
I'm subscribing to a list of addresses using the Websocket API and am successfully getting an event for a new transaction of one of the addresses in the list. 

The problem is once I receive 1 event, it then stops watching the addresses. I never receive a 2nd event from the server. As a workaround, once I receive the first event, I immediately resubscribe using the same list of addresses I have cached locally.

This is happening for the socket URL: `wss://btc1.trezor.io/websocket`

**Comment by martinboehm** [comment]
Hi. We do not observe the problem you describe, the notifications of multiple transactions are working.
Could you check that the websocket connection was not closed? Our servers will close it after about 1 minute of inactivity.
