### ISSUE TITLE
Get balance for specific bitcoin address API call

### ISSUE THREAD

**Issue by Sumit570** [trezor/blockbook#473]
I am using Blockbook Docker to build docker container for Blockbook, the Trezor wallet backend. I am able to start docker container successfully and made connection with bitcoin daemon running separately. How can I call rest API to get balance for specific bitcoin address now ?

Steps to run:

* bitcoind -regtest -rpcuser=USER -rpcpassword=PASS -fallbackfee=0.00072 -rpcbind=HOST_IP -rpcallowip=0.0.0.0/0 -rpcport=HOST_PORT
* docker pull gustavonalle/blockbook
* docker run --name blockbook -it -p 9030:9030 -p 9130:9130 -e RPC_USER=USER -e RPC_PASS=PASS -e RPC_HOST=HOST_IP -e  RPC_PORT=HOST_PORT gustavonalle/blockbook

now I can see dashboard on https://localhost:9130 but how can I call rest API from postman to get balance for specific bitcoin address. 

I tried https://localhost:9130/blockbook/balance/{addr} but not working. Is there anyway so I can use `http` instead of `https`?

**Comment by martinboehm** [comment]
Hi, the API documentation for address balance is [here](https://github.com/trezor/blockbook/blob/master/docs/api.md#get-address).

**Comment by Sumit570** [comment]
Hi @martinboehm,

I am able to get balance for specific address using `https` but I want to do same using `http`, how can I do that?

**Comment by martinboehm** [comment]
If you do not specify the parameter `-certfile`, Blockbook will listen on `http`.

**Comment by Sumit570** [comment]
I am using [docker image](https://hub.docker.com/r/gustavonalle/blockbook) to build Blockbook, the Trezor wallet backend. By default, it is running on `https`.

Steps to run:

* bitcoind -regtest -rpcuser=USER -rpcpassword=PASS -fallbackfee=0.00072 -rpcbind=HOST_IP -rpcallowip=0.0.0.0/0 - 
  rpcport=HOST_PORT

* docker pull gustavonalle/blockbook
* docker run --name blockbook -it -p 9030:9030 -p 9130:9130 -e RPC_USER=USER -e RPC_PASS=PASS -e 
  RPC_HOST=HOST_IP -e RPC_PORT=HOST_PORT gustavonalle/blockbook

I can see one file `launch.sh` inside docker container which contains `-certfile` option. Can you tell me how can I remove 
`-cerfile` option from script while running docker container?

**Comment by Sumit570** [comment]
> You will have to change content of the image.

Thanks, will do.
