### ISSUE TITLE
Suggestion / PR

### ISSUE THREAD

**Issue by Droppix** [trezor/blockbook#479]
Hello,

When invoking the api "xxx.trezor.io/api/v2/block/xxxx", 
```
{
  "page": 1,
  "totalPages": 1,
  "itemsOnPage": 1000,
  "height": 1827173,
  "confirmations": 101,
  "txCount": 10,
  ...
  "txs": [
    {
      "txid": "70f36142e81fcbf8a9d8b01fd950c342adf582a6af3309e2721c682e91b51a1c",
      "vin": [
        {
          "n": 0,
          "isAddress": false,
          "value": "0"
        }
      ],
      "vout": [
        {
          "value": "20238760",
          "n": 0,
          "addresses": [
            "2MsM67NLa71fHvTUBqNENW15P68nHB2vVXb"
          ],
          "isAddress": true
        },
        {
          "value": "0",
          "n": 1,
          "addresses": [
            "OP_RETURN aa21a9ede8aba44f0f2268f736c33e41d84e325c082cc3c31d4f20682234ee1394bbdaf2"
          ],
          "isAddress": false
        }
      ],
      "blockHash": "000000000000023e45d24d680bcf3094e9e42eed36fa0380cfb5b4bf701f9e44",
      "blockHeight": 1827173,
      "confirmations": 101,
      "blockTime": 1598533843,
      "value": "20238760",
      "valueIn": "0",
      "fees": "0"
    },
    ...
  ]
}
```
in my opinion, an important information is missing which is the size of each transaction (cf: txs[n].size), which can be obtained by calling the api "xxx.trezor.io/api/v2/tx/xxxx", which provides the transaction in "hex" : 
```
size = (tx.length / 2).
````
The problem is that each block can contain thousands of transactions, and it would be a shame to make thousands of calls to "xxx.trezor.io/api/v2/tx/xxxx" just to get the transaction size.

Therefore, do you think it would be possible to add 'the size of a each transaction' in the "block" api?

Thanks

**Comment by martinboehm** [comment]
Hi. Unfortunately the data for the block request are obtained from Blockbook's data index (for performance reasons), which contains neither the size of the transaction nor the transaction hex. There is no easy way to get the tx size at this moment.
