### ISSUE TITLE
ETH EthereumTypeGetErc20ContractInfo : invalid jump destination

### ISSUE THREAD

**Issue by matyushkins** [trezor/blockbook#481]
Hi. 
Geth/v1.9.20-stable-979fc968/linux-amd64/go1.15
Address 0x52bc44d5378309EE2abF1539BF71dE1b7d7bE3b5
[https://eth1.trezor.io/address/0x52bc44d5378309EE2abF1539BF71dE1b7d7bE3b5](https://eth1.trezor.io/address/0x52bc44d5378309EE2abF1539BF71dE1b7d7bE3b5)
`Error
Internal server error
`
```
I0901 08:35:40.506355       6 worker.go:950] GetAddress 0x52bc44d5378309EE2abF1539BF71dE1b7d7bE3b5 finished in 1.107401ms
E0901 08:35:40.583069       6 public.go:378] github.com/trezor/blockbook/server.(*PublicServer).explorerAddress-fm error: EthereumTypeGetErc20ContractInfo ad:fb6ee7ca12e4008001eaef2ae4a027350b36ed60: invalid jump destination
```

Not error:
Geth/v1.9.13-stable-cbc4ac26/linux-amd64/go1.14.2
[https://ethbook.guarda.co/address/0x52bc44d5378309EE2abF1539BF71dE1b7d7bE3b5](https://ethbook.guarda.co/address/0x52bc44d5378309EE2abF1539BF71dE1b7d7bE3b5)

**Comment by martinboehm** [comment]
Hi, there is a fix in the master now.
