### ISSUE TITLE
PR /api/v2/xpub

### ISSUE THREAD

**Issue by Droppix** [trezor/blockbook#484]
Hi Martin,

I looked at the method /api/v2/xpub?tokens=[nonzero/used/derived], in order to avoid several http calls, is it to add an option, of "free" type, which could provide one or more free addresses (with a 0 balance), this would limit the use of 'derived', especially if the account has > 1000 transactions.

Regards

**Comment by martinboehm** [comment]
Hi, I think, the parameters `details=tokens&tokens=derived` is what you are looking for. It is not returning any transactions and you can easily find a free address if it has 0 transfers.

**Comment by Droppix** [comment]
The problem with this option ("details=tokens&tokens=derived), what it does not guarantee to return (in a single call), a free address, which implies making a few calls (per page), in order to scan a free address. I wrong?

**Comment by martinboehm** [comment]
It does guarantee a return of free addresses, it generates addresses up to the gap of 20 (by default) free addresses and returns them all.

**Comment by Droppix** [comment]
Great! 
Thanks
