### ISSUE TITLE
min relay fee not met on testnet is incorrect

### ISSUE THREAD

**Issue by 3tbraden** [trezor/blockbook#485]
## Expected Behavior
I should be able to send transaction on the testnet with appropriate fee on the network.

## Current Behavior
I was querying fee rate with the endpoint: https://tbtc1.trezor.io/api/v1/estimatefee/1, where it was about 1sat/byte.

But when I tried to broadcast a transaction with https://tbtc1.trezor.io/api/v2/sendtx/<tx_hex>, it returned error: {"error":"-26: min relay fee not met, 130 \u003c 141"}

**Comment by martinboehm** [comment]
The fee estimate is calculated by the backend, there is nothing Blockbook can do about incorrect estimates. I would not expect too much from the testnet fee estimators anyways.
