### ISSUE TITLE
Parser bug in all coins except BTC/Eth

### ISSUE THREAD

**Issue by sidhujag** [trezor/blockbook#489]
https://github.com/trezor/blockbook/blob/master/bchain/coins/dash/dashparser.go#L61

There is a bug as you can see in all the coins outside of eth/btc and maybe one more that init'ed bchain.BaseParser properly like so (https://github.com/trezor/blockbook/blob/master/bchain/coins/btc/bitcoinparser.go#L39)

Here we see that it does not init with 8 for causing AmountDecimalPoint to be 0 and this function not working properly: https://github.com/trezor/blockbook/blob/master/bchain/baseparser.go#L49

I fixed this for Syscoin: https://github.com/syscoin/blockbook/blob/dev-4.2.0/bchain/coins/sys/syscoinparser.go#L68

**Comment by martinboehm** [comment]
Could you please explain a bit more the issue as I do not see any problem with parsing/formatting of the amounts in non btc/eth coins, see for example amounts in https://ltc1.trezor.io/.

**Comment by sidhujag** [comment]
@martinboehm I was noticing that transaction values were not in satoshi amounts because decimals was 0 instead of 8

https://github.com/trezor/blockbook/blob/master/bchain/baseparser.go#L107

voutSats would return values with decimal 0 instead of 8 and my code was breaking specific to assets, perhaps not a big issue with ltc or other coins but after it stored to cache it wasn't affecting it, only the first time the transaction was queried (in mempool I believe). I tried a few mempool txs on ltc and seems ok but maybe in one of your unit or integration tests you can output the value of decimals to see its 0 and see that voutSats is incorrect in the API.

**Comment by martinboehm** [comment]
I do not see the problem. Please document using some running instance, not in the source code. Closing for now.
