### ISSUE TITLE
Should "terms" in footer lead to wallet.trezor.io terms?

### ISSUE THREAD

**Issue by karel-3d** [trezor/blockbook#49]
"Terms" in explorer footer lead to wallet.trezor.io terms

I am not sure if that is intended or not

**Comment by martinboehm** [comment]
It is intended, however I don't know if correct. From my point of view is explorer a part of the wallet, with the same conditions. Could @prusnak @slush0 have input to this issue, please?

**Comment by prusnak** [comment]
I am OK with this
