### ISSUE TITLE
ETH Ropsten: websocket: read limit exceeded. Retrying...

### ISSUE THREAD

**Issue by matyushkins** [trezor/blockbook#490]
HI.
**Eth Ropsten 
Geth/v1.9.20-stable-979fc968/linux-amd64/go1.15**
_Blockbook Sync from 0_

Falls more than once on this error:

`E0910 06:52:15.205891       6 sync.go:302] getBlockWorker 3 connect block error hash 0xd092253c94e5f24426fff2c9a203ec921b2df0d188d0f7ffb654be0dbec15ddd, height 599275: websocket: read limit exceeded. Retrying...
E0910 06:52:15.205887       6 sync.go:302] getBlockWorker 2 connect block error hash 0xc02b5459997699df8b7a2bc45db78d784b1938b360ac3bc9f92764ee290e4ea5, height 599281: websocket: read limit exceeded. Retrying...
`

**Comment by martinboehm** [comment]
Hi. We have not seen this behavior. Does it recover from it or do you have to restart the server?

**Comment by matyushkins** [comment]
Hey. On our testnet, this has been observed more than once when synchronizing from scratch. Those. the node is synchronized from scratch and the blockbook is also synchronized from scratch. Restart did not help. deleting the data didn't help either.

**Comment by aman-rac** [comment]
@martinboehm , any updates? I am facing the same issue.

**Comment by csiocompany** [comment]
@matyushkins @martinboehm @aman-rac 

Version from 1/09/2020 woks fine. Something has changed...

**Comment by aman-rac** [comment]
@csiocompany , you built using the master after this [commit](https://github.com/trezor/blockbook/commit/bea6b6230fdadc077c6d5d3f0926f7c341aafd07)?

**Comment by csiocompany** [comment]
@aman-rac I do not know exactly. I only see the package date I was build is 1 september.

**Comment by martinboehm** [comment]
Do I understand it correctly that the September 1st version built from master works fine and later builds from master do not work? 

The only significant change since September 1st is this https://github.com/trezor/blockbook/commit/a1993173ab6dcb34f7911f23f6d85276783be31a commit, which bumps go-ethereum dependecy to `v1.9.20` (from `v1.8.20`). Could you check the behaviouor either rolling back the dependency to `v1.8.20` or more preferably upgrading to the latest go-ethereum, currently `v1.9.23` and then let us know of the result?

**Comment by matyushkins** [comment]
It work in last master on 26.12.2020

**Comment by aman-rac** [comment]
@martinboehm , same issue on ropsten `height 599275: websocket: read limit exceeded`.

Blockbook - 0.3.4 (Built from this [commit](https://github.com/trezor/blockbook/commit/d8640f4e2f50046fad4b3cf5bb1291de823f2bdc))
Geth - 1.10.1

**Comment by martinboehm** [comment]
Fixed by 0bf1d17edf0f4e99528f03b7327e747949f44bc7

**Comment by 7-of-9** [comment]
@martinboehm Same issue, using Geth/v1.10.3-stable-991384a7/linux-amd64/go1.16.3 and BB frontend 0.3.4 / cf66ce9 / 2021-05-17T06:27:32+00:00...

E0527 04:40:57.611810   21562 sync.go:335] getBlockWorker 2 connect block error hash 0xc02b5459997699df8b7a2bc45db78d784b1938b360ac3bc9f92764ee290e4ea5, height 599281: websocket: read limit exceeded. Retrying...
E0527 04:40:58.177114   21562 sync.go:335] getBlockWorker 1 connect block error hash 0xd092253c94e5f24426fff2c9a203ec921b2df0d188d0f7ffb654be0dbec15ddd, height 599275: websocket: read limit exceeded. Retrying...
E0527 04:40:58.177127   21562 sync.go:335] getBlockWorker 2 connect block error hash 0xc02b5459997699df8b7a2bc45db78d784b1938b360ac3bc9f92764ee290e4ea5, height 599281: websocket: read limit exceeded. Retrying...

**Comment by martinboehm** [comment]
@7-of-9 Hi, the commit cf66ce91126ad50e7eb0a439d1cc5b62f8304ce2 is not in our repository. Please make sure that the version of Blockbook you run includes the commit 0bf1d17edf0f4e99528f03b7327e747949f44bc7.

**Comment by 7-of-9** [comment]
Thanks @martin-key sry yes, `cf66ce9` is a commit on my fork. It bumps geth to 1.10.3 (from 1.10.2 in your commit `0bf1d17`).
I'd assumed that 1.10.3 would be fine, as the geth fix came in the previous verison. 
I'm going to try geth 1.10.2 per your commit, but fear it will fail on these same two blocks.

**Comment by martin-key** [comment]
I believe that comment was for @martinboehm

**Comment by 7-of-9** [comment]
Thanks @martinboehm - confirmed, I sync'd from your master branch ok. Must be something bad on my fork.
