### ISSUE TITLE
get latest xpub change and receiving indexes

### ISSUE THREAD

**Issue by sidhujag** [trezor/blockbook#493]
Is it possible to pass in options in xpub or utxo API call to get only the latest xpub change and receiving indexes to support xpub based wallets without having to get all of that data everytime to manage latest indexes?  I currently assume blockbook as the source of truth as its wallet agnostic however it fetches all the xpub tokens and it can grow unbounded, perhaps an easier alternative would be just to return the last used ones for change and receiving.

Currently im using XPUB API with tokens=used&details=tokens options

**Comment by martinboehm** [comment]
At this moment we do not plan to implement this feature.
