### ISSUE TITLE
Bitcoin Cash implementations/compatibility

### ISSUE THREAD

**Issue by g574** [trezor/blockbook#498]
Hello,
It's more a question than a bug report: I have a machine set up with [Bitcoin Cash ABC](https://github.com/Bitcoin-ABC/bitcoin-abc/releases) and Blockbook. This way it works fine with the following config.json:
```
{
    "coin_name": "Bcash",
    "coin_shortcut": "BCH",
    "coin_label": "Bitcoin Cash",
    "rpc_url": "****",
    "rpc_user": "****",
    "rpc_pass": "****",
    "rpc_timeout": 25,
    "parse": true,
    "message_queue_binding": "****",
    "subversion": "",
    "address_format": "",
    "block_addresses_to_keep": 300
}
```
Now I need to test it with other implementations, like [Bitcoin Cash Node](https://bitcoincashnode.org/) or [BCHD](https://bchd.cash/). With both of these I got an error message from Blockbook. E.g. for BCHD it says:
```
E1003 15:29:52.260269       1 blockbook.go:371] rpc: unexpected end of JSON input Retrying...
E1003 15:29:53.260388       1 blockbook.go:371] rpc: unexpected end of JSON input Retrying...
E1003 15:29:54.260436       1 blockbook.go:371] rpc: unexpected end of JSON input Retrying...
```

Is Blockbook compatible with any other implementation than ABC? If so which one or how shall I change the config for it to work?

**Comment by martinboehm** [comment]
Hi, we have not implemented/tested Blockbook with any other node than Bitcoin Cash ABC. From your report it seems that the rpc protocol differs in other implementations. I would expect that the difference will not be big but still need to be addressed in the code.

You are welcome to investigate it and create a PR for it.

**Comment by quietnan** [comment]
This change is at fault for Bitcoin Cash Node: https://gitlab.com/bitcoin-cash-node/bitcoin-cash-node/-/commit/5eb88756f3a787a9e57464181df785b46d72a2b3

Renaming `blockhash` to `hash_or_height`. Quickfix renaming works for Bitcoin Cash Node, obviously breaks all other BTC-ish currencies.
So far for the 'investigate' part. PR might follow if I find the time, but I can't promise it.

**Comment by sickpig** [comment]
`hash_or_height` is the same param name chosen by Core when they decided to make `getblockstat` works both with block `height` and `hash`. 

We at BCHN and BCH Unlimited (in short BU) simply extended the application of the concept and used it also for `getblock` (BCHN and BU) and `getheader` (BU only). 

Another possible fix, on top of the ones mentioned by @quietnan, is to call the RPC w/o using named parameter. Dunno if it is possible thou.

Will have a look at blockbook codebase.

**Comment by ftrader** [comment]
@quietnan : Thanks for your investigation.

It looks like it might be possible to add a 'blockhash' alias in BCHN to restore compatibility with ABC there, but I would caution against relying only on ABC node as a reference as they don't seem to have the support of the majority of the BCH network for the coming upgrade. (hashpower, number of nodes, fork future prices)

We will add more information about upstream resolutions in BCHN here as it becomes available.

**Comment by cculianu** [comment]
@quietnan We have already created a fix and are reviewing it.  We anticipate this fix appearing in the next version of BCHN -- https://gitlab.com/bitcoin-cash-node/bitcoin-cash-node/-/merge_requests/810

**Comment by ftrader** [comment]
@quietnan @martinboehm @g574 

BCHN release v22.1.0 is out, and include a compatibility fix which restores the 'blockhash' argument name (as an alias).

So if it works with ABC, it should work with BCHN v22.1.0 too.

Looking forward to hearing if this solves the issue you were experiencing.

**Comment by martinboehm** [comment]
@quietnan If we wanted to test it, are the ABC and BCHN blockchain databases binary compatible (ie. it is enough to use BCHN binaries with formerly ABC database) or is it necessary to resync it from start?

**Comment by ftrader** [comment]
> are the ABC and BCHN blockchain databases binary compatible (ie. it is enough to use BCHN binaries with formerly ABC database) 

Yes, they are still compatible.

**Comment by cculianu** [comment]
100% the exact same format .. just swap the binaries to test and you can use the same CONFIG files and should work 100% @martinboehm

**Comment by g574** [comment]
@cculianu, @ftrader, @martinboehm, thank you for help. Bitcoin Cash Node seems to work with Blockbook now. I'll get back to you if I run into any issues.

**Comment by cculianu** [comment]
@g574 Much appreciated.  If you ever have bugs that you think are Bitcoin Cash Node's fault again, feel free to write in this thread, or contact us directly on our gitlab.com repo: https://gitlab.com/bitcoin-cash-node/bitcoin-cash-node <-- creating an issued here will work -- we respond quickly.

Our website also has a link to our slack -- we are always on slack!: https://bitcoincashnode.org/
