### ISSUE TITLE
Add API call for coin name

### ISSUE THREAD

**Issue by karel-3d** [trezor/blockbook#5]
Currently, we detect the chain by

* looking at 0 height
* if it is bitcoin, we have some hard-coded rules by reading "version" from some networkInfo call

However, since we don't plan to be compatible with Bitcore in the future and so don't plan to keep compatibility with third party insight servers, we can make this easier by explicitly returning the coin name in some simple API.

And the best thing would be `coin_name` from https://github.com/trezor/trezor-common/tree/master/defs/coins

**Comment by martinboehm** [comment]
We will return "coin_name" in the getInfo socket.io request. Our coin_name will match your coin_name.

**Comment by karel-3d** [comment]
:sun_with_face:

**Comment by martinboehm** [comment]
Implemented in commit 9c019620019472c78a3f68acd3e1a73699fca622
