### ISSUE TITLE
Can't find data on how to send a transaction using POST in blockbook API documentation.

### ISSUE THREAD

**Issue by sollerias** [trezor/blockbook#502]
Hi, guys!

I have a problem. Cannot find data about how to send a transaction, using Blockbook.

[Here](https://github.com/trezor/blockbook/blob/master/docs/api.md#send-transaction) is API documentation. I want to get information about how to send a signed transaction with POST. Only `POST /api/v2/sendtx (hex tx data in request body)` is mentioned, but no description about what kind of parameters I need to send.

Where can I find anything about this?

**Comment by martinboehm** [comment]
`Hex tx data` means signed transaction in hex format. Blockbook is not composing transactions, it is only passing signed transactions to the backend for validation and distribution through the blockchain network.
You have to use some application to compose the transaction and sign it.

**Comment by sollerias** [comment]
@martinboehm ,

Oh, I mean there is no data in the API documentation on how to POST a hex transaction.  I am sending a signed transaction using the GET method, but the signed transaction is about 450 characters long, so I am afraid it is too long for a GET.

So, about POST: do I need to send JSON-data like this: { "tx": "transaction in hex"} or will it be another form of POST data, maybe another form of JSON? Where can I get information about this?

**Comment by martinboehm** [comment]
Just make a POST request with hex as a body of it. No need for JSON.

**Comment by Felix0301** [comment]
I am also experiencing trouble using this endpoint. Using Postman I get a "Missing tx blob". Tried with quotes, without, with ticks with different Headers (application/json & text/plain). Could you share an example of a correctly formatted request? :-)

**Comment by Felix0301** [comment]
My issue was solved by #222 👍

**Comment by martin-key** [comment]
I've had the same issue with the POST request. I have added more information in the README in that PR - https://github.com/trezor/blockbook/pull/817
