### ISSUE TITLE
Disk usage

### ISSUE THREAD

**Issue by AlexanderPavlenko** [trezor/blockbook#503]
Hello! Thanks for this software. Is there any actual data about the disk space required for full sync, especially for Ethereum Blockbook? 1 TB seemed to be not enough in my case.
I don't see Backend's "size on disk" at https://eth1.trezor.io/

**Comment by martinboehm** [comment]
Hi. Backend size on disk is displayed only if the backend reports it. However, I measured it for you, here are the numbers:
```
du -h -d 1 /opt/coins/data/ethereum/
1.4T	/opt/coins/data/ethereum/backend
121G	/opt/coins/data/ethereum/blockbook
1.5T	/opt/coins/data/ethereum/
```
Ethereum backend is growing quite fast, I would suggest using a disk with a big reserve.
