### ISSUE TITLE
How to decrease synchronization interval with blockchain

### ISSUE THREAD

**Issue by sollerias** [trezor/blockbook#504]
Hi, guys!

I would like to get my address balance information for Dash using Blockbook. Unfortunately, I ran into this situation: synchronization with the blockchain happens only once every 10 minutes or so. This means that I cannot create transactions more often because I do not know if the balance of my address has changed. Are there any settings in Blockbook configuration to reduce the time between syncs?

**Comment by martinboehm** [comment]
Hi, it seems that the connection to backend ZeroMQ is not working. Check your configuration and Blockbook log, you should see something like
```
mq.go:60] MQ listening to tcp://127.0.0.1:38333
```
when Blockbook starts.

**Comment by sollerias** [comment]
@martinboehm, hello!

Yes, when starting Blockbook this line appears:

`MQ listening to tcp://12.345.67.89:29998` (I have remote testnet node for Dash)

During the further work of Blockbook, I did not observe any errors from MQ.

**Comment by sollerias** [comment]
Hi, guys!

I have an update on my issue. I found this library behavior:
The local database is synchronized with the blockchain data every 15 minutes.  This occurs when the "blockbook" log generates the line 

`I1021 11:12:05.831925   12795 sync.go:111] resync: local at 394022 is behind`

Until another same line appears

`I1021 11:27:41.868043   12795 sync.go:111] resync: local at 394025 is behind`

I cannot get any balance, block information, or other blockchain change information which I need for the stable operation of my application.

Could you please explain what it might be and how to fix this behavior?

**Comment by martinboehm** [comment]
It looks like MQ connection is not working. Check the network rules etc.
The sync every 15 minutes is a fallback mechanism that Blockbook uses when it does not get an update from MQ for 15 minutes. It could be controlled by config parameter `-resyncindexperiod`, which defines the fallback period in milliseconds.

**Comment by sollerias** [comment]
@martinboehm, thanks! I'll check it.

**Comment by sollerias** [comment]
Thanks again! We've fixed that.
