### ISSUE TITLE
Latest Ethereum-go client new release  for security

### ISSUE THREAD

**Issue by Muggle-Du** [trezor/blockbook#509]
![4301605086812_ pic_hd](https://user-images.githubusercontent.com/25078682/98794147-aa176200-2443-11eb-9e1e-7249e9327859.jpg)
will this new version of ethereum go client be incompatible with the current version of blockbook

**Comment by martinboehm** [comment]
Thank you, we will check the issue

**Comment by martinboehm** [comment]
Done in commit 576b8b57b7974437cc0e69d7e31ed0305a090daf
