### ISSUE TITLE
Will blockbook work with CTOR in new Bitcoin ABC fork?

### ISSUE THREAD

**Issue by karel-3d** [trezor/blockbook#52]
Bitcoin ABC might have a hard-fork, which will make transaction be ordered differently in a block.

See https://www.reddit.com/r/btc/comments/9ehll3/a_technical_dive_into_ctor/

The problem is that with the new ordering, we might see in a block transaction *before* its parent/grandparent/..., which might produce some errors (the transaction will be spending an output of a transaction that we don't yet know, since it happens later in a block)

**Comment by prusnak** [comment]
It seems blockbook surived this: https://bch1.trezor.io/block/556767

**Comment by karel-3d** [comment]
satoshi's vision is alive!
