### ISSUE TITLE
Add scriptSig and witness to transaction vin/vout

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/blockbook#522]
This information is required by trezor-connect > firmware to implement new "replace-by-fee" feature.

they can be sent optionally, only in rbf transactions

**Comment by szymonlesisz** [comment]
turns out i didn't need it. i've just [calculated](https://github.com/trezor/connect/blob/920641a60538ec937a67713e65e3fee5e9ada0e7/src/js/core/methods/tx/refTx.js#L52) missing fields from the data that i already have

**Comment by martinboehm** [comment]
I will leave the functionality there. Apart from a small network overhead it does not cause any problems.
