### ISSUE TITLE
License Clarification   |   indexer for Trezor wallet .... Do not use for any other purpose.

### ISSUE THREAD

**Issue by HelloKashif** [trezor/blockbook#524]
The license in the source code is AGPL however the explorer footer mentions that this should not be used for any other purpose.

"Blockbook - blockchain indexer for Trezor wallet https://trezor.io/. Do not use for any other purpose."

Refer:
https://github.com/trezor/blockbook/blob/6447cdb1b70400d4333705e5c7dc5eb96ce230bd/build/text/about

Can you please clarify if we are allowed to use it outside the trezor wallet usecase or not?

**Comment by martinboehm** [comment]
Hi, I think this #194 answers your question.
