### ISSUE TITLE
Replace RBF exclamation mark with something less dangerous

### ISSUE THREAD

**Issue by tsusanka** [trezor/blockbook#525]
This is very nit-picky but I think the "danger" symbol that appears next to the transaction ID for RBF transaction is too "scary". I would like to replace it with smth less warning. I will discuss with @matejzak first.

![image](https://user-images.githubusercontent.com/1835345/100654547-44373f80-334a-11eb-8ad1-412a126ef1ff.png)

**Comment by martinboehm** [comment]
Actually, it is warning, danger is usually red :-) The symbol is an emoji character, not an image and it is browser dependent. Chrome shows it like this:
![image](https://user-images.githubusercontent.com/11609674/100658337-2ddfb280-334f-11eb-92aa-c7a53f81d100.png)

**Comment by matejzak** [comment]
I agree with @tsusanka. The warning symbol doesn't tell the user much about what kind of danger it is, or why they should be worried. Perhaps we can add information somewhere the transaction is not final? Let me know, if you need "design". Thanks!

**Comment by tsusanka** [comment]
@matejzak some ideas:

1.
![image](https://user-images.githubusercontent.com/1835345/101203412-e7e65f80-366a-11eb-9616-c726680a5077.png)

2.
![image](https://user-images.githubusercontent.com/1835345/101203492-08161e80-366b-11eb-8d0b-f2c359d264b9.png)

3. Different emoji?

**Comment by matejzak** [comment]
Thanks! I like `1.` the most since it's consistent with the Send form labels. Only we use ON/OFF so I'd suggest to do that here as well. Note: RBF feature will be thoroughly explained in the app in the near future so I believe ON/OFF here is sufficient.

**Comment by tsusanka** [comment]
Btw the terminology here is a bit flaky, we call it RBF, but it can be replaced also for other reasons that fee. But yeah, that's another topic. PR in #529, let's see what @martinboehm says about it :).
