### ISSUE TITLE
Align releasing with trezor infrastructure

### ISSUE THREAD

**Issue by vniche** [trezor/blockbook#527]
Hello there, first let me congratulate the team and say that Blockbook is an awsome project and game changing for the cryptocurrencies world 👏 

Now, about the issue, i've been running blockbook self-hosted and struggled on the past few weeks with upgrades, mainly because the repo's release is pointing to an outdated 0.3.4 compared *.trezor.io instances. I know that these are not necessarily related and trezor's may manage it's infrastructure as it pleases, but if the releasing process here on the repo follows the trezor's production release process it would enable others to stay up to date without much trouble.

**Comment by martinboehm** [comment]
Hi. We are preparing a new release. To make sure that the new version is stable, we run it on our production servers for some time before making the formal release.

However, the version 0.3.4 is good enough, we were running until now.

**Comment by vniche** [comment]
I see, then the production releases could be draft releases here on GitHub, while already tested versions would be stable/verified releases.

About the running 0.3.4, the version stated as latest release here on the repository differs much from the one running on *.trezor.io instances.

0.3.4 on repository points to eb4e10ac677b8c3763fd0c2a5e7f971e4d8cedd1 (from Jun 12) while the one from running instances have been upgrading from time to time, now pointing to 08afda91b37ec975ea194e7158e613ec34c9cdd0 (from 9 days ago)

**Comment by vniche** [comment]
Also, if it were to follow the blockchains distributions (and not suffer from unwanted forks or any related issue), blockbook's nodes versions are also outdated related to official and also *.trezor.io instances distributions.

**Comment by martinboehm** [comment]
Thank you for your tips, we will consider them.
