### ISSUE TITLE
Coin Spent links to the wrong transaction

### ISSUE THREAD

**Issue by soraphis** [trezor/blockbook#534]
investigating transaction: https://litecoinblockexplorer.net/tx/66da7b2037a97e84049fecd9486c086fef173bc85b22cb9b47ad5840cde4f81f

it has 3 outputs, where the first two have the same balance. clicking the red arrow on any of them links to the same transaction, even though output-2 is spent in a different transaction, here: 

https://litecoinblockexplorer.net/tx/ea83854cb2edd0a8ae0ec0203a1337e1feb1bae5d9ba2c12c39db3a59aabd058

**Comment by martinboehm** [comment]
Yes, unfortunately Blockbook is getting the spent links only heuristically and this can happen.

**Comment by ynohtna92** [comment]
This is still occurring, surely this can be fixed if you are able to mark the arrows as red to the correct transaction.
