### ISSUE TITLE
Integration question 

### ISSUE THREAD

**Issue by Droppix** [trezor/blockbook#535]
Hi,

I'm studying the possibility of integrating Monero (XMR) in Blockbook, but as I'm not a specialist of "Go", I would like to have your opinion on the difficulty of the integration and an estimation of the delay it could take.

Thanks

**Comment by Ooooze** [comment]
![image info](https://www.berfrois.com/wp-content/uploads/2013/05/eurotrip2.jpg)

=)

**Comment by martinboehm** [comment]
Hi, it is certainly doable in Go as in any other programming language. There is for example wallet RPC client written in Go https://github.com/gabstv/go-monero, which implements . 

However, it would probably require a lot of changes in the Blockbook base packages. Monero would have to be a new coin type as it is neither bitcoin type nor ethereum type, possibly have a different DB structure etc.

In general, we do not merge external pull requests which add features to the base packages, that we do not require for our own purposes. These changes would increase our maintenance efforts.
