### ISSUE TITLE
invalid BTG explorer link

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/blockbook#54]
moving issue from https://github.com/satoshilabs/mytrezor/issues/385,

When i click on "details" of BTG transaction (in wallet) i'm getting redirected from:
https://btg1.trezor.io/tx/[txid]
to
https://explorer.bitcoingold.org/insight/

and i not able to see requested transaction detail

**Comment by martinboehm** [comment]
Solved by moving BTG to blockbook internal explorer.
