### ISSUE TITLE
DB inconsistency. Only RPC without ZMQ

### ISSUE THREAD

**Issue by matyushkins** [trezor/blockbook#542]
Hi
`I1226 13:33:28.698378       6 worker.go:1723] GetBlock 3609579, page 0 finished in 1.309599ms
W1226 13:33:30.358504       6 worker.go:830] DB inconsistency:  tx d85cd1a5c668385e45bb613ed7e8d20fbd5a778c94762155ad32108a89d9393a: not found in txAddresses
W1226 13:33:30.359035       6 baseparser.go:37] tx d85cd1a5c668385e45bb613ed7e8d20fbd5a778c94762155ad32108a89d9393a, input tx  not found in txAddresses
W1226 13:33:30.359075       6 worker.go:830] DB inconsistency:  tx b5069197568d8e3edca01daada2f0e75ac6cc686eb8b4f84628a16e64571aae5: not found in txAddresses
I1226 13:33:30.360001       6 worker.go:1723] GetBlock 85ffca36ccfc8ad71f578bfc418f0496421640101c2733b3b515fced026fd0ab, page 0 finished in 2.006917ms
`

And tx Confirmations is `4294967279 Confirmations`

**Comment by martinboehm** [comment]
Sorry, I do not exactly understand the issue. What coin is it? What are the ZMQ issues?

In general, the `DB inconsistency` warning may be shown when a tx is just mined in the new block but Blockbook has not yet finished indexing of the new block. 

The backend in this case returns that the tx is confirmed but Blockbook does not find it in the index.

**Comment by matyushkins** [comment]
Coin: Reddcoin. In this case, the blockbook lags behind the node by 10-30 blocks. Then he catches up and lags behind again. This coin only has PRC, no ZMQ.

**Comment by martinboehm** [comment]
If there is no ZMQ, you can setup Blockbook to poll for new blocks and mempool transactions more often using parameters `-resyncindexperiod` and `-resyncmempoolperiod`, see for example https://github.com/trezor/blockbook/pull/228#issuecomment-521025616.

**Comment by matyushkins** [comment]
It work. Thanks
