### ISSUE TITLE
Subscribe to confimed txs

### ISSUE THREAD

**Issue by aghamir** [trezor/blockbook#544]
Dear @martinboehm 

Currently websocket returns notify when tx comes to mempool. This cause getting balance after receiving transaction only returns unconfimed balance which doesn't return the correct value for tokens(#543). 

I suggest that blockbook returns notify when a transaction of the subscribed address has been confirmed. Or at lease we have an option like `details=[unconfirmed|confirmed|all]` to set notify trigger time. 

I hope I explained the issue correctly

Best regards,

**Comment by martinboehm** [comment]
Hi, how about using `subscribeNewBlock` subscription and checking the balance after a new block is mined?

**Comment by aghamir** [comment]
Actually, it's good, I think. It doesn't do the same thing but surely will work. 
Thanks a lot.
