### ISSUE TITLE
Add some prometheus version metrics

### ISSUE THREAD

**Issue by petrkr** [trezor/blockbook#55]
Please add prometheus gauge metrics at least as follows:

Blockbook version:
blockbook{coin="bitcoin", version="0.0.6", "gitcommit"="hash", ...} 1

Backend version
backend{coin="bitcoin", version="0.16.2" (or similar), subversion="satoshi/0.16.2", ...} 1

Name of variables can be changed for some reason, but must be same across blockbooks/backends

Thank you !

**Comment by martinboehm** [comment]
Finished in commit e270cf0f950aaaf8246244eb12bf433f499ead2d.
