### ISSUE TITLE
Broadcasting bitcoin cash but seeing the transaction in bitcoin abc 

### ISSUE THREAD

**Issue by f4r4** [trezor/blockbook#553]
I have a node with the below config, the issue I am facing is that when I broadcast a transaction using blockbook to BCHN i still see that transaction on bitcoin ABC block explorers why is this happening ? 
Please advice 

```
Chain | main
Version | 22010000
Subversion | /Bitcoin Cash Node:22.1.0(EB32.0)/
Protocol Version | 70015
Last Block | 670301
Difficulty | 237725479123.9431
Size On Disk | 172191848887

```

**Comment by martinboehm** [comment]
Hi, sorry, this is not a question for the Blockbook repo. However, I think that ABC node can be configured to be connected to the BCHN network, which would explain the described behavior.
