### ISSUE TITLE
[Feature] Improve displaying of fees in tx detail

### ISSUE THREAD

**Issue by slush0** [trezor/blockbook#559]
Currently only total fees in tx detail is displayed. It would be nice to display also value of sat/B for better checking of transaction priority.

**Comment by martinboehm** [comment]
@slush0 Hi, Blockbook now computes `size` and `vSize` of the transaction. It currently displays `sat/vByte` if it knows `vSize` and `sat/Byte` if `vSize` is not applicable (no all coins have vSize).

<img width="553" alt="image" src="https://user-images.githubusercontent.com/11609674/188563698-a2e587da-b441-418c-9589-318a03780ee5.png">

Do you want to get `sat/vByte`, `sat/Byte` or both?

**Comment by slush0** [comment]
If I'm not mistakem, sat/vByte is the new norm (displayed across the bitcoin ecosystem). I would display that.

**Comment by martinboehm** [comment]
Implemented in v0.4.0.
