### ISSUE TITLE
RVN. FEE on block page is incorrect value

### ISSUE THREAD

**Issue by matyushkins** [trezor/blockbook#563]
HI.
RVN coin.
Fee on block page incorrect value. Is big.
Example:
[Block page](https://rvnblockexplorer.com/block/000000000000b8fa57bd690ca9cb65e97f62d9a7b4c661ffc0a0d77df4db1ea9)
[Tx page](https://rvnblockexplorer.com/tx/f7ff85fd737f2268831aa42978aada48b976cc92632b4046c2a3b8215575b582)

Probable problem in `valueSat` from node

**Comment by martinboehm** [comment]
Please fix it and submit a pull request. We (Trezor) do not maintain the Ravencoin integration.
