### ISSUE TITLE
Can I help with supporting TRON

### ISSUE THREAD

**Issue by Muggle-Du** [trezor/blockbook#564]
TRON is account model right now which is similar to the Ethereum , so how can I help with extending to Tron

**Comment by martinboehm** [comment]
We are not at this moment interested in adding coins to Blockbook that require non trivial implementation.
You are of course free to implement TRON in your own clone.

**Comment by Rancbar** [comment]
Does anyone have any information about this Tron explorer's source code based on BlockBook:

    blockbook-tron.tronwallet.me

**Comment by danicodez1** [comment]
It looks like `blockbook-tron.tronwallet.me` is a fork of blockbook which implements tron.
**It also looks like klever.io is violating this project's [GPL license](https://github.com/trezor/blockbook/blob/master/COPYING) by not publishing the source code.**
The repo appears to be here: https://github.com/TronWallet/gotron but it's probably private.

Maybe their devs can help with this issue.
@vniche

**Comment by matyushkins** [comment]
New url [https://tron.blockbook.chains.klever.io/](https://tron.blockbook.chains.klever.io/)

**Comment by npozd** [comment]
@matyushkins @danicodez1 have you got access to https://github.com/TronWallet/gotron?
