### ISSUE TITLE
Negative fee in estimateFee for DOGE

### ISSUE THREAD

**Issue by CherryDT** [trezor/blockbook#565]
I noticed weird results in estimateFee for DOGE - lower number of blocks can cause a **negative** fee of -100000000 to be returned:

Trezor's instance: (https://doge1.trezor.io/test-websocket.html)
![image](https://user-images.githubusercontent.com/6010463/107427185-6c4cd700-6b21-11eb-8ba4-8e446b3ee95a.png)

My own instance:
![image](https://user-images.githubusercontent.com/6010463/107427283-81296a80-6b21-11eb-85d9-c7f2dae79b7a.png)

**Comment by martinboehm** [comment]
Hi, negative fee means that the DOGE backend is not able to estimate the fee with given condition. Blockbook does not do any estimation on its own.
