### ISSUE TITLE
ErrAddressCollision because multiple coins uses same first letter in P2PKH and P2SH

### ISSUE THREAD

**Issue by wlc-** [trezor/blockbook#57]
I am currently implementing support for Myriad but because the DecodeAddress function in github.com/btcsuite/btcutil checks all registered networks to determine if it is a P2PKH or P2SH address it throws ErrAddressCollision.

We get an address conflict between Litecoin and Myriad (first letter in Litecoin P2SH is same as first letter in Myriad P2PKH).

I saw that Monacoin solved this by registering a dummy network. I do not think that solution is very good. How would you advise?

**Comment by martinboehm** [comment]
Hi. Please base your code on branch `v0.0.7`, which we will soon merge into master (or wait couple of days for the merge). In this branch we use our own fork of `btcutil`, where we will add a possibility to register coins with equal magic number. However, until it is done, use dummy like in case of Monacoin.

**Comment by rikardwissing** [comment]
Hmm, I've based my code on 0.0.7 but I still get address collision.

It's strange cause all the tests passes. But once I have installed it on the server and try to run the getAddressHistory API call it throws address collision. But if i remove litecoin from blockchain.go an reinstall it on the server the API calls work.

**Comment by wlc-** [comment]
Hmm, I've based my code on 0.0.7 but I still get address collision.

It's strange cause all the tests passes. But once I have installed it on the server and try to run the getAddressHistory API call it throws address collision. But if i remove litecoin from blockchain.go an reinstall it on the server the API calls work.

**Comment by wlc-** [comment]
You'll find my changes here:
https://github.com/wlc-/blockbook/commit/1aa8f37457d1adf3466d3d04c7f01bc0a5f18e5a

**Comment by wlc-** [comment]
Testserver here: https://139.162.175.108:9142/test.html

Try getAddressTxids with MADjFW2StHu6QqBfjiubYR7QrDVWo9KRRE for example.

**Comment by wlc-** [comment]
Thanks!
Works fine now. Closing this issue.
