### ISSUE TITLE
go-ethereum v1.10.0 - GetChainInfo: the method eth_protocolVersion does not exist/is not available

### ISSUE THREAD

**Issue by alexeirbv** [trezor/blockbook#572]
Hello! After updating to geth v1.10.0 blockbook shows error - `GetChainInfo: the method eth_protocolVersion does not exist/is not available`. It seems to be a bug in geth not in blockbok. Created that issue just FYI.

**Comment by martinboehm** [comment]
Fixed by removing the usage of `eth_protocolVersion` here 0ae8ba57a2d763c21c017eb17f0ef62d32e25c0f.

**Comment by alexeirbv** [comment]
@martinboehm Thank you!
