### ISSUE TITLE
Makefile BASE_IMAGE

### ISSUE THREAD

**Issue by matyushkins** [trezor/blockbook#577]
Hi. 
https://github.com/trezor/blockbook/blob/61c28340029f0c865ea0ae00dff7fdcfe8427bc6/Makefile#L4

Please add variant run make with vars BASE_IMAGE=ubuntu:18.04. We run make on local host with examples OS manjaro and make is crash error
> BASE_IMAGE=ubuntu:18.04 make                                                                                                                                                           
Building image blockbook-build from manjaro:
Sending build context to Docker daemon  6.144kB
Step 1/26 : ARG BASE_IMAGE
Step 2/26 : FROM $BASE_IMAGE
invalid reference format
make: *** [Makefile:47: .bin-image] Error 1

**Comment by martinboehm** [comment]
Hi. Try to build it the way it is described [here](https://github.com/trezor/blockbook/blob/master/docs/build.md#extra-variables), i.e. `make BASE_IMAGE=ubuntu:18.04 <your coin>`

**Comment by matyushkins** [comment]
Ok. Thanks.
