### ISSUE TITLE
[API Question] Regarding querying 'chainlock' status using `tx-specific` on a Dash transaction

### ISSUE THREAD

**Issue by greatwolf** [trezor/blockbook#578]
This is just a quick question on how to efficiently query for a chainlock status on a Dash transaction using the blockbook api. As per [documentation](https://github.com/trezor/blockbook/blob/master/docs/api.md#get-transaction-specific), I can query for that using `/api/v2/tx-specific` however it doesn't return all the same fields that the regular `/api/v2/tx` endpoint does. In particular I also need the array of `Addresses` field for `vin` which isn't included for the `tx-specific` endpoint.

Is there a way to efficiently query for both of these pieces of info without having to make 2 separate api calls? Note there is a large overlap in what both endpoints return.

**Comment by martinboehm** [comment]
As the "generic" endpoint `/api/v2/tx` does not know anything about coin "specific" data, you have to use the `/api/v2/tx-specific`. And although there is an overlap, you will have to query both.
