### ISSUE TITLE
BSV stuck at 678300

### ISSUE THREAD

**Issue by f4r4** [trezor/blockbook#582]
Blockbook does not move past 678300 any of you facing the same issue ?

backend: {
chain: "main",
blocks: 678300,
headers: 678952,
bestBlockHash: "00000000000000000de9a5810fab4d79bac24fe94937366f6f6cb379fe6a7e8e",
difficulty: "72975992025.82556",
version: "101000700",
subversion: "/Bitcoin SV:1.0.7/",
protocolVersion: "70015",
warnings: "Warning: The network does not appear to fully agree! We received headers of a large fork. Still waiting for block data for more details."
}

**Comment by martinboehm** [comment]
Hi. Sorry, we do not have BSV on our servers.
