### ISSUE TITLE
Ropsten Sync issues after Berlin fork

### ISSUE THREAD

**Issue by aman-rac** [trezor/blockbook#585]
Blockbook Version -> 0.3.4
Geth Version -> 1.10.1

Geth is synced. But Blockbook gives -> 

> ` bash resyncIndex Cannot disconnect blocks with height 9812189 and lower. It is necessary to rebuild index. `

In the config file `"block_addresses_to_keep": 100000,` which is before the fork. I can delete the datadir, are there any other options?

**Comment by martinboehm** [comment]
Yes, you have to delete the datadir and sync again.
