### ISSUE TITLE
[Feature] extend getAccountUtxo information

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/blockbook#589]
add `own` (boolean) field with check if tx.vin address belongs to utxo owner.
this information has influence on utxo selection algorithm in trezor-suite/connect/hd-wallet.
if utxo is "mine" then it's safe to use immediately otherwise it should be used after X confirmations

**Comment by Unrulyjulie4life** [comment]
Hello ,I unrulyjulie4life. I was part of. Minning pool and I'm trying to find my payment. And  I think maybe this is it . I completely  don't know what I'm doing . But I feel like I'm looking in the right place.  Can anyone please help me .

**Comment by Unrulyjulie4life** [comment]
I was in a sluss pool or could pool . Sorry for my lack of  knowledge and infomercial  thanks

**Comment by Unrulyjulie4life** [comment]
Hello iam I otx Vin? Please help me

**Comment by Unrulyjulie4life** [comment]
What do I do
 I just learn to read a little code today, and this important  so I know this is me .. I'm :mine"

**Comment by martinboehm** [comment]
`getAccountUtxo` returns only own utxos, the `own` field does not make sense I think. It the requested endpoint is `getAccountInfo`, the feature is implemented since version `0.3.6`, the field name is `isOwn`.
