### ISSUE TITLE
Ethereum blockbook issue

### ISSUE THREAD

**Issue by f4GGT** [trezor/blockbook#597]
- Upgraded the backend ethereum to new version and facing issue UI
- Service is starting without fail but couldnt see anything one the logs except 
`resyncIndex Block not found`

 anyone please advice

**Comment by martinboehm** [comment]
Is the backend fully synchronized?

**Comment by f4r4** [comment]
Is the backend fully synchronized?



> Is the backend fully synchronized?

Yes

**Comment by martinboehm** [comment]
It is not clear to me what is going on. Maybe the whole log of the service start would help.

**Comment by f4r4** [comment]
Blockchain.INFO  
Log file created at: 2021/04/16 11:16:27
Running on machine: ns3142434
Binary: Built with gc go1.15.5 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0416 11:16:27.126924   14377 blockbook.go:138] Blockbook: {Version:0.3.4 GitCommit:1f6cddd BuildTime:2021-04-16T10:18:07+00:00 GoVersion:go1.15.5 OSArch:linux/amd64}, debug mode false
I0416 11:16:27.130256   14377 ethrpc.go:171] rpc: block chain livenet
I0416 11:16:27.130274   14377 ethrpc.go:180] mempool created, MempoolTxTimeoutHours=48, QueryBackendOnMempoolResync=false
I0416 11:16:27.130301   14377 rocksdb.go:148] rocksdb: opening /opt/coins/data/ethereum/blockbook/db, required data version 5, cache size 536870912, max open files 16384
I0416 11:16:44.165747   14377 rocksdb.go:1696] loaded 12244000 block times
I0416 11:16:44.221566   14377 worker.go:1793] GetSystemInfo finished in 22.626589ms
I0416 11:16:44.221727   14377 internal.go:65] internal server: starting to listen on http://:9036
I0416 11:16:44.230867   14377 public.go:119] public server: starting to listen on http://:9136
I0416 11:16:44.233567   14377 sync.go:140] resync: local at 12243999 is behind
E0416 11:16:44.234559   14377 blockbook.go:294] resyncIndex Block not found
I0416 11:16:44.234971   14377 rocksdb.go:287] rocksdb: close

**Comment by martinboehm** [comment]
Is you backend on the right fork, i.e. what version of geth do you run? Block 12244000 is the Berlin hard fork block, see https://blog.ethereum.org/2021/03/08/ethereum-berlin-upgrade-announcement/

**Comment by f4r4** [comment]
geth-linux-amd64-1.10.1-c2d2f4ed.tar.gz

**Comment by martinboehm** [comment]
The version is OK. We do not have this problem with the same setup. The error `Block not found` is returned if the block hash or block data are not returned from the backend. You will have to figure out the state of your backend, why it does not return the data.

**Comment by alepc253** [comment]
@f4r4 could you fix this? I'm facing a similar issue integrating RSK (I'm using Ethereum base code for this, just minor changes up to now): a lot of `Block not found` because of non-existent hashes. Is it the same that it's happening to you?

**Comment by martinboehm** [comment]
@alepc253 @f4GGT Is the issue still active? Our Blockbooks are running fine. The issue could also be this https://github.com/trezor/blockbook/issues/636.

**Comment by alepc253** [comment]
@martinboehm I solved it for my case (different fields for block hash)

**Comment by aghamir** [comment]
@alepc253 
Can you share your solution. I faced the same issue too.

**Comment by alepc253** [comment]
@aghamir in my case, I was working with another network (RSK) that has a different set of fields for the block hash, so applying ETH block hashing function to RSK block header gets a hash that doesn't work for RSK and I got that message.

**Comment by aghamir** [comment]
Ah thanks a lot.

**Comment by rfabriciors** [comment]
Guys, does the blockbook achieve work with Ethereum light nodes?
Thank very much
