### ISSUE TITLE
WebSocket: ETH1 / Ropsten Error Connecting

### ISSUE THREAD

**Issue by Droppix** [trezor/blockbook#603]
Hi,

Recently, I have Websocket connection errors on 'wss://eth1.trezor.io/websocket' and 'wss://ropsten1.trezor.io/websocket' on 2 different servers, do you have a problem on your side?

`var ws = new WebSocket(wss://eth1.trezor.io/websocket)`
**ws.onerror: Unexpected server response: 403**

**In doing some research, I found this:** 

The unexpected server response 403 error is due to the fact that the server recognizes the connection request but fails to authorize it and doesn't allow connection. The connection was being rejected by the server as no origin header was set. The docs of NodeJS WebSocket describe it as:

If verifyClient is not set then the handshake is automatically accepted. If it is provided with a single argument then that is:

info {Object}
origin {String} The value in the Origin header indicated by the client.
req {http.IncomingMessage} The client HTTP GET request.
secure {Boolean} true if req.connection.authorized or req.connection.encrypted is set.

Suggestion?
Thanks

**Comment by martinboehm** [comment]
Hi. You should not be using our production servers. Please run your own instance.

**Comment by dsp1589** [comment]
@martinboehm Any suggestion on running our own instance? Does it download complete block chain of all the coins?
