### ISSUE TITLE
Load balancing through multi-blockbook gateway

### ISSUE THREAD

**Issue by sidhujag** [trezor/blockbook#604]
Hello there, 

Syscoin Core Dev and BCFN CTO here again. We are contributing this code to you in good faith under Open Source ethos as we have been relying on Blockbook for our SDK initiatives for Syscoin. We built a load balanced blockbook infrastructure you might find useful. 

Demo:
https://blockbook.elint.services/

You can refresh a few times and notice the host IP is changing. There are 4 backends running in it and is flexible. It offers sub-second responses and API aswell as front-end load balancing.

You can take the code here to launch via script: https://github.com/syscoin/blockbook-lb

**Comment by martinboehm** [comment]
Thank you for the information!
