### ISSUE TITLE
Issue with RSK integration

### ISSUE THREAD

**Issue by alepc253** [trezor/blockbook#613]
Hi team,
I'm running the backend with RSK node and this seems to be working OK but when connecting it to blockbook, blockbook queries block hashes that don't exist in RSK (I checked for ETH, BTC, Rinkeby and Ropsten and they don't exist there either).
Any clues about what can be happening here? where are those hashes generated or gotten?
Thanks!

**Comment by prusnak** [comment]
Could you post the hashes here?

**Comment by alepc253** [comment]
Any ideas about what to check? the connection between blockbook and backend/rsk node seems to be OK because the `eth_getBlockByHash` requests are being received by the node and it responses `null` (because this hashes don't exist)

**Comment by alepc253** [comment]
@prusnak I think I got it: `getBestHeader` doesn't get `hash` as a parameter of the response, that hash is then calculated with a function and it seems that we have a difference there
