### ISSUE TITLE
"Connection reset by peer" error

### ISSUE THREAD

**Issue by alepc253** [trezor/blockbook#619]
Hey team,

I'm getting this error very frequently when sending request to the node: `Post "http://127.0.0.1:4444": read tcp 127.0.0.1:41736->127.0.0.1:4444: read: connection reset by peer`, any idea about how to solve this?

Thanks!

**Comment by martinboehm** [comment]
Please do not waste our time with generic questions.

**Comment by alepc253** [comment]
Wow, I didn't expect this answer...

**Comment by martinboehm** [comment]
What kind of answers do you expect when you ask about connections to something running somewhere? There is no service configured to run on port 4444 in our repo!

**Comment by alepc253** [comment]
I'm integrating a new network to blockbook (Ethereum-like node), working in an, at least, hard environment for me and after solving other frictions I find this error that I assume it's not related to the node because I've never seen this in other integrations (that also index the network). This node is running in port `4444`, by the way.
I would expect some help from people that already have gone through this process, maybe questions asking for more context if it wasn't enough, things that I usually do myself when other people need support to work in RSK.
