### ISSUE TITLE
Genesis block transaction not found

### ISSUE THREAD

**Issue by kwissem1** [trezor/blockbook#624]
Genesis block exists in explorer: https://btc1.trezor.io/block/000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f

But as you can see its transaction isnt.
https://btc1.trezor.io/tx/4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b

Really thanks for your great work <3

**Comment by martinboehm** [comment]
Hi, it is an interesting anomaly. Probably, the backend is not returning the data of the very first transaction.

**Comment by prusnak** [comment]
That's the limitation of Bitcoin RPC.

If you try to use `getrawtransaction 4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b` directly via Bitcoin RPC it responds with: `The genesis block coinbase is not considered an ordinary transaction and cannot be retrieved (code -5)`.
