### ISSUE TITLE
[Feature] Caching

### ISSUE THREAD

**Issue by kwissem1** [trezor/blockbook#625]
Is there any option to pass to disable completly caching.
"-dbcache=0" is not helping.

Really thanks for your great work <3

**Comment by martinboehm** [comment]
Hi, Blockbook uses the following caches:
- RocksDB memory cache, controlled by `dbcache` flag
- transaction cache, which stores transactions from Blockchain in RocksDB, controlled by `noTxCache` flag
- ERC20 contract cache (only for Ethereum), in memory, not controlled by any flag, in general fairly small, for 100.000 cached contracts it will be only about 10MB large as a contract will not take more than 100 bytes on average
- xpub cache (only for Bitcoin type coins), in memory, not controlled by any flag, the size depends on the number of processed xpubs in the last 24 hours, for 10.000 xpubs will be in the range of tens of MB. The number of cached xpubs can be seen using the prometheus metrics `blockbook_xpub_cache_size`.

What do you want to achieve by disabling the cache? Memory consumption? Unfortunately even without caching the RocksDB is quite memory hungry...

**Comment by kwissem1** [comment]
Just for testing purpose.
Thanks for your help.
