### ISSUE TITLE
Is MATIC Ethereum Layer 2 coming soon?

### ISSUE THREAD

**Issue by zxy-2021** [trezor/blockbook#627]
Because of the high transaction fees on the Ethereum mainchain, more users are redirecting to the Layer 2 solution and most of them are into MATIC. We are working on a DeFi platform and want to integrate MATIC Ethereum Layer 2 as well. We might want to use blockbook in the near future to keep track of transaction histories, just to see if blockbook team are planning to add MATIC Integration. Thank you

**Comment by martinboehm** [comment]
There are no plans for MATIC at the moment.

**Comment by Turtus** [comment]
have you tried to extend https://github.com/trezor/blockbook/blob/7847f7c2adf4f1a06c2b0858fad62990d1b710e5/docs/ports.md ?

i actually also looking for matic trezor installation - as matic public rpc s///
