### ISSUE TITLE
Bitcoin Tx Info Incorrect (compared with bitcoind raw data)

### ISSUE THREAD

**Issue by Muggle-Du** [trezor/blockbook#629]
I tried to get tx details through blockbook api:

https://****/api/v2/tx/e9587767fa57dbbe767ab265d4f5b42323b32e1d6e762bdc17bd6aeebcbcc857

and the response shows the blocknumber of this tx is 687869
<img width="1376" alt="截屏2021-06-17 下午12 21 18" src="https://user-images.githubusercontent.com/25078682/122331271-1ec8f680-cf67-11eb-9ba8-30b09a6e5218.png">

while I query by bitcoind rpc and get 
>>> tx = rpc_connection.getrawtransaction('e9587767fa57dbbe767ab265d4f5b42323b32e1d6e762bdc17bd6aeebcbcc857',1)
>>> tx['blockhash']
'00000000000000000009874c4a34626d5befeec7620a3f87d4b9a7f8e58a22dd'
which corresponds to blocknumber 687867 and is the same as information in blockchair

so blockbook api had returned wrong information , what's the problem?

**Comment by martinboehm** [comment]
What Blockbook version/commit do you use? About a year ago we discovered a bug in the blockchain synchronization in case of rollback, which could very rarely place transactions to a different block. This is long time fixed though. Try to upgrade to the newest version, Blockbook will automatically fix all these rollback issues. All our production servers are reporting correct height for your transaction.

**Comment by Muggle-Du** [comment]
Thanks a lot , though I've updated my blockbook to the latest version just at that moment in the March of this year
I would try to update to the latest version in time and check if this bug got fixed
