### ISSUE TITLE
Transaction not found error

### ISSUE THREAD

**Issue by peterpan0708** [trezor/blockbook#636]
Try to get transaction details from api:
![image](https://user-images.githubusercontent.com/36805830/123922038-361dd000-d9ba-11eb-8d10-81190fb0fb57.png)
But got "transaction not found error"
Is there a way i can get all transactions in the network ?
I can only get the recent transaction details from api.

**Comment by martinboehm** [comment]
Blockbook should return all transactions. Is the txid valid?

**Comment by aghamir** [comment]
I faced the same issue in bsc(forked repository) and etc too.
https://etc1.trezor.io/address/0x6B176BD299b24E6c68e6fe8149793973C1eE24C6

**Comment by the-tinderbox** [comment]
The same thing with etc blockchain - many transactions are not found. Tried to reindex blockchain - didn't help.

Version / Commit / Build | 0.3.5 / 491580b / 2021-07-03T11:42:49+00:00
Backend: CoreGeth/v1.12.0-stable-c5ef3a9e/linux-amd64/go1.16.2

**Comment by martinboehm** [comment]
It seems like some strange issue with the backend. I have already reported the issue to the core-geth repo https://github.com/etclabscore/core-geth/issues/399.

**Comment by martinboehm** [comment]
The fix is to add a parameter `--txlookuplimit=0`, see the reply in the core-geth issue https://github.com/etclabscore/core-geth/issues/399. This commit https://github.com/trezor/blockbook/commit/4b233813800c820cb517396fe3a85968f5247dd2 fixes it for ETC.

**Comment by alexeirojas87** [comment]
I have the same issue with BTC and I think, the flag --txlookuplimit=0 is only for eth

**Comment by ahmadalli** [comment]
I'm having a similar issue with ltc

**Comment by mojbaba** [comment]
I have the same issue With litecoin and bitcoin. how it is solved on the trezor servers?

**Comment by alireza1371** [comment]
I have the same issue with LTC and I think, Is there any solutions for that? we seriously need it

**Comment by v1adislave** [comment]
I've recently faced the same issue, trying to integrate BTC SegWit. Maybe there are things that I missed?

**Comment by mano92fuentesjimenez** [comment]
I am facing the same issue with LTC and BTC. Is there a way to have information from all transactions?

**Comment by ciberluffy** [comment]
I'm facing the same problem with BTC. I appreciate any help to solve this issue.

**Comment by raisty** [comment]
FMI Why is it closed?

**Comment by martinboehm** [comment]
Reopening the issue. The original issue was ETH related and solved by the `--txlookuplimit=0` parameter.
However, the new issues are not very informative. Could you plese @ciberluffy @mano92fuentesjimenez @v1adislave @alireza1371 @raisty describe more precisely what problem are you facing (ie. version of Blockbook, missing tx, etc.)

**Comment by alexeirojas87** [comment]
> Reopening the issue. The original issue was ETH related and solved by the `--txlookuplimit=0` parameter. However, the new issues are not very informative. Could you plese @ciberluffy @mano92fuentesjimenez @v1adislave @alireza1371 @raisty describe more precisely what problem are you facing (ie. version of Blockbook, missing tx, etc.)

The problem that we have is the following
![image](https://user-images.githubusercontent.com/38229259/146617226-8d2e1518-4dc8-47eb-a3bf-fe63c1210a39.png)


I send some btc to an address "tb1q8at548ja9xvxxq9gylhag2k8tre5fwpx68525e" in testnet network, and receive a notification of this transaction con ID="317a3a9d3e6ba1c1bfe9ea6e8a3d41212dee98eaa3160b15a81853de5bfb9cc7", but at the moment that this transaction get one or more confirmations, the Get transaction endpoint show this error

![image](https://user-images.githubusercontent.com/38229259/146617454-8f74ff64-314c-42ae-a999-931e5259b8e5.png)

but if we take a look, the transaction does exist and is confirmed because we see it in the Get address endpoint.

**Comment by martinboehm** [comment]
@alexeirojas87 Is Blockbook never able to find the tx 317a3a9d3e6ba1c1bfe9ea6e8a3d41212dee98eaa3160b15a81853de5bfb9cc7 or only for a short time after it is mined in the new block?

**Comment by alexeirojas87** [comment]
> @alexeirojas87 Is Blockbook never able to find the tx 317a3a9d3e6ba1c1bfe9ea6e8a3d41212dee98eaa3160b15a81853de5bfb9cc7 or only for a short time after it is mined in the new block?

blockbook only finds the txs in the time between it is sent and the time it receives the first confirmation. When it receives the first confirmation we already receive Transaction X not found

**Comment by martinboehm** [comment]
Are you able to get the transaction from the backend, using `bitcoind-cli getrawtransaction`?

**Comment by alexeirojas87** [comment]
> Are you able to get the transaction from the backend, using `bitcoind-cli getrawtransaction`?

Look the transaction in this link https://www.blockchain.com/btc-testnet/tx/d2c0f99177eb10aa8ae962b2e9b871ec407ef133563cfd677e0ce0741ba0bedf

but this same id tx, not found in blockbook

![image](https://user-images.githubusercontent.com/38229259/146974245-9bb4fdcc-4f58-4533-9df4-420bc86d4f14.png)

**Comment by martinboehm** [comment]
But we have it in our Blockbook, see https://tbtc1.trezor.io/tx/d2c0f99177eb10aa8ae962b2e9b871ec407ef133563cfd677e0ce0741ba0bedf. The issue is not that Blockbook is not able to handle this transaction in general, there must be something specific to your instance. And without knowing more about your instance, I am not able to help you. We must narrow the problem and I suggest that you make sure that the transaction is in your backend by trying to find it using `bitcoind-cli getrawtransaction` command.

**Comment by peterpan0708** [comment]
> > Are you able to get the transaction from the backend, using `bitcoind-cli getrawtransaction`?
> 
> Look the transaction in this link https://www.blockchain.com/btc-testnet/tx/d2c0f99177eb10aa8ae962b2e9b871ec407ef133563cfd677e0ce0741ba0bedf
> 
> but this same id tx, not found in blockbook
> 
> ![image](https://user-images.githubusercontent.com/38229259/146974245-9bb4fdcc-4f58-4533-9df4-420bc86d4f14.png)

have you solve the problem?

**Comment by peterpan0708** [comment]
transaction can be found before first confirmation, but during 1-6 confirmations,  transaction can't be found, after 6 confirmations,   it can be found again

**Comment by alexeirojas87** [comment]
> > > Are you able to get the transaction from the backend, using `bitcoind-cli getrawtransaction`?
> > 
> > 
> > Look the transaction in this link https://www.blockchain.com/btc-testnet/tx/d2c0f99177eb10aa8ae962b2e9b871ec407ef133563cfd677e0ce0741ba0bedf
> > but this same id tx, not found in blockbook
> > ![image](https://user-images.githubusercontent.com/38229259/146974245-9bb4fdcc-4f58-4533-9df4-420bc86d4f14.png)
> 
> have you solve the problem?

No, I applied another strategy to solve my problem.

**Comment by alexeirojas87** [comment]
> transaction can be found before first confirmation, but during 1-6 confirmations, transaction can't be found, after 6 confirmations, it can be found again

The same thing happened to me

**Comment by martinboehm** [comment]
@alexeirojas87, @peterpan0708  Hi, please provide more details. Ideally blockbook log around the problematic case.

**Comment by peterpan0708** [comment]
> @alexeirojas87, @peterpan0708 Hi, please provide more details. Ideally blockbook log around the problematic case.

hi, we are now facing the problem, what detail do you need, thanks for help

**Comment by martinboehm** [comment]
Timed Blockbook responses (i.e. at xx:xx gettransaction works, at yy:yy does not work, at zz:zz works again), accompanied with the Blockbook log from the problematic period.

**Comment by huanghuang933** [comment]
> 

The problem is described in detail here:
STEP1: address A sends LTC to address B, get TXid: xxx
STEP2: To get the transaction record, use 'GET api/v2/xpub/$[xpubkey]', at this time txid xxx confirms 0 and appears at the top of the list.
STEP3: query the transaction record about 30 seconds later, and txid xxx disappears

**Comment by peterpan0708** [comment]
> The problem is described in detail here:
> STEP1: address A sends LTC to address B, get TXid: xxx
> STEP2: To get the transaction record, use 'GET api/v2/xpub/$[xpubkey]', at this time txid xxx confirms 0 and appears at the top of the list.
> STEP3: query the transaction record about 30 seconds later, and txid xxx disappears

The problem is described in detail here:
STEP1: address A sends LTC to address B, get TXid: xxx
STEP2: To get the transaction record, use 'GET api/v2/xpub/$[xpubkey]', at this time txid xxx confirms 0 and appears at the top of the list.
STEP3: query the transaction record about 30 seconds later, and txid xxx disappears

**Comment by peterpan0708** [comment]
> Timed Blockbook responses (i.e. at xx:xx gettransaction works, at yy:yy does not work, at zz:zz works again), accompanied with the Blockbook log from the problematic period.
The problem is described in detail here:
STEP1: address A sends LTC to address B, get TXid: xxx
STEP2: To get the transaction record, use 'GET api/v2/xpub/$[xpubkey]', at this time txid xxx confirms 0 and appears at the top of the list.
STEP3: query the transaction record about 30 seconds later, and txid xxx disappears

**Comment by martinboehm** [comment]
@huanghuang933 does the transaction record reappear later? How long does it take to sync block? Is your Blockbook connected to the backend using ZeroMQ? 
What would help is to see the Blockbook log from the period when you observe such issue.
The problem could be that the tx is removed from mempool (mined) but Blockbook synchronizes the new block a lot later (for example if it is not notified immediately about the new block using ZeroMQ).

**Comment by galt-tr** [comment]
@martinboehm I'm seeing similar problems with Bitcoin transactions. There are some missing transactions randomly across my blockbook instance when I query the transaction directly, but I can find the transaction in the block itself. Please see for example:
https://blockbook.siftbitcoin.com:9146/block/000000000000000012724b62feca5df085b61e4b05cf3e3b085819add23e4648?page=62 and ctrl-F halfway down the page for tx `f38b8fb8bf828c9faaf95691b7b0bb2d5ff039ed72f897f1b924183c6ebbe1b6`. 

Then look here: https://blockbook.siftbitcoin.com:9146/tx/f38b8fb8bf828c9faaf95691b7b0bb2d5ff039ed72f897f1b924183c6ebbe1b6 and see an error.

I tried running blockbook with `-fixutxo` but it found no errors. I'm assuming that perhaps the db is missing some data (unsure how) in the tx table. Is there any way to have it refresh the tx table without having to index all over again?

I cannot find any errors in the logs about this specific block, but I did have some some errors if blockbook crashed while indexing and the db not shutting down gracefully. But for the most part I resolved that with `-worker=1`.
