### ISSUE TITLE
[Feature] Add ERC721 module

### ISSUE THREAD

**Issue by hacfox** [trezor/blockbook#640]
Hello, Are there any plans to add the ERC-721 module? Thanks.

**Comment by hacfox** [comment]
I realized that this module should not be handled by `blockbook`, so I close it.

**Comment by apricotpancake** [comment]
Can you explain why? 
I just wanted to start implementing erc721, erc1155 directly in blockbook. 
How did you solved it? Did you use a public rpc, like infura

**Comment by hacfox** [comment]
> Can you explain why? 
> 
> I just wanted to start implementing erc721, erc1155 directly in blockbook. 
> 
> How did you solved it? Did you use a public rpc, like infura

You can find the docs [here](https://docs.opensea.io)

**Comment by apricotpancake** [comment]
Thanks for the fast response.
Unfortunately a link to docs.OpenSea doesn't help me much. 
I would like to use blockbook to query an address to get nfts (erc721, erc1155) and not rely on 3rd party providers. If I use OpenSea either them are using a service like infura or use their own indexer.

**Comment by hacfox** [comment]
@apricotpancake Ya. Of course the best way is based on blockbook. But I don't know when they plan to support it.

**Comment by apricotpancake** [comment]
Alright, I look into how much effort it is and might do a PR

**Comment by hacfox** [comment]
If they do not have any plan on it. I suggest that you can integrate it by opeasea's api

**Comment by apricotpancake** [comment]
> I realized that this module should not be handled by `blockbook`, so I close it.

So you just came to the conclusion it's easier to use opensea api instead of waiting for blockbook, or was there any other reason for this sentence?

**Comment by hacfox** [comment]
@apricotpancake yeah. We can not wait a long time for the ERC-721 supported. So We make a decision that integrate it by OpeaSea's.

**Comment by apricotpancake** [comment]
Thanks , that helps us on decision making
