### ISSUE TITLE
Ropsten blockbook 0.3.5 - multiple "block not found", sync stops at height 10494881

### ISSUE THREAD

**Issue by 7-of-9** [trezor/blockbook#642]
Hi,
Per subject - BB frontend 0.3.5 is failing to sync up to max height, and throwing errors as below:
`E0719 11:55:01.545498    1946 sync.go:338] getBlockWorker 3 connect block error Block not found. Retrying...
E0719 11:55:01.545545    1946 sync.go:338] getBlockWorker 2 connect block error Block not found. Retrying...
E0719 11:55:01.545549    1946 sync.go:338] getBlockWorker 5 connect block error Block not found. Retrying...
E0719 11:55:01.545581    1946 sync.go:338] getBlockWorker 7 connect block error Block not found. Retrying...
E0719 11:55:01.545590    1946 sync.go:338] getBlockWorker 6 connect block error Block not found. Retrying...
E0719 11:55:01.545636    1946 sync.go:338] getBlockWorker 0 connect block error Block not found. Retrying...
E0719 11:55:01.545638    1946 sync.go:338] getBlockWorker 1 connect block error Block not found. Retrying...
E0719 11:55:02.046946    1946 sync.go:338] getBlockWorker 6 connect block error Block not found. Retrying..`

The backend is: Geth/v1.10.4-stable-aa637fd3/linux-amd64/go1.16.4 - output on the
HTTP monitoring page: https://ac-dev0.net:29136

Backend output:

`INFO [07-20|05:42:10.210] Deep froze chain segment                 blocks=3    elapsed=13.711ms  number=10,582,352 hash=6b1d4a..2e5c20
ERROR[07-20|05:42:57.677] Snapshot extension registration failed   peer=c5b271da err="peer connected on snap without compatible eth support"
INFO [07-20|05:43:32.564] Imported new chain segment               blocks=1    txs=81      mgas=7.622     elapsed=72.481ms  mgasps=105.159  number=10,672,353 hash=59acd7..71452e age=1m40s     dirty=255.90MiB
INFO [07-20|05:43:33.653] Chain reorg detected                     number=10,672,352 hash=b9f94f..610176 drop=1   dropfrom=59acd7..71452e add=1   addfrom=52280f..04ca70
INFO [07-20|05:43:33.654] Imported new chain segment               blocks=1    txs=81      mgas=7.622     elapsed=37.587ms  mgasps=202.782  number=10,672,353 hash=52280f..04ca70 age=2m20s     dirty=255.90MiB
INFO [07-20|05:44:01.772] Imported new chain segment               blocks=1    txs=17      mgas=2.571     elapsed=37.044ms  mgasps=69.392   number=10,672,354 hash=69e1f9..a4bcf8 dirty=255.90MiB
INFO [07-20|05:44:10.224] Deep froze chain segment                 blocks=2    elapsed=13.191ms  number=10,582,354 hash=c53c14..a3a391
INFO [07-20|05:45:20.173] Imported new chain segment               blocks=1    txs=33      mgas=5.889     elapsed=88.585ms  mgasps=66.474   number=10,672,355 hash=0737f8..b7ef94 age=1m19s     dirty=255.90MiB
ERROR[07-20|05:46:21.929] Snapshot extension registration failed   peer=c5b271da err="peer connected on snap without compatible eth support"
INFO [07-20|05:46:24.538] Imported new chain segment               blocks=1    txs=18      mgas=4.072     elapsed=47.840ms  mgasps=85.122   number=10,672,356 hash=23634e..508b3e age=1m5s      dirty=255.90MiB
INFO [07-20|05:46:38.241] Imported new chain segment               blocks=1    txs=8       mgas=5.759     elapsed=13.638ms  mgasps=422.292  number=10,672,357 hash=d6c688..29700c dirty=255.97MiB
INFO [07-20|05:47:10.239] Deep froze chain segment                 blocks=3    elapsed=12.605ms  number=10,582,357 hash=6bea9f..ba3b5c
INFO [07-20|05:47:30.646] Imported new chain segment               blocks=1    txs=25      mgas=7.153     elapsed=46.726ms  mgasps=153.089  number=10,672,358 hash=d6e95d..811949 dirty=255.90MiB
INFO [07-20|05:48:48.740] Imported new chain segment               blocks=1    txs=46      mgas=6.871     elapsed=67.266ms  mgasps=102.141  number=10,672,359 hash=4e7e97..7a8a76 age=1m18s     dirty=255.90MiB
INFO [07-20|05:49:10.254] Deep froze chain segment                 blocks=2    elapsed=12.999ms  number=10,582,359 hash=7509c4..2fc4e9
ERROR[07-20|05:49:14.230] Snapshot extension registration failed   peer=cd047704 err="peer connected on snap without compatible eth support"
INFO [07-20|05:49:20.726] Imported new chain segment               blocks=1    txs=14      mgas=4.365     elapsed=40.125ms  mgasps=108.790  number=10,672,360 hash=55c84b..610949 dirty=255.90MiB
INFO [07-20|05:49:35.806] Imported new chain segment               blocks=1    txs=28      mgas=4.038     elapsed=18.860ms  mgasps=214.111  number=10,672,361 hash=70de15..6053fd dirty=255.90MiB
INFO [07-20|05:49:46.571] Imported new chain segment               blocks=1    txs=6       mgas=2.389     elapsed=13.408ms  mgasps=178.148  number=10,672,362 hash=2808b7..ee495e dirty=255.95MiB`

Any input is appreciated; trying to get a London-fork Ropsten deployment fully functional. Have tried multiple resync's from genesis on both front and backend.

**Comment by martinboehm** [comment]
Please build from master. We had to upgrade the client library Blockbook uses to access the backend. This commit fixes the problem https://github.com/trezor/blockbook/commit/491580bb654044b4d18f0255252a3c63460984c7

**Comment by 7-of-9** [comment]
Thanks @martinboehm - do you mean I should build latest `master` commit using e.g. `make deb-blockbook-ethereum_testnet_ropsten`, or must I follow the steps shown in [Manual Build](https://github.com/trezor/blockbook/blob/master/docs/build.md#manual-build)?

If the former, then please be advised that this is how I compiled and installed blockbook Ropsten service, i.e. I see the errors above using a manually built 0.3.5 using `make deb-blockbook-ethereum_testnet_ropsten` on latest commit https://github.com/trezor/blockbook/commit/491580bb654044b4d18f0255252a3c63460984c7...

I am retrying now with `NO_CACHE=true` directive...

**Comment by martinboehm** [comment]
Do the docker build, just get the latest `master` from the repo. It is always safer to do `make clean-all` before so that you can be sure that there is no docker caching issue.

**Comment by 7-of-9** [comment]
`**make clean-all** was the key! Previous builds I guess weren't picking up the updated library.

Thanks @martinboehm.
