### ISSUE TITLE
Blockbook ETH has stopped processing blocks (London hard fork)

### ISSUE THREAD

**Issue by kaladinlight** [trezor/blockbook#651]
Since the london hard fork upgrade has occurred at block 12,965,000, blockbook has stopped processing blocks. Status is the same for v0.3.5 which I am running myself and for v0.3.4 as can be seen at the public endpoint: https://blockbook-ethereum.tronwallet.me/.

As a side note, I also haven't seen any issues/prs for supporting EIP-1559 either (besides pointing to the newest geth version in the config).

**Comment by hacfox** [comment]
@kaladinlight the same as you, and I'm going to upgrade to v0.3.5.

**Comment by isimeen** [comment]
> @kaladinlight the same as you, and I'm going to upgrade to v0.3.5. and also nothing works.(edited)

You didn't change anything directly, just put it on top? The base folder is not cleaned during installation?

**Comment by hacfox** [comment]
@isimeen  yes，run `make all-ethereum`, and then replace the `blockbook` binary file.

**Comment by hacfox** [comment]
@kaladinlight @isimeen I have made the `master` branch, it works.

**Comment by martinboehm** [comment]
@kaladinlight @hacfox Please see this issue https://github.com/trezor/blockbook/issues/642

**Comment by hacfox** [comment]
@martinboehm Yes, I have seen it. thanks!

**Comment by isimeen** [comment]
> @kaladinlight @hacfox Please see this issue #642

Compiled through `make` and installed the received packages. Launched, and just empty logs. The files are updated, but no logs are written. And accordingly, it does not start.

**Comment by kaladinlight** [comment]
@martinboehm Thank you for the quick reply. I will try to spin things up off master and see if it picks back up. Is there a timeline for EIP-1559 support (new fee fields in tx, rpc endpoints, etc)? Or has there already been work done and merged into master that I missed?

**Comment by isimeen** [comment]
The ./coins/data/ethereum/backend/geth/chaindata folder has grown to 1 TB on Ethereum, how is this possible?

**Comment by kaladinlight** [comment]
> The ./coins/data/ethereum/backend/geth/chaindata folder has grown to 1 TB on Ethereum, how is this possible?

A geth full node is now at 1TB in size with all of the chain data. I just had to bump our volume size up from 1TB -> 1.5TB for this reason as well.

**Comment by isimeen** [comment]
> > The ./coins/data/ethereum/backend/geth/chaindata folder has grown to 1 TB on Ethereum, how is this possible?
> 
> A geth full node is now at 1TB in size with all of the chain data. I just had to bump our volume size up from 1TB -> 1.5TB for this reason as well.

Yes, now I looked on the Internet for the size, really about 1 TB. I haven't noticed how time has flown since March this year)

**Comment by kaladinlight** [comment]
Ok cool, so I just rebuilt the image from master and restarted and it looks like it is picking back up syncing!
