### ISSUE TITLE
blockbook cannot continue sync after restart system

### ISSUE THREAD

**Issue by aghamir** [trezor/blockbook#652]
After I restart the blockbook service, it raise this error
```
resyncIndex resync: remote best height error
resync: error - remote best height 0 less than sync start height 723
```
How do I resolve this issue?

**Comment by martinboehm** [comment]
One cannot see your setup from the error description but it looks like the backend is not synchronized correctly (or Blockbook is connecting to wrong backend).

**Comment by aghamir** [comment]
I found the issue. I ran the `Geth` backend with `fast` mode. It works correctly and will sync until you restart blockbook service. Because of [this issue](https://github.com/ethereum/go-ethereum/issues/23405), after restarting the blockbook service, the `blockNumber` returns 0. Hence, `blockbook` returns error in this line and not continuing the syncing.  
https://github.com/trezor/blockbook/blob/b82dc92522eee957b7a139c38269a1844fe102f8/db/sync.go#L161
