### ISSUE TITLE
Ability to change from localhost to a local domain name or IP

### ISSUE THREAD

**Issue by jimmysong** [trezor/blockbook#66]
The certificate for https only works with localhost. I can't run this software on one computer and point to it with another computer on the network.

**Comment by martinboehm** [comment]
Hi, you have two options:
1) specify different certificate, either by command line parameter `-certfile` or by changing the links in `/opt/coins/blockbook/<coin>/cert/`
2) run blockbook behind nginx. This is how we run our blockbooks and how we recommend to run it in production.
