### ISSUE TITLE
Issue after migrating backend data to new volume

### ISSUE THREAD

**Issue by rabinshrestha** [trezor/blockbook#672]
My root volume filled due to backend data so, I

1. moved data from `/opt/coins/data` to new mount location `/mnt/ethereum-volume/data/data` 
2. changed configs/environ.json config to new path
3. created new build and restarted backend service

Backend service is stuck on **Head state missing, repairing**

**Comment by rabinshrestha** [comment]
@martinboehm

**Comment by martinboehm** [comment]
@rabinshrestha Hi, how can I help you with a corrupted backend DB?
