### ISSUE TITLE
Crash due to illegal instruction (SIGILL) in rocksdb

### ISSUE THREAD

**Issue by rikublock** [trezor/blockbook#684]
By default the rocksdb binary is optimized for the platform you're compiling on, which can lead to problems when trying to install a deb package on a different system. Certain processor instructions might not necessarily be available depending on the platform used to compile the binaries.

Adding `PORTABLE=1` to the make command when building rocksdb resolves this type of issue, see [here](https://github.com/facebook/rocksdb/blob/master/INSTALL.md)

The Dockerfile could be adjust in the following way:
`RUN cd /opt/rocksdb && CFLAGS=-fPIC CXXFLAGS=-fPIC PORTABLE=1 make -j 4 release`

I also prepared a pull request that adds an optional `PORTABLE` variable to the existing blockbook build process. See #685

Most likely related to issue #195

**Comment by martinboehm** [comment]
Resolved by #685
