### ISSUE TITLE
ETH NFT Txn Fetch (ERC-721/ERC1155) 

### ISSUE THREAD

**Issue by mchalise** [trezor/blockbook#690]
How to pull NFT txns from ETH addr. Any endpoint?

**Comment by Turtus** [comment]
its not supported for now - hope someday devs will do - or we should do ourselves

**Comment by martinboehm** [comment]
It is planned for the next release, be patient, please.

**Comment by suleymancalikprb** [comment]
Hi @martinboehm I guess you completed this functionality on https://github.com/trezor/blockbook/commits/eth_update  Wen release ser :)

**Comment by martinboehm** [comment]
Finished with v0.4.0
