### ISSUE TITLE
transactions in mempool

### ISSUE THREAD

**Issue by shlee890727** [trezor/blockbook#691]
ETH testnet is in use.
block-book running
The log shows that transactions in mempool have occurred,
It is created by setting the amount value of the transaction to 0.

**Comment by shlee890727** [comment]
https://ropsten.etherscan.io/tx/0xe6b246048d2dd8f19aecc95f0d170f609aea2d36c07599ba045263863a33a94f

**Comment by martinboehm** [comment]
Sorry, I do not understand your issue.
