### ISSUE TITLE
Incorect txs in /address/<address> response

### ISSUE THREAD

**Issue by screw** [trezor/blockbook#694]
"coin":"Bitcoin"
"version":"0.3.5"

The value of `txs` when I query `api/v2/address/<address>?from=XX&to=XX` is the same no matter what block range I select.
Even if the response doesn't contain any transactions I still get for example `txs=2`.
I assume the returned value of `txs` is the number of transactions across all blocks not taking into account the filter.

Is that a bug or is that intended behaviour?

**Comment by martinboehm** [comment]
Hi, the `txs` field always contains the total number of transactions.

**Comment by screw** [comment]
Just to clarify, so no matter what the parameters are (`to`, `from`, `page`, `pageSize`) you will always get the same number?

**Comment by martinboehm** [comment]
Yes
