### ISSUE TITLE
ETH - Out of space

### ISSUE THREAD

**Issue by xsoft** [trezor/blockbook#696]
As suggested, SSD was added to single instance ETH only backend machine.
Even with 2TB I run out of space, after 50+ days of syncing (on 1Gb network).

Any tips how to compress or trim database at this point?
I really dont want to spend 2 month again waiting for a sync (like anything more than week is insane).
Thanks for tips.

**Comment by martinboehm** [comment]
Hi, here is our disk usage of the Ethereum mainnet:
```
2.8T	/opt/coins/data/ethereum/backend
290G	/opt/coins/data/ethereum/blockbook
3.1T	/opt/coins/data/ethereum
```
