### ISSUE TITLE
Both the coin and token to be transmitted are transmitted as 0 without being transmitted over a certain value.

### ISSUE THREAD

**Issue by ghost** [trezor/blockbook#700]
I am using ETH Ropsten Testnet.
Both the coin and token to be transmitted are transmitted as 0 without being transmitted over a certain value.

**Comment by shlee890727** [comment]
전송 값 한도가 있습니까?

**Comment by martinboehm** [comment]
I do not really understand, where in the application happens the issue you are describing but Blockbook does not have any transfer value limit.
