### ISSUE TITLE
ETH- context deadline exceeded

### ISSUE THREAD

**Issue by 0x799** [trezor/blockbook#701]
An error occurred during the synchronization of Ethereum data.

`
E1110 05:41:32.182512       1 sync.go:338] getBlockWorker 0 connect block error hash 0xbda416f2f26f5b9cca7b8e611a94b26eaf274662a4b9fade6ac6896319bfebb9, height 9266808: context deadline exceeded. Retrying...
E1110 05:41:32.231909       1 sync.go:338] getBlockWorker 2 connect block error blockNumber 0x8d6675: context deadline exceeded. Retrying...
E1110 05:41:32.345175       1 sync.go:376] GetBlockHash error height 9266810: context deadline exceeded
E1110 05:41:32.345167       1 sync.go:338] getBlockWorker 5 connect block error hash 0x5d102691709b5ffc270d590d89bda3d801130a5aff2b8f7696f1336c2cd872ea, height 9266809: context deadline exceeded. Retrying...
E1110 05:41:32.375651       1 sync.go:338] getBlockWorker 4 connect block error blockNumber 0x8d6677: context deadline exceeded. Retrying...
E1110 06:31:32.701785       1 sync.go:338] getBlockWorker 0 connect block error hash 0xbda416f2f26f5b9cca7b8e611a94b26eaf274662a4b9fade6ac6896319bfebb9, height 9266808: context deadline exceeded. Retrying...
E1110 06:31:32.732383       1 sync.go:338] getBlockWorker 2 connect block error hash 0xabf8fe425dfc9125b954b6b1cf5742f9f81000a7698b5cb5a18560996d1fd0ed, height 9266805: context deadline exceeded. Retrying...
E1110 06:31:32.845758       1 sync.go:338] getBlockWorker 5 connect block error hash 0x5d102691709b5ffc270d590d89bda3d801130a5aff2b8f7696f1336c2cd872ea, height 9266809: context deadline exceeded. Retrying...
E1110 06:31:32.845780       1 sync.go:376] GetBlockHash error height 9266810: context deadline exceeded
E1110 06:31:32.876215       1 sync.go:338] getBlockWorker 4 connect block error hash 0x659090544b07b6d5cbe7405aebe44cc38d1a314e8646f5b2395ef1c2e1d062f5, height 9266807: context deadline exceeded. Retrying...
E1110 07:21:33.202538       1 sync.go:338] getBlockWorker 0 connect block error hash 0xbda416f2f26f5b9cca7b8e611a94b26eaf274662a4b9fade6ac6896319bfebb9, height 9266808: context deadline exceeded. Retrying...
E1110 07:21:33.232864       1 sync.go:338] getBlockWorker 2 connect block error hash 0xabf8fe425dfc9125b954b6b1cf5742f9f81000a7698b5cb5a18560996d1fd0ed, height 9266805: context deadline exceeded. Retrying...
E1110 07:21:33.346319       1 sync.go:338] getBlockWorker 5 connect block error hash 0x5d102691709b5ffc270d590d89bda3d801130a5aff2b8f7696f1336c2cd872ea, height 9266809: context deadline exceeded. Retrying...
E1110 07:21:33.346359       1 sync.go:376] GetBlockHash error height 9266810: context deadline exceeded
E1110 07:21:33.376714       1 sync.go:338] getBlockWorker 4 connect block error hash 0x659090544b07b6d5cbe7405aebe44cc38d1a314e8646f5b2395ef1c2e1d062f5, height 9266807: context deadline exceeded. Retrying...
E1110 07:22:52.498511       1 worker.go:1750] GetChainInfo error context deadline exceeded
I1110 07:22:52.516587       1 worker.go:1799] GetSystemInfo, 50m0.018390971s
E1110 07:22:52.517045       1 public.go:368] write tcp 172.17.0.4:9136->10.10.0.55:50250: write: broken pipe
E1110 07:23:11.926530       1 worker.go:1750] GetChainInfo error context deadline exceeded
I1110 07:23:11.943577       1 worker.go:1799] GetSystemInfo, 50m0.017351291s
E1110 07:23:11.944088       1 public.go:368] write tcp 172.17.0.4:9136->10.10.0.55:50251: write: broken pipe
`

**Comment by martinboehm** [comment]
This looks like Blockbook cannot reach the backend
