### ISSUE TITLE
balance of address is  shown differently on ropstanscan.io and blockbook

### ISSUE THREAD

**Issue by Sonmezturk** [trezor/blockbook#703]
total balance:0.305 Ether and 2txs are  shown in https://ropsten.etherscan.io/address/0x92Db03e7f8AE7325fB964FB0922913D3693E7413 and this information is true.

But problem is in blockbook. You can see tx infos and balance in picture.
<img width="1489" alt="Screen Shot 2021-11-10 at 16 48 57" src="https://user-images.githubusercontent.com/12473727/141124792-ac308e58-d1ba-4603-9c13-9fb66f480ebc.png">

**Comment by martinboehm** [comment]
Hi, our instance returns correct result: https://ropsten1.trezor.io/address/0x92Db03e7f8AE7325fB964FB0922913D3693E7413

**Comment by Sonmezturk** [comment]
hi
<img width="1483" alt="Screen Shot 2021-11-11 at 09 51 29" src="https://user-images.githubusercontent.com/12473727/141251814-b9269342-e8fb-466e-bd15-67a527b88652.png">

I noticed that the block height of the blockbook I am using is 10 days behind your server. But it seems to be constantly pulling new blocks, what could be the reason?
<img width="1545" alt="Screen Shot 2021-11-11 at 09 57 45" src="https://user-images.githubusercontent.com/12473727/141252351-3ef7e177-e13b-453a-a037-e227bdf160d7.png">

**Comment by martinboehm** [comment]
You run very old version of geth (1.10.6), which is on a wrong chain. Current version is Geth/v1.10.12-stable-6c4dc6c3/linux-amd64/go1.17.2. You will have to upgrade it and hope that it will roll back and sync to the right chain.

**Comment by Sonmezturk** [comment]
Thanks a lot for your quick reply, should I pull the newest blockbook repo for the update and then run the backend service again?

**Comment by martinboehm** [comment]
Yes, the newest Blockbook contains the definition of Geth/v1.10.12-stable-6c4dc6c3/linux-amd64/go1.17.2 backend package.

**Comment by Sonmezturk** [comment]
I did the update. For now, geth is in the latest version, now should I wait for it to complete the missing blocks? @martinboehm 
<img width="1470" alt="Screen Shot 2021-11-11 at 17 09 41" src="https://user-images.githubusercontent.com/12473727/141312192-66df2816-1fc1-4e1e-8d6f-f6ce5c0fa52c.png">
