### ISSUE TITLE
Geth/v1.10.06-> Geth/v1.10.12 update

### ISSUE THREAD

**Issue by Sonmezturk** [trezor/blockbook#705]
I updated the new blockbook. Backend and blockbook services have been updated. blocks are still 10 days behind.
This is the correct one: https://ropsten1.trezor.io/
My updated blockbook:
<img width="1462" alt="Screen Shot 2021-11-12 at 10 30 50" src="https://user-images.githubusercontent.com/12473727/141427648-9fad4bcc-e51b-4ffa-9a8c-5388326ec0ad.png">

Will I encounter this problem with main net updates as well? Or, when I pull the repo and update it, is it possible to make a normal transition without any problems?

**Comment by martinboehm** [comment]
It happened to us too in one instance where we forgot to upgrade the backend. Unfortunately, it did not do any rollback automatically, we had to delete the database and resync the backend from scratch (it took about 3-4 days to sync). 

You could try to force rollback using the command described here https://github.com/ethereumproject/go-ethereum/pull/206 instead but I cannot give you any hint on that.

**Comment by Sonmezturk** [comment]
Did this problem arise because I did not update immediately, or will I have the same problem in the next update? Do I have to wait for the blockbook to sync on every geth update?

**Comment by martinboehm** [comment]
The problem arose because you were running an old version of geth. I would recommend to upgrade geth as soon as they release a new version.
