### ISSUE TITLE
Blockbook Ropsten rollback

### ISSUE THREAD

**Issue by isefatuna** [trezor/blockbook#706]
How can I do rollback in blockbook (for example, I want to sync again starting from block number 10510950), if rollback is not possible, which folder should I delete to start by deleting all blocks.

**Comment by martinboehm** [comment]
You can rollback blocks up to `block_addresses_to_keep` setting from the config file using the `-rollback=<rollback to blockheight>` parameter, i.e. if you are on block 10000 and `block_addresses_to_keep` is 300, you can rollback to block 9700.

If that is not enough, you can delete the db by removing all files from the folder which is specified by `-datadir` parameter. If you run our standard setup, it would be `/opt/coins/data/ethereum_testnet_ropsten/blockbook/db`.
