### ISSUE TITLE
[BTC] Internal server error

### ISSUE THREAD

**Issue by screw** [trezor/blockbook#712]
Version 0.3.6

When I try to access the last page or page higher than `totalPages` for this particular address, I get "Internal server error".

But it happens only for this address

```` https://btc1.trezor.io/api/v2/address/1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa?details=txs&pageSize=1&page=4131````

From the log of our server: 

````10 public.go:311] apiAddress error: GetTransaction 4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b: Transaction '4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b' not found````

**Comment by wakiyamap** [comment]
`4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b` is Coinbase Transaction of genesis block.
It is a specification of blockbook.

https://btc1.trezor.io/block/000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f
https://mainnet-explorer.wakiyamap.dev/block/000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f

**Comment by screw** [comment]
I am not sure how the referenced issue is related to this one.

Another example:
If I do this query `https://btc1.trezor.io/api/v2/address/1P5ZEDWTKTFGxQjZphgWPQUpe554WKDfHQ?details=txs&page=19999992036854775` I get all the transactions.

But if I do it with bigger `page` like so:

`https://btc1.trezor.io/api/v2/address/1P5ZEDWTKTFGxQjZphgWPQUpe554WKDfHQ?details=txs&page=29999992036854775`

I get "internal server error".


There are only ± 627 transactions with this address every request with full page (1000txs) will get all of them.

**Comment by screw** [comment]
In case this is of any value
`page=27670116110564327` returns all txs

`page=27670116110564328` returns only one, probably last tx

`page=27670116110564329` returns Internal server error

**Comment by atomlab** [comment]
The same problem but with ETH

```
GET /api/v2/address/0xD61eB9E6745b3F80F1e0421c72Fcc90a5053BdD1?pageSize=25&details=txs&filter=All
```
output
```
{"error":"Internal server error: GetTransaction 0xc66afa255fe1dd08cda5a0d179171a51ae64146da50dd6ce89f0ba054e42eee7: Transaction '0xc66afa255fe1dd08cda5a0d179171a51ae64146da50dd6ce89f0ba054e42eee7' not found, data \u003cnil\u003e"}
```
