### ISSUE TITLE
Manual build fails

### ISSUE THREAD

**Issue by GBBx** [trezor/blockbook#714]
Hi there,

since v0.3.6 the manual build fails.
I follow these steps: https://github.com/trezor/blockbook/blob/v0.3.6/docs/build.md#manual-build

Here's what happens:
- I build RocksDB 6.22.1:
```
cd rocksdb
git checkout v6.22.1
CFLAGS=-fPIC CXXFLAGS=-fPIC make release
```
- set variables:
```
export CGO_CFLAGS="-I/path/to/rocksdb/include"
export CGO_LDFLAGS="-L/path/to/rocksdb -lrocksdb -lstdc++ -lm -lz -ldl -lbz2 -lsnappy -llz4"
```
- try to build Blockbook:
```
    BUILDTIME=$(date --iso-8601=seconds); \
    GITCOMMIT=$(git describe --always --dirty); \
    LDFLAGS=" -X github.com/trezor/blockbook/common.version=${BLOCKBOOK_VERSION} -X github.com/trezor/blockbook/common.gitcommit=${GITCOMMIT} -X github.com/trezor/blockbook/common.buildtime=${BUILDTIME}" && \
    go build -tags rocksdb_6_16 -ldflags="-s -w ${LDFLAGS}" 
```
This one fails with
```
# github.com/flier/gorocksdb
/app/go/pkg/mod/github.com/flier/gorocksdb@v0.0.0-20210322035443-567cc51a1652/filter_policy.go:49:72: cannot use _Ctype_int(bitsPerKey) (type _Ctype_int) as type _Ctype_double in argument to _Cfunc_rocksdb_filterpolicy_create_bloom
/app/go/pkg/mod/github.com/flier/gorocksdb@v0.0.0-20210322035443-567cc51a1652/filter_policy.go:55:77: cannot use _Ctype_int(bitsPerKey) (type _Ctype_int) as type _Ctype_double in argument to _Cfunc_rocksdb_filterpolicy_create_bloom_full
```

The same steps used to work with Blockbook v0.3.5 (RocksDB v6.13.3, Go 1.15.6).

I understand it is not a problem in your code but in the dependencies but I wonder how you build it in v0.3.6?

**Comment by martinboehm** [comment]
Hi, you are trying to use too new version of RocskDB. Unfortunately, in version 6.24.0 they made a backwards incompatible change in API (see https://github.com/facebook/rocksdb/releases/tag/v6.24.2, info about `bits_per_key` parameters) and Blockbook is not yet ready for that. Make sure that you use an earlier version - I would recommend to use 6.22.1, the version we are using in our production.

**Comment by GBBx** [comment]
Yes, you are right. I forgot to reference the version number in the rocksdb build steps.
Thanks a lot for your help.
