### ISSUE TITLE
What is the fastet way to query ethreum addresses info?

### ISSUE THREAD

**Issue by 123Serg** [trezor/blockbook#722]
Hello, I want to ask what is the fastet way to get info about eth address through blockbook? Info I'm interested in: number of transactions, balance, tokens balance.
I want to test with huge amount of addresses, I've only tested http request api(I've got speed like 1000 addresses in 8 seconds using localhost). Maybe I can use some sort of database query or is there websocket/ipc rpc?

**Comment by martinboehm** [comment]
The speed of ETH address info is currently limited by the speed of fetching the token balance from geth using `eth_call` as token balance is not indexed in Blockbook.
We are preparing a new version of Blockbook, with better support of Ethereum (internal transactions, NFT tokens etc.), which will also index token balances. The address info will be (hopefully) much faster in the new version.

**Comment by 123Serg** [comment]
> The speed of ETH address info is currently limited by the speed of fetching the token balance from geth using `eth_call` as token balance is not indexed in Blockbook.
> 
> We are preparing a new version of Blockbook, with better support of Ethereum (internal transactions, NFT tokens etc.), which will also index token balances. The address info will be (hopefully) much faster in the new version.

Thank you for answer. Then how blockbook know which token contract addresses to call for fetching balance on user specified address? Do you have a data of every created token or something like that?

**Comment by martinboehm** [comment]
Blockbook has for each address data with which token it interacted.
