### ISSUE TITLE
Blockbook is way behind backend

### ISSUE THREAD

**Issue by mehdiirh** [trezor/blockbook#732]
It's been more than 40h that litecoin **backend is fully synchronized** but blockbook is still syncing

![image](https://user-images.githubusercontent.com/38499444/153070090-a8c5a566-3410-4a6c-8636-d608050a9950.png)

I guess blockbook syncing must be much faster than backend ?

and another problem is if I reboot my server, because of "database is in inconsistent state and cannot be used" error blockbook fails to start

Server:
4 core
8 GB RAM + 12 GB Swap
160GB NVMe SSD
 
![image](https://user-images.githubusercontent.com/38499444/153070684-6e30bb53-3680-47cb-9379-5a6dfbaa3338.png)

Blockbook syncing:
![image](https://user-images.githubusercontent.com/38499444/153071058-226ce350-2996-4981-887a-615d3b872a24.png)

**Comment by martinboehm** [comment]
Hi. I would expect Blockbook to fully sync Litecoin in a couple of hours. Is there something suspicious in the log file when the syncing is hanging? Or maybe it just run out of memory and is swapping a lot which slows down the process to halt.

When Blockbook is doing the initial sync, it switches for performance reasons to bulk insert mode, which may leave the DB temporarily in an inconsistent state. If you kill Blockbook in this mode, it refuses to continue syncing after start, the DB must be deleted and resynced again, see more [here](https://github.com/trezor/blockbook#error-internalstate-database-is-in-inconsistent-state-and-cannot-be-used).

I would recommend to retry it with parameter `-workers=1`, which disables the bulk import mode.

**Comment by mehdiirh** [comment]
Hi. I have 885 ERROR logs. don't know how to check them all 
![image](https://user-images.githubusercontent.com/38499444/153082559-dce3b1be-26d2-4ce4-a4e5-88d8c5b202aa.png)

-----

So when initial sync is done, the problem of not starting after reboot will be solved ?

**Comment by mehdiirh** [comment]
And I have another question. what is that `-dirty` after commit ?

**Comment by martinboehm** [comment]
If you are not in bulk insert mode, you can kill Blockbook any time and it should work just fine after restart as all DB write operations are done in transactions. `-dirty` after commit means that you are building Blockbook with some local uncommitted changes.

**Comment by mehdiirh** [comment]
Got it, Thank you for providing information

**Comment by mehdiirh** [comment]
Hi, I reopen this issue 

I left blockbook syncing during the night and after I woke up today, I saw both backend and blockbook turned off with error: not enough space 

as Litecoin blockchain size is about 70GB, I though 160GB might be more than enough, but since blockbook save blocks in DB, that 70GB will be doubled to 140GB ( am I right ? )

anyways, I added 20GB to my server, blockbook and backend are now running but I get :

```
503 Service Unavailable
No server is available to handle this request.
```

with this error:
```
Log file created at: 2022/02/09 06:43:35
Running on machine: blockbook-btc
Binary: Built with gc go1.17.1 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0209 06:43:35.482278   10254 blockbook.go:212] internalState: database is in inconsistent state and cannot be used

```

I tried to add `-workers=1` to blockbook but I get same error:

```
[Unit]
Description=Blockbook daemon (Litecoin)
After=network.target
Wants=backend-litecoin.service

[Service]
ExecStart=/opt/coins/blockbook/litecoin/bin/blockbook -blockchaincfg=/opt/coins/blockbook/litecoin/config/blockchaincfg.json -datadir=/opt/coins/data/litecoin/blockbook/db -sync -internal=$
User=blockbook-litecoin
Type=simple
Restart=on-failure
TimeoutStopSec=300
WorkingDirectory=/opt/coins/blockbook/litecoin

# Resource limits
LimitNOFILE=500000

# Hardening measures
####################

# Provide a private /tmp and /var/tmp.
PrivateTmp=true

# Mount /usr, /boot/ and /etc read-only for the process.
ProtectSystem=full

# Disallow the process and all of its children to gain
# new privileges through execve().
NoNewPrivileges=true

# Use a new /dev namespace only populated with API pseudo devices
# such as /dev/null, /dev/zero and /dev/random.
PrivateDevices=true

# Deny the creation of writable and executable memory mappings.
MemoryDenyWriteExecute=true

[Install]
WantedBy=multi-user.target

```

Also seems blockbook and backend are running:

```
root@blockbook-btc:~# systemctl status blockbook-litecoin.service 
● blockbook-litecoin.service - Blockbook daemon (Litecoin)
   Loaded: loaded (/lib/systemd/system/blockbook-litecoin.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2022-02-09 06:53:01 UTC; 1s ago
 Main PID: 9928 (blockbook)
    Tasks: 23 (limit: 4915)
   Memory: 127.5M
   CGroup: /system.slice/blockbook-litecoin.service
           └─9928 /opt/coins/blockbook/litecoin/bin/blockbook -blockchaincfg=/opt/coins/blockbook/litecoin/config/blockchaincfg.json -datadir=/opt/coins/data/litecoin/blockbook/db -sync -in

Feb 09 06:53:01 blockbook-btc systemd[1]: Started Blockbook daemon (Litecoin).

root@blockbook-btc:~# systemctl status backend-litecoin.service 
● backend-litecoin.service - Litecoin backend daemon
   Loaded: loaded (/lib/systemd/system/backend-litecoin.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2022-02-09 06:46:12 UTC; 7min ago
  Process: 692 ExecStart=/opt/coins/nodes/litecoin/bin/litecoind -datadir=/opt/coins/data/litecoin/backend -conf=/opt/coins/nodes/litecoin/litecoin.conf -pid=/run/litecoin/litecoin.pid (cod
 Main PID: 728 (litecoind)
    Tasks: 17 (limit: 4915)
   Memory: 2.0G
   CGroup: /system.slice/backend-litecoin.service
           └─728 /opt/coins/nodes/litecoin/bin/litecoind -datadir=/opt/coins/data/litecoin/backend -conf=/opt/coins/nodes/litecoin/litecoin.conf -pid=/run/litecoin/litecoin.pid

Feb 09 06:46:12 blockbook-btc systemd[1]: Starting Litecoin backend daemon...

```

so where is the problem ?
