### ISSUE TITLE
new REST API call for getting raw block data

### ISSUE THREAD

**Issue by prusnak** [trezor/blockbook#736]
Currently we have only API for getting the parsed block data:

https://btc1.trezor.io/api/block/00000000000000000007970079f61055742fb2ccda61ed507aa4f93caa2a3799

But we'd like to have a new REST API call for getting the RAW block data.

For example: https://btc1.trezor.io/api/rawblock/00000000000000000007970079f61055742fb2ccda61ed507aa4f93caa2a3799

**Comment by martinboehm** [comment]
Done and released to prodution.
