### ISSUE TITLE
Bitcoin SV Blockbook stuck synchronizing at block 686010

### ISSUE THREAD

**Issue by samholmes** [trezor/blockbook#739]
<img width="1249" alt="Screen Shot 2022-03-08 at 09 36 13" src="https://user-images.githubusercontent.com/517469/157293931-a42d934b-3190-4568-a24d-0697b6cca945.png">

I don't know where else to reach out for support to uncover why the blockbook server stopped synchronizing for Bitcoin SV, so I'm creating this issue here for support.

The server is running on a Debian 10 x64 DigitalOcean droplet with 64GB of memory and 200 GB disk storage and a 9.77 TB attached volume.

The BSV node is synchronized on the P2P network with little no hiccups. I had to start the server using `-workers=1` flag to disable bulk-insert (if I recall correctly). This caused it to synchronize up to this point, but now it's stuck at this block height for 1-2 weeks.

Looking at the blockbook.WARNING log file I found:

```
E0308 17:47:04.962507    3204 blockbook.go:294] resyncIndex Corruption: block checksum mismatch: stored = 3979886353, computed = 2268415448  in /opt/coins/data/bcashsv/blockbook/db/175458.sst offset 8349424 size 32683
```

**Comment by martinboehm** [comment]
Hi, sorry we do not operate Bitcoin SV Blockbook, I do not know the reason for the error. However from the error message it looks like some data corruption of the RocksDB file. Maybe you run out of disk space or there was some attached storage issue?

**Comment by samholmes** [comment]
@martinboehm Thanks for the reply. The attached storage is 11TB and only 3.5TB is used (35%):

```
$ df -H
Filesystem      Size  Used Avail Use% Mounted on
udev             34G     0   34G   0% /dev
tmpfs           6.8G  202M  6.6G   3% /run
/dev/vda1       212G  9.5G  194G   5% /
tmpfs            34G     0   34G   0% /dev/shm
tmpfs           5.3M     0  5.3M   0% /run/lock
tmpfs            34G     0   34G   0% /sys/fs/cgroup
/dev/sda         11T  3.5T  6.8T  35% /datadrive
tmpfs           6.8G     0  6.8G   0% /run/user/0
```

This rules out a disk storage capacity issue. So, it could be corruption or some other issue. How would I remove the corrupted data in order to kick the Blockbook processing back into motion without starting from scratch; is this possible?

**Comment by samholmes** [comment]
I'm not familiar with a "block checksum", so perhaps this is a worthwhile point to expand upon. I'm aware that addresses contain checksums, but I don't recall a checksum in the block header (or some other part of the block data). Perhaps the checksum comes from the p2p network merely for validating the block header is not malformed, but I don't see why this would be needed. Are there tools available for reading the RocksDB dataset in order to pry open what could be going wrong?

**Comment by martinboehm** [comment]
Hi, as far as I understand the message, it looks like some RocksDB issue. You can try to repair the database using `-repair` flag and if it does not help, you will have to delete the DB and reindex it from start.

**Comment by samholmes** [comment]
@martinboehm What's the full command to run including the `--repair` arg?

**Comment by martinboehm** [comment]
You have to specify at least `-datadir` in addition to `-repair`. However, you can use the same command line parameters you use for the synced run of Blockbook and add the `-repair` parameter, it takes the precedence over `-sync`.
