### ISSUE TITLE
Use Blockbook with Bitcoin Core Full Node backend on separate server?

### ISSUE THREAD

**Issue by HannahVernon** [trezor/blockbook#742]
Is there a way to run Blockbook such that it consumes blocks from a separate server running Bitcoin Core?   I neither want nor need the Bitcoin Backend service to run on my Blockbook server.

I modified `/opt/coins/blockbook/bitcoin/config/blockchaincfg.json` to point the `rpc_url` at the Bitcoin Core machine, which is fully sync'd and has been running reliably for several years.   I also pointed the `message_queue_binding` setting at the `zmqpubrawblock` port on my Bitcoin Core node.

However, whenever I restart my Blockbook server, `systemctl status backend-bitcoin` shows `Active: active (running)`, and sure enough its consuming memory and downloading the blockchain.  I tried `systemctl disable backend-bitcoin` which claims to have deleted the `.service` file, however restarting the `blockbook-bitcoin` service results in it recreating the systemd service file and starting up the backend again.

Perhaps there are other options I need to configure in the `blockchaincfg.json` file?

**Comment by HannahVernon** [comment]
so I removed `/usr/lib/systemd/system/backend-bitcoin.service`, ran `systemctl daemon-reload`, and now am able to `systemctl start blockbook-bitcoin` without the `backend-bitcoin` service starting.

**Comment by martinboehm** [comment]
Great to hear that you were able to resolve the issue. When we split the backend and Blockbook services, we use the same approach.
