### ISSUE TITLE
Sending consecutive transactions

### ISSUE THREAD

**Issue by irishungndt** [trezor/blockbook#743]
I want to send a series of consecutive transactions using testnet.

Currently, base on background transaction can't be sent if there are any unconfirm transaction exist, is this right ?
if no, please help to correct
if yes, I refer to api.md and foud that api Get address (field unconfirmedTxs = 0 mean that there is no unconfirm transaction exist) may be fit, but even if there is no unconfirm transaction exist, when I try  to send a transaction immedidately, I get error "Undefine".

 Coul you please show me any doc or guide to do this ?

**Comment by martinboehm** [comment]
Hi, you can send transactions based on unconfirmed transactions. Blockbook does not have any guide on how to compose and sign transactions, you have to check the documentation of the blockchain you want to use.
