### ISSUE TITLE
http: TLS handshake error from x.x.x.x: EOF conncting Trezor Suite to Blockbook

### ISSUE THREAD

**Issue by HannahVernon** [trezor/blockbook#745]
Blockbook 0.3.6 is fully synchronized with my Bitcoin Core 22.0.0 backend yet when I configure Trezor Suite 22.3.2 to point at it, the suite won't connect.  Looking at the logs in `coins/blockbook/bitcoin/logs/blockbook.INFO`  I see the following error:

`server.go:3159] http: TLS handshake error from x.x.x.x:1431: EOF`

My Blockbook server is using a valid SSL certificate issued by Let's Encrypt.  When I point my browser at it via https://my.blockbook.server:9030 I see the following json response:

```
{
    "blockbook": {
        "coin": "Bitcoin",
        "host": "tbb",
        "version": "0.3.6",
        "gitCommit": "05baef7",
        "buildTime": "2022-03-21T22:42:32+00:00",
        "syncMode": true,
        "initialSync": false,
        "inSync": true,
        "bestHeight": 729578,
        "lastBlockTime": "2022-03-29T11:27:14.599556761-05:00",
        "inSyncMempool": true,
        "lastMempoolTime": "2022-03-29T11:41:20.558645586-05:00",
        "mempoolSize": 2580,
        "decimals": 8,
        "dbSize": 348380619019,
        "dbColumns": [
            {
                "name": "default",
                "version": 5,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "height",
                "version": 5,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "addresses",
                "version": 5,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "blockTxs",
                "version": 5,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "transactions",
                "version": 5,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "fiatRates",
                "version": 5,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "addressBalance",
                "version": 5,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "txAddresses",
                "version": 5,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            }
        ],
        "about": "Blockbook - blockchain indexer for Trezor wallet https://trezor.io/. Do not use for any other purpose."
    },
    "backend": {
        "chain": "main",
        "blocks": 729581,
        "headers": 729581,
        "bestBlockHash": "0000000000000000000666be7b0be9100b20359f6baaf6fa65d0652493a63400",
        "difficulty": "27452707696466.39",
        "sizeOnDisk": 452287069052,
        "version": "220000",
        "subversion": "/Satoshi:22.0.0/",
        "protocolVersion": "70016"
    }
}
```

That looks reasonable to me, although I'm not exactly sure if there should be more than zero rows reported in the `dbColumns` node.

Here's a screenshot from my browser:

![image](https://user-images.githubusercontent.com/6086769/160663178-4a05b168-7d44-4cb0-a674-7e40c80d8f8b.png)

Trezor Suite shows the following error in the coin configuration for Bitcoin:

> Not connected to the backend. Try reconnecting the device. Also, check your internet connection or the URL of your custom backend.

I'm assuming this is an issue related to TLS, but I just don't know what the actual error is.

**Comment by HannahVernon** [comment]
If this is not the correct place to ask about connectivity between Trezor Suite and Blockbook, can someone guide me to the correct place?

**Comment by martinboehm** [comment]
Hi, I think you are using a wrong port. 9030 is the internal interface, used primarily for Prometheus metrics, try the port 9130.

**Comment by HannahVernon** [comment]
> Hi, I think you are using a wrong port. 9030 is the internal interface, used primarily for Prometheus metrics, try the port 9130.

It's the same result connecting to either 9030 or 9130.

**Comment by martinboehm** [comment]
In that case it looks like a problem with your certificate. Are you using web or desktop version of the Suite? If you connect to your Blockbook using the web browser, do you have to confirm the certificate? Try to use the web version of the Suite in the same web browser to see if it connects. This way I am able to use the Suite even with self signed certificates. Unfortunately, I am not sure if the same procedure is possible to do in the desktop version.

**Comment by HannahVernon** [comment]
As it says in my post, I have a fully trusted Let's Encrypt cert - the browser screenshot shows the cert is valid.  I'm using the Desktop Trezor Suite as shown in the other screenshot.

**Comment by martinboehm** [comment]
Please try it with the web version too, so that we can narrow the problem.

**Comment by HannahVernon** [comment]
Do you mean I should download the Trezor github web wallet from https://github.com/trezor/trezor-wallet and build that and try it?  The last time I did that, it uses trezord.exe which can only connect to either https://*.trezor.io or https://localhost.  If I point my browser at https://suite.trezor.io and try to connect to my blockbook from there I get the same result as documented above.  For clarity though, my Blockbook is not accessible from the Internet - it's only visible on my internal network.  And also, I'm not attempting to connect to it from the same machine where blockbook is installed.  Blockbook is installed on a VM running at 192.168.0.1 and my client is connecting to it from 192.168.0.2, a wholly separate machine on my network.  (those IPs are just an example to make it clear).

**Comment by HannahVernon** [comment]
If the Trezor suite has the same limitation (i.e. can only connect to Trezor's own Blockbook servers at https://*.trezor.io or https://localhost) then it's completely useless to me.  I know that https://wiki.trezor.io/User_manual:Running_a_local_instance_of_Trezor_Wallet_backend_(Blockbook) shows localhost in step #12, but it's not clearly documented if that's the *only* option.

**Comment by martinboehm** [comment]
There is no such limitation, you can certainly connect Suite to your own Blockbook. And for this test, you do not have to build anything, just use https://suite.trezor.io/web/.

**Comment by HannahVernon** [comment]
so I tried pointing the https://suite.trezor.io/web/ bitcoin coin settings at https://tbb.mvct.com:9130 and https://tbb.mvct.com:9030 - I have internal DNS servers so that does resolve correctly to the blockbook machine, as verified by using both an ssh client to login to the machine, and my web browser being pointed at https://tbb.mvct.com:9030 or https://tbb.mvct.com:9130 .  

This is what I see from `systemctl status blockbook-bitcoin` via ssh:

```shell
root@tbb:/opt/coins# systemctl status blockbook-bitcoin
● blockbook-bitcoin.service - Blockbook daemon (Bitcoin)
     Loaded: loaded (/lib/systemd/system/blockbook-bitcoin.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-03-29 11:26:31 CDT; 6 days ago
   Main PID: 6925 (blockbook)
      Tasks: 42 (limit: 38421)
     Memory: 29.9G
        CPU: 10h 31min 18.741s
     CGroup: /system.slice/blockbook-bitcoin.service
             └─6925 /opt/coins/blockbook/bitcoin/bin/blockbook -blockchaincfg=/opt/coins/blockbook/bitcoin/config/blockchaincfg.json -datadir=/opt/coins/data/bitcoin/blockbook/db -s>

Apr 04 11:56:28 tbb blockbook[6925]: I0404 11:56:28.949617    6925 server.go:3159] http: TLS handshake error from 192.168.0.152:2226: EOF
Apr 04 11:56:48 tbb blockbook[6925]: I0404 11:56:48.982241    6925 server.go:3159] http: TLS handshake error from 192.168.0.152:2236: EOF
Apr 04 11:57:09 tbb blockbook[6925]: I0404 11:57:09.196629    6925 server.go:3159] http: TLS handshake error from 192.168.0.152:2248: EOF
Apr 04 11:57:30 tbb blockbook[6925]: I0404 11:57:30.201013    6925 server.go:3159] http: TLS handshake error from 192.168.0.152:2258: EOF
Apr 04 11:57:51 tbb blockbook[6925]: I0404 11:57:51.199798    6925 server.go:3159] http: TLS handshake error from 192.168.0.152:2277: EOF
Apr 04 11:58:12 tbb blockbook[6925]: I0404 11:58:12.205566    6925 server.go:3159] http: TLS handshake error from 192.168.0.152:2299: EOF
Apr 04 11:58:33 tbb blockbook[6925]: I0404 11:58:33.190404    6925 server.go:3159] http: TLS handshake error from 192.168.0.152:2312: EOF
Apr 04 11:58:54 tbb blockbook[6925]: I0404 11:58:54.202971    6925 server.go:3159] http: TLS handshake error from 192.168.0.152:2327: EOF
Apr 04 11:59:15 tbb blockbook[6925]: I0404 11:59:15.193013    6925 server.go:3159] http: TLS handshake error from 192.168.0.152:2346: EOF
Apr 04 11:59:36 tbb blockbook[6925]: I0404 11:59:36.200988    6925 server.go:3159] http: TLS handshake error from 192.168.0.152:2359: EOF
```

This is a screenshot from the web wallet:

![image](https://user-images.githubusercontent.com/6086769/161595124-bb0a6b9c-48f5-4634-9946-19140ffb9b06.png)

**Comment by HannahVernon** [comment]
FYI, this is what Firefox shows when I look at the Let's Encrypt cert:

![image](https://user-images.githubusercontent.com/6086769/161596368-467393d5-fca5-488d-848c-00f73d7051e4.png)

**Comment by HannahVernon** [comment]
I get the same results from https://suite.trezor.io/web/settings/coins using Google Chrome.

**Comment by martinboehm** [comment]
In that case, I think it is a networking issue as it should be possible to use a custom Blockbook (and I verified it while responding to this issue). I found for example this https://stackoverflow.com/questions/34823724/golang-tls-handshake-error.
Btw do not specify the servers ending with the port 9030, they are not correct.

**Comment by HannahVernon** [comment]
ok, so just to follow-up, when LetsEncrypt provides certificates through certbot, it provides 4 files:

```shell
cert.pem
chain.pem
fullchain.pem
privkey.pem
```

I was under the impression that `cert.pem` would be the certificate to provide to Blockbook, however, pointing the symlink for `coins/blockbook/bitcoin/cert/blockbook.crt` at the `fullchain.pem` allows it to work correctly.  I suppose the `fullchain.pem` contains the necessary intermediate certificates for the full chain of trust, whereas the `cert.pem` is strictly the one certificate issued to tbb.mvct.com.

Anyway, it works.  Which is sweet.  Thanks!

**Comment by HannahVernon** [comment]
FYI @martinboehm  - I cleaned up my responses to make this more helpful to future visitors that may have the same problem.

**Comment by martinboehm** [comment]
Thank you!
