### ISSUE TITLE
Bitcoin SV stuck sync on the blocks with high number of transaction and outputs

### ISSUE THREAD

**Issue by alexandrtrue** [trezor/blockbook#752]
Hi guys, i know u not supported a Bitcoin SV, but maybe u help us with this issues
Blockbook stuck sync or processing that so long time on the blocks below
https://blockchair.com/ru/bitcoin-sv/block/733755
https://blockchair.com/ru/bitcoin-sv/block/734096
block number 734096 have a millions transactions and outputs blockbook synced that piece around three days

Our developers don't have a much experience on "go", but they said if some one can change function of parsing txs in each block, and make it multiple threads like a parsing function as for example with blocks during the initial synchronization. It would help us.

**Comment by martinboehm** [comment]
I would estimate that on a reasonable server with enough memory, the import of a block with 1 million transactions takes less than 5 minutes. It corresponds to an initial import of 1000 blocks with 1000 transactions each (for example in Bitcoin). Anything significantly over that probably means that your computer is out of memory and swapping heavily. The memory consumption of processing such large blocks can be significant.
I do not think that higher parallelization will solve the problem.

**Comment by alexandrtrue** [comment]
I have a AMD's Ryzen™ 9 5950X. With its Zen 3 architecture, 16 cores and 32 threads. Together with 128 GB of DDR4 ECC RAM and two 3.84 TB datacenter NVMe SSDs
Setting for book is "workers=1",  because when set is more we catch out of memory error and that is currupted database.
That is why i ask about hight parralization when block parsing.

**Comment by martinboehm** [comment]
This looks like a powerful enough machine. 
I think this PR https://github.com/trezor/blockbook/pull/427 (which was not merged) could be interesting for you . Merge it to your codebase and try to run Blockbook with it. It should give you probably better results than some parallelization.
