### ISSUE TITLE
Unable to locate package backend-bitcoin_22.0-satoshilabs-1_amd64.deb

### ISSUE THREAD

**Issue by masanaka** [trezor/blockbook#756]
I'm trying to install a local backend according to the manual https://wiki.trezor.io/User_manual:Running_a_local_instance_of_Trezor_Wallet_backend_(Blockbook).
When I run step 5 "apt install <package name>", it said "Unable to locate package backend-bitcoin_22.0-satoshilabs-1_amd64.deb", but I command "ls" on build folder, it does have backend-bitcoin_22.0-satoshilabs-1_amd64.deb.
Did I misunderstand something? Can somebody help me?

**Comment by wakiyamap** [comment]
I remember trying to follow the wiki street a long time ago and failing.
`apt install <package name> (e.g., apt install backend-bitcoin_0.16.1-satoshilabs1_amd64.deb)`
↓
`apt install ./<package name> (e.g., apt install ./backend-bitcoin_0.16.1-satoshilabs1_amd64.deb)`

This worked fine

**Comment by masanaka** [comment]
@martinboehm 
Yes, in the build directory. According to Mr. wakiyamap's comment, I succeeded with './backend-bitcoin_0.16.1-satoshilabs1_amd64.deb'.
Thank you for your help.

@wakiyamap 
Thank you, thanks a lot. I succeeded the installation with your help.
