### ISSUE TITLE
Missing log files

### ISSUE THREAD

**Issue by samholmes** [trezor/blockbook#759]
I removed the logs dir `rm -rf /opt/coins/blockbook/bcashsv/logs` and then restarted the blockbook service `systemctl restart blockbook-bcashsv.service` and now the logs are not reappearing. I tried `systemctl stop blockbook-bcashsv.service && systemctl start blockbook-bcashsv.service`, but this still did not result in the logs appearing. Why doesn't blockbook's logger recover from deleted logs?

**Comment by martinboehm** [comment]
Does the folder `/opt/coins/blockbook/bcashsv/logs` exist? Blockbook will not create it.

**Comment by samholmes** [comment]
@martinboehm Yes it does exist. I should have mentioned that I created the directory after deleting it.

**Comment by samholmes** [comment]
```
root@blockbook-bsv-sfo3:/opt/coins/blockbook/bcashsv# ls -al
total 28
drwxr-xr-x 7 root root 4096 Apr 21 23:43 .
drwxr-xr-x 3 root root 4096 Mar  8 17:42 ..
drwxr-xr-x 2 root root 4096 Mar  8 17:43 bin
drwxr-xr-x 2 root root 4096 Mar  8 17:43 cert
drwxr-xr-x 2 root root 4096 Mar  8 17:44 config
drwxr-xr-x 2 root root 4096 Apr 21 23:43 logs
drwxr-xr-x 5 root root 4096 Feb 14 20:00 static
root@blockbook-bsv-sfo3:/opt/coins/blockbook/bcashsv# pwd
/opt/coins/blockbook/bcashsv
```

**Comment by martinboehm** [comment]
Is your Blockbook running under root?

**Comment by samholmes** [comment]
Looks like it's running under `blockbook-bcashsv`. I `chmod`'d the logs dir and that fixed it.
