### ISSUE TITLE
Support Zcash NU5 upgrade

### ISSUE THREAD

**Issue by brucexiu** [trezor/blockbook#762]
NU5 will introduce [ZIP225](https://zips.z.cash/zip-0225) and [ZIP316](https://zips.z.cash/zip-0316). Have a plan to support it soon?

**Comment by martinboehm** [comment]
Hi, I assume it will work fine as transactions are parsed by the backend. At least it seems to work fine in the Zcash testnet.

**Comment by brucexiu** [comment]
> Hi, I assume it will work fine as transactions are parsed by the backend. At least it seems to work fine in the Zcash testnet.

OK, thanks.
