### ISSUE TITLE
LTC mainnet, stuck at 2265984

### ISSUE THREAD

**Issue by amurde** [trezor/blockbook#770]
Hello,
today blockbook stuck at LTC mainnet with error:

blockbook.go:294] resyncIndex 2265984 418dcad142cd2d94da49f4d0025efa73adde9d7ac971392852f7bce7c716d11c: MsgTx.BtcDecode: witness tx but flag byte is 08

 Blockbook: {Version:v0.3.6 GitCommit:5f8cf45-dirty

**Comment by nrazavi70** [comment]
Same here, Im stuck since yesterday at the same block.

**Comment by martinboehm** [comment]
Hi, we are aware of the problem and working on a fix.

**Comment by martinboehm** [comment]
The problem is that (from the https://github.com/litecoin-project/litecoin/releases/tag/v0.21.2) `MWEB fields added to BlockIndex, and block serialization format has changed.`. 
That means that Litecoin is no longer compatible with the Bitcoin wire protocol Blockbook uses to deserialize block data. 
We will have to switch to the method used for example in Zcash, which gets parsed data from the blockchain instead of parsing them in Blockbook.

**Comment by martinboehm** [comment]
@amurde, @nrazavi70 could you please verify that the fix works for you?

**Comment by nrazavi70** [comment]
@martinboehm Would you please elaborate what exactly I have to do?

**Comment by atomlab** [comment]
@martinboehm I have built blockbook from commit [a22bf37](https://github.com/trezor/blockbook/commit/a22bf37788ed578722e4cfa95e9996433a81caa2)

Faced error when launch

```
I0521 15:03:53.833896       1 worker.go:1845] GetSystemInfo, 9.258139ms
I0521 15:03:53.834406       1 internal.go:65] internal server: starting to listen on http://:9034
I0521 15:03:53.837580       1 rocksdb.go:287] rocksdb: close
E0521 15:03:53.871894       1 blockbook.go:119] main recovered from panic: template: txdetail.html:16: function "isOwnAddresses" not defined
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/opt/go/src/runtime/debug/stack.go:16 +0x19
main.main.func1()
	/go/src/github.com/trezor/blockbook/blockbook.go:120 +0x85
panic({0x10c7660, 0xc000610960})
	/opt/go/src/runtime/panic.go:1038 +0x215
html/template.Must(...)
	/opt/go/src/html/template/template.go:374
github.com/trezor/blockbook/server.(*PublicServer).parseTemplates.func1({0xc0010695f0, 0x3, 0x3})
	/go/src/github.com/trezor/blockbook/server/public.go:466 +0xa5
github.com/trezor/blockbook/server.(*PublicServer).parseTemplates(0xc00054f450)
	/go/src/github.com/trezor/blockbook/server/public.go:509 +0x7ae
github.com/trezor/blockbook/server.NewPublicServer({0x7ffdd0859d60, 0x5}, {0x0, 0x0}, 0xc00059a000, {0x1414760, 0xc00000f218}, {0x14004d8, 0xc00000f230}, 0xc0001d1180, ...)
	/go/src/github.com/trezor/blockbook/server/public.go:104 +0x4fd
main.startPublicServer()
	/go/src/github.com/trezor/blockbook/blockbook.go:410 +0x11d
main.mainWithExitCode()
	/go/src/github.com/trezor/blockbook/blockbook.go:282 +0x1205
main.main()
	/go/src/github.com/trezor/blockbook/blockbook.go:124 +0x3b
```

**Comment by Lojzicek** [comment]
dobry den prosim vAS MUZETE MI POMOCT JELIKOZ NEVIM VUBEC CO MAM DELAT ABYCH MNEL VSE V PORADKU DEKUJI

**Comment by martinboehm** [comment]
@atomlab I do not think that your issue is caused by Lightning. You are probably running a clone of Blockbook and are not properly synced with upstream.

**Comment by amurde** [comment]
Hi @martinboehm,

> @amurde, @nrazavi70 could you please verify that the fix works for you?

So we build new blockbook from the master. Deleted blockbook data and now syncing it from the scratch.
I will update the state when there will be some results. Probably tomorrow during the day.

So far, thank you for the support!

**Comment by nrazavi70** [comment]
@martinboehm By building blockbook from master and syncing from the beginning the issue is resolved. 
Thanks for your help

**Comment by amurde** [comment]
Hi @martinboehm !
We was unhappy with our storage, so i will start over.

What is recommended Rocksdb version right now? 
Can i use https://github.com/facebook/rocksdb/releases/tag/v7.2.2 ?

Our last build was using RocksDB v6.22.1.

**Comment by amurde** [comment]
Hello @martinboehm,

we finally synchronized blockbook using the version from "master".
So far everything is fine.
Thank you for your help!
