### ISSUE TITLE
Question ERC721/ERC1155?

### ISSUE THREAD

**Issue by Droppix** [trezor/blockbook#781]
Hi,

I see you completed ERC721/ERC1155  on https://github.com/trezor/blockbook/commits/eth_update, is the version installable (in beta)? If yes, I suppose that the database (rockdb) must be completely rebuilt?

Thanks

**Comment by martinboehm** [comment]
Hi, it must be completely rebuilt. 
In addition to that if you want to index internal transactions, you have to run Ethereum in the archive mode, which makes the backend DB huge and the initial sync (both backend and Blockbook) is very slow.
We are currently testing it and completing some additional tasks.
You can try it certainly but not yet tested enough at this moment.

**Comment by Droppix** [comment]
Hi,

Thanks for your response.

I will try to do some tests.

**Comment by Droppix** [comment]
Hello Martin,

Just a small question, to be sure: 
The synchronization of the backend in "full" mode (on mainnet) is very long, I'm at 6194643 blocks out of 15044622 (that is 40% after 3 days, on server 32GB - SSD 1TB), do we really have to wait for 70% filling to launch the "blockbook" service, or can we do it at any time?

Thanks

**Comment by martinboehm** [comment]
You can start syncing any time, however without the internal transactions the sync is very fast (you would need archive mode for internal transactions) and you will not loose much time by starting Blockbook when the backend is fully synced.
