### ISSUE TITLE
Errors while getting transactions from Litecoin testnet 

### ISSUE THREAD

**Issue by APshenkin** [trezor/blockbook#782]
Blockbook builded from https://github.com/trezor/blockbook/commit/2002bd23524b93fb755b8b4f50aee3e7bc906279

For several addresses if request `/api/address/some address?details=txs` we receive `500 Internal Server Error - {"error":"Internal server error"}`

In blockbook we can see in logs
```
E0629 21:49:47.352041       6 public.go:314] apiAddress error: GetTransaction 981b4aba9ebae949cbe88aa0b5d6e0aa0876e7e81db5ecc85c78ed1b5503ffe2: Transaction '981b4aba9ebae949cbe88aa0b5d6e0aa0876e7e81db5ecc85c78ed1b5503ffe2' not found (proto: bchain.ProtoTransaction: illegal tag 0 (wire type 0))
E0629 21:49:47.353052       6 public.go:314] apiAddress error: GetTransaction 458605fb0b3db168490762919a25aa0b01bb69177598662fa1c9ac547fd97c3e: Transaction '458605fb0b3db168490762919a25aa0b01bb69177598662fa1c9ac547fd97c3e' not found (proto: bchain.ProtoTransaction: illegal tag 0 (wire type 0))
E0629 21:49:54.471326       6 public.go:314] apiAddress error: GetTransaction 3b143ad07264706cc7ca80b1370df7f6b4d72d09c34f2df55029910ed24c907e: Transaction '3b143ad07264706cc7ca80b1370df7f6b4d72d09c34f2df55029910ed24c907e' not found (proto: bchain.ProtoTransaction: illegal tag 0 (wire type 0))
```

If try to open such transactions in blockbook we can see
```
Transaction '3b143ad07264706cc7ca80b1370df7f6b4d72d09c34f2df55029910ed24c907e' not found (proto: bchain.ProtoTransaction: illegal tag 0 (wire type 0))
```

BTW if open block page with this transaction this transaction exist
![image](https://user-images.githubusercontent.com/14344430/176552308-e9567c00-ed5e-4702-950a-5989af92aefa.png)

**Comment by martinboehm** [comment]
Hi, sorry, probably too late but did you clean the transaction cache as described in this commit message https://github.com/trezor/blockbook/commit/1e684933712107fd8e66b23539161443e3a19b04?
