### ISSUE TITLE
The blockbook is constantly lagging behind for dogecoin by 5-30 blocks

### ISSUE THREAD

**Issue by savmaingit** [trezor/blockbook#784]
Hello!

The blockbook is constantly lagging behind for dogecoin by 5-30 blocks.
We noticed a constant blockbook lag of 5-30 at different times. The dogecoin version has been updated to the latest v1.14.6. The notebook version has been updated to the latest commit 2002bd23524b93fb755b8b4f50aee3e7bc906279.
There are no errors in the logs.

for example:
4316081  dogecoin
4316069  blockbook

Please help)

**Comment by stepollo2** [comment]
Did you try to use -resyncindexperiod param?

**Comment by martinboehm** [comment]
We run `-resyncindexperiod=30011`, i.e. checking the backend every 30 seconds in our servers. @savmaingit check your params, please.

**Comment by savmaingit** [comment]
Hello!
I'll try and back)
Thank you!

**Comment by savmaingit** [comment]
What will be the default value if this parameter is not specified?

**Comment by martinboehm** [comment]
The default values are 15 minutes for resync index and 1 minute to check mempool.
