### ISSUE TITLE
Litecoin MWEB transaction error: MsgTx.BtcDecode: witness tx but flag byte is 08

### ISSUE THREAD

**Issue by sime** [trezor/blockbook#791]
Viewing an MWEB transaction on ltc1.trezor.io throws the following error:

```
MsgTx.BtcDecode: witness tx but flag byte is 08
```
Blockbook: https://ltc1.trezor.io/tx/b2d8bda5926ecfc92ea3f06a574611fbb42a1d5355f702895cc460c2fe56121f

**Comment by sime** [comment]
Trezor Suite reference: https://github.com/trezor/trezor-suite/issues/5882#issuecomment-1200273414

**Comment by martinboehm** [comment]
Seems that Blockbook has an issue with this type of address, will have to investigate.

**Comment by martinboehm** [comment]
@sime The issue was already fixed by this commit 1e68493, unfortunately not released to production. I will talk to admins to release the right version.

**Comment by sime** [comment]
@martinboehm Thanks! Will keep an eye out for an release.

**Comment by martinboehm** [comment]
@sime It is released to production.
