### ISSUE TITLE
Is there any plan for supporting ETH merge?

### ISSUE THREAD

**Issue by liuyangc3** [trezor/blockbook#798]
Merge will happend at 15 Sep

**Comment by Dehumanizer77** [comment]
Definitely.
Some discussion also over at https://github.com/trezor/blockbook/issues/794

**Comment by liuyangc3** [comment]
> Definitely. Some discussion also over at #794

Thank you

**Comment by liuyangc3** [comment]
Hi @martinboehm May I ask can the `eth_update` branch be used in production environment? any plan to merge to master? Thank you

**Comment by martinboehm** [comment]
@liuyangc3 hi, I would recommend to use the branch https://github.com/trezor/blockbook/tree/v0.4.0 to build and install the execution and consensus layer backends. The merge is fully supported, we already run the consensus layer connected to execution for our Ethereum prod servers.

Blockbook does not require any update for the Merge, it remains connected to the execution layer. You could build a new version of Blockbook from this branch too (it has a lot of ETH related features) but be warned that the database from the previous version of Blockbook is not compatible and must be synced again. Plus, while it is almost ready to be released, it still needs some finishing touches. For example Blockbook version is still not bumped to v0.4.0, it will report itself as v0.3.6.
