### ISSUE TITLE
Unable to sync FIRO

### ISSUE THREAD

**Issue by chadouming** [trezor/blockbook#801]
Hi, I'm trying to sync FIRO and I am getting this error:

E0904 02:53:06.492684 1203166 blockbook.go:294] resyncIndex 117564 f3646083759fd81d6cddeb6667deddde6745c77346ac81d58f282162763bc8aa: unexpected EOF

I've tried re-sync'ing the backend twice already, it seems to be ok as I can query it.

I also launched blockbook using -workers=1 but it still give me that error

I've got roughly 40GB free so I doubt that it the issue.

Using ubuntu 22.04 AMD64

I have sync'ed Vertcoin, Raptoreum and Ravencoin succesfully on the same system.

**Comment by chadouming** [comment]
I tried again and this is the error I get when I do an initial sync. It'll run for a while in that loop then just crash.

Sep 05 19:21:16 cvm blockbook[338773]: E0905 19:21:16.373364  338773 sync.go:339] getBlockWorker 5 connect block error 117569 6ace1945aa0a7cb6141b2b0359f395eb04f915e3a4d8204b591442ce822e4013: unexpected EOF. Retrying...
Sep 05 19:21:16 cvm blockbook[338773]: E0905 19:21:16.373584  338773 sync.go:339] getBlockWorker 2 connect block error 117566 f80b1b3e5268ee7d6c6cce08c0d8b6ab856bd731a6e96224d96d0836c097f107: unexpected EOF. Retrying...
Sep 05 19:21:16 cvm blockbook[338773]: E0905 19:21:16.373717  338773 sync.go:339] getBlockWorker 3 connect block error 117568 6b387f9a3709f2735b3aa9e1322761ae6f787176032357a5cb06a7d66a53f131: unexpected EOF. Retrying...
Sep 05 19:21:16 cvm blockbook[338773]: E0905 19:21:16.373761  338773 sync.go:339] getBlockWorker 4 connect block error 117570 ffcefe5b2a90e9aca4f0343dccae7ca8267cc91271018c69c3c8158454e9f07a: unexpected EOF. Retrying...
Sep 05 19:21:16 cvm blockbook[338773]: E0905 19:21:16.373868  338773 sync.go:339] getBlockWorker 6 connect block error 117564 f3646083759fd81d6cddeb6667deddde6745c77346ac81d58f282162763bc8aa: unexpected EOF. Retrying...
Sep 05 19:21:16 cvm blockbook[338773]: E0905 19:21:16.373964  338773 sync.go:339] getBlockWorker 7 connect block error 117571 0893770c886b3a3d90d1133eb6dbb0a9a22da52cdd506e9292adeefc194894a4: unexpected EOF. Retrying...
Sep 05 19:21:16 cvm blockbook[338773]: E0905 19:21:16.744015  338773 sync.go:339] getBlockWorker 0 connect block error 117565 0bd66f10fc0ff4ad7b608c70b66536f6485292b269c4da1367d801a5a168c7ff: unexpected EOF. Retrying...
Sep 05 19:21:16 cvm blockbook[338773]: E0905 19:21:16.874102  338773 sync.go:339] getBlockWorker 1 connect block error 117567 768b59e199e1c3cb436c2078d8a252ba82b0320fe3065e7fac6bf8f34938fa33: unexpected EOF. Retrying...

**Comment by martinboehm** [comment]
We do not run Firo Blockbook, I cannot give you any advice, unfortunately. I would recommend you to contact the package maintainer specified here https://github.com/trezor/blockbook/blob/ab0e7cd33b351a448e41e28363967b523d159abb/configs/coins/firo.json or some other people that are contributing to the Firo implementation (see in the file history).

**Comment by chadouming** [comment]
> We do not run Firo Blockbook, I cannot give you any advice, unfortunately. I would recommend you to contact the package maintainer specified here https://github.com/trezor/blockbook/blob/ab0e7cd33b351a448e41e28363967b523d159abb/configs/coins/firo.json or some other people that are contributing to the Firo implementation (see in the file history).

Ok, fixed on my side. Thanks for the notice !
