### ISSUE TITLE
Requests with many transactions, addresses and balances.

### ISSUE THREAD

**Issue by KurlatovD** [trezor/blockbook#808]
Hello!
Are there any plans for adding an ability to send few addresses in a moment to https://${chain}.getblock.io/blockbook/api/v2/address/${address}
and receive info for all of them at once? Instead of making cycle with requests for each one.

And the same question about transactions endpoint
https://${chain}.getblock.io/blockbook/api/v2/tx/${txid}

**Comment by martinboehm** [comment]
Sorry, at this moment not.
