### ISSUE TITLE
Spent/received transactions type.

### ISSUE THREAD

**Issue by KurlatovD** [trezor/blockbook#809]
Hello!
Are there any ways to detect type of transaction - spent of received?

For example,
https://btc.getblock.io/blockbook/api/v1/tx/518a6b9ffc65c02000c424db52d5fde3487300a6a1662f9f3f45549d05695c09?api_key=${api_key}

There is "spent" field in "vout". And in [0] it is "false", in [1] it is "true".
So I broke my brain trying to understand the method witch will allow me to clearly detect the type of transaction)

**Comment by martinboehm** [comment]
I do not understand the question. The `spent` field means if the output was already spent by some other transaction.
