### ISSUE TITLE
Compatibilty with Bcoin

### ISSUE THREAD

**Issue by NoamResnick** [trezor/blockbook#81]
Will Blockbook be compatible with Bcoin in the future? I took a look and found that Bcoin's rpc calls have a different format than Bitcoind (different parameters and result formatting). Is there an easy way to make Blockbook send the correct rpc requests to Bcoin?

**Comment by martinboehm** [comment]
We do not plan to add Bcoin compatibility. However, it would not be hard to implement Bcoin as an additional rpc connector.
