### ISSUE TITLE
BTC/ testBTC stopped syncing

### ISSUE THREAD

**Issue by TheTrunk** [trezor/blockbook#810]
Both Bitcoin and Testnet Bitcoin seemed to contain a transaction in a block that prevents further blockbook syncing.
```
resyncIndex 757922 0000000000000000000400a35a007e223a7fb8a622dc7b5aa5eaace6824291fb: readScript: script witness item is larger than the max allowed size [count 33970, max 11000]
```

**Comment by wakiyamap** [comment]
```
Oct 10 09:44:39 blockbook[28613]: E1010 09:44:39.894816   28613 blockbook.go:544] syncIndexLoop readScript: script witness item is larger than the max allowed size [count 33970, max 11000]
Oct 10 09:44:39 blockbook[28613]: /go/src/github.com/trezor/blockbook/bchain/coins/btc/bitcoinrpc.go:597: 757922 0000000000000000000400a35a007e223a7fb8a622dc7b5aa5eaace6824291fb
```
I'm getting the same error on mine too.

**Comment by TheTrunk** [comment]
I see it is being worked on and perhaps that even fixes it.
Will rebuild our solutions asap
https://github.com/martinboehm/btcd/commit/987348babe731d73e0b70dda98da70f50ab1c541

**Comment by qinheqing** [comment]
> I see it is being worked on and perhaps that even fixes it. Will rebuild our solutions asap [martinboehm/btcd@987348b](https://github.com/martinboehm/btcd/commit/987348babe731d73e0b70dda98da70f50ab1c541)

Was it resolved successfully? We also encountered the same problem

**Comment by TheTrunk** [comment]
> > I see it is being worked on and perhaps that even fixes it. Will rebuild our solutions asap [martinboehm/btcd@987348b](https://github.com/martinboehm/btcd/commit/987348babe731d73e0b70dda98da70f50ab1c541)
> 
> Was it resolved successfully? We also encountered the same problem

For us the rebuilt blockbook is crashing after couple of seconds with no information in the logs on both mainnet and testnet

**Comment by wakiyamap** [comment]
It worked fine with v0.4.0.
https://mainnet-explorer.wakiyamap.dev/

**Comment by martinboehm** [comment]
And now the fix is in the `master` too.

**Comment by atomlab** [comment]
Blockbook built from master. But I faced the error. Blockbook crashed. I use the same db without resync from btc node.  How to fix it? 

```
blockbook.go:138] Blockbook: {Version:devel GitCommit:6e0a045 BuildTime:2022-10-10T07:31:18+00:00 GoVersion:go1.17.1 OSArch:linux/amd64}, debug mode true

bitcoinrpc.go:136] rpc: block chain mainnet

mempool_bitcoin_type.go:56] mempool: starting with 8*2 sync workers

rocksdb.go:148] rocksdb: opening /data/db, required data version 5, cache size 0, max open files 16384
```

**Comment by kaladinlight** [comment]
It appears there is another issue with a transaction over the size limit as of this morning that will require another btcd update:
```
blockbook.go:294] resyncIndex 761249 000000000000000000070742427fa10ec3c66d006160155a704d9f56d090a3ea: MsgTx.BtcDecode: to │
│ o many witness items to fit into max message size [count 500003, max 500000]
```

**Comment by kaladinlight** [comment]
Nevermind, it looks like you are already on it: https://github.com/martinboehm/btcd/commit/408689e15809b9f8100a860ab293cb8800c1807f

**Comment by martinboehm** [comment]
There was a similar issue with an additional btcd constant being too small. Already fixed.
