### ISSUE TITLE
fiat_rates.go error 429

### ISSUE THREAD

**Issue by HannahVernon** [trezor/blockbook#814]
After downloading the latest blockbook code, and resyncing the entire BTC chain, the Trezor Suite app is showing price data from several years ago, and I've noticed the INFO log is showing the following message:

`fiat_rates.go:195] syncHistorical GetData error: Invalid response status: 429 Too Many Requests`

Is there something I should do?

**Comment by martinboehm** [comment]
Coingecko is rate limiting its API. When Blockbook encounters this error, it will try again later. Or, you can disable the download of fiat rates completely by removing the `fiat_rates` entry from config.

**Comment by HannahVernon** [comment]
Thanks Martin, does it use an exponential backoff algorithm for retrying `syncHistorical.GetData()` - I'm just wondering how long to expect it to take until blockbook has current fiat rates.
