### ISSUE TITLE
Block sync stopped at height 761249

### ISSUE THREAD

**Issue by qinheqing** [trezor/blockbook#820]
E1101 19:02:56.977401   16520 blockbook.go:512] syncIndexLoop MsgTx.BtcDecode: too many witness items to fit into max message size [count 500003, max 500000]
/go/src/github.com/trezor/blockbook/bchain/coins/btc/bitcoinrpc.go:598: 761249 000000000000000000070742427fa10ec3c66d006160155a704d9f56d090a3ea

**Comment by qinheqing** [comment]
I noticed that there is an update on the master branch, is it done to fix this problem?

@martinboehm

**Comment by Dehumanizer77** [comment]
It was supposed to fix the problem but apparently it isn't fixed yet, Martin is working on a fix right now.

**Comment by Dehumanizer77** [comment]
Now fixed in master and will be fixed in v0.4.0 branch in a few moments.

**Comment by qinheqing** [comment]
E1101 20:16:03.348928   25149 blockbook.go:187] internalState: DB version 6 of column 'default' does not match the required version 5. DB is not compatible. 

I still get an error when I restart after the update.

**Comment by bb4L** [comment]
fyi latest build has failed on master

**Comment by Dehumanizer77** [comment]
@qinheqing you have blockbook built from branch v0.4.0, you will need to build it from that branch, as there is already a newer rocksDB in the v0.4.0 branch

@bb4L try to do "make clean-all" before build. I have built it from master an hour ago and it's already working on our servers.

**Comment by martinboehm** [comment]
@qinheqing if you built/run your Blockbook from the branch v0.4.0, you have to stay in this branch, the database is not backwards compatible.

**Comment by alexjavabraz** [comment]
v0.4.0 already have this fix?

**Comment by Dehumanizer77** [comment]
> v0.4.0 already have this fix?

yes
