### ISSUE TITLE
BlockBook not syncing

### ISSUE THREAD

**Issue by alexjavabraz** [trezor/blockbook#821]
Blockbook is not syncing with the message `too many witness`

**Blockbook**

Coin | Bitcoin
-- | --
Version / Commit / Build | 0.3.6 / / 2022-10-17T14:02:55+00:00
Synchronized | false
Last Block | 761248
Last Block Update | Tue, 01 Nov 2022 10:38:04 UTC
Mempool in Sync | true
Last Mempool Update | Tue, 01 Nov 2022 16:26:12 UTC
Transactions in Mempool | 10393
Size On Disk | 383727757590

**Backend**

Chain | main
-- | --
Version | 230000
Subversion | /Satoshi:23.0.0/
Protocol Version | 70016
Last Block | 761285
Difficulty | 36835682546787.98
Size On Disk | 494825235681

**Comment by screw** [comment]
see #820
