### ISSUE TITLE
Eth blockbook is freezed

### ISSUE THREAD

**Issue by ah2020b** [trezor/blockbook#826]
Hi

There are several blockbooks installed that has freezed on the block 

15537393

https://eth1.bcfn.ca/blocks

Why?

**Comment by martinboehm** [comment]
Hi, Ethereum underwent the Merge event https://ethereum.org/en/upgrades/merge/ in that block. You have to install the consensus layer and the execution layer (a newer version of geth). You can get the build configs for that in the branch [v0.4.0](https://github.com/trezor/blockbook/tree/v0.4.0) in this repo, https://github.com/trezor/blockbook/blob/v0.4.0/configs/coins/ethereum.json and https://github.com/trezor/blockbook/blob/v0.4.0/configs/coins/ethereum_consensus.json, if you are using our Docker build. 

You could use also a new version (soon to be released) of Blockbook from this branch, however be aware that the database is not compatible and requires new full sync with the backend.

**Comment by ah2020b** [comment]
Hi

Thank you for your help.

We are using the v0.4.0 (it is a new fresh installation happened 15 days a go)

Do I need to do this? "You have to install the consensus layer and the execution layer (a newer version of geth)"

If yes, how to do this?

Tnks

**Comment by Dehumanizer77** [comment]
Yes, you need to be running consensus layer for eth backend to work after the merge.
To build it: `make deb-backend-ethereum-consensus`, then install and start it. Note that it will take a while until consensus backend will synchronize (currently the consensus db is 120 GB or so IIRC).

**Comment by ah2020b** [comment]
> You have to install the consensus layer and the execution layer (a newer version of geth).

What is the forecast for this new version?

**Comment by ah2020b** [comment]
This is not our blockbook

https://eth1.bcfn.ca/blocks

sorry for confusion.

Our blockbook is showed on the above image. I can't share the url here to protect it.

**Comment by martinboehm** [comment]
Please check the ethereum documentation about the consensus and execution layer. You can use the above mentioned configs to build and install them but I would recommend you to get some understanding of how it works.
