### ISSUE TITLE
[Question] What is  `197 rocksdb.go:1854] db: Column addressBalance: rows 875000000, key bytes 21311551568, value bytes 8407928885, in progress...`

### ISSUE THREAD

**Issue by screw** [trezor/blockbook#828]
I see the following message a lot in our log.
` 197 rocksdb.go:1854] db: Column addressBalance: rows 875000000, key bytes 21311551568, value bytes 8407928885, in progress...`

What does it mean?

I found in the code that it is calculating column size, I am interested for what purpose or if it indicates anything (inconsistency, performance degradation, ...).

Thank you.

**Comment by martinboehm** [comment]
It is just for statistical reasons. You can see the results in the internal web interface. However, we decided to disable this functionality by default in the upcoming version as it is not essential.
