### ISSUE TITLE
Get address - Non-contract filter.

### ISSUE THREAD

**Issue by Rey092** [trezor/blockbook#829]
https://github.com/trezor/blockbook/blob/master/docs/api.md#get-address

''' contract: return only transactions which affect specified contract (applicable only to coins which support contracts) '''

It will be usefull to add option to get only non-contract ransactions. Like with contract=none or something.

**Comment by martinboehm** [comment]
Actually, there is kind of undocumented feature, if you specify the parameter `filter=0`, it will return only non-contract transactions. We may add some more friendly alias for that and document it in the future.

**Comment by Rey092** [comment]
Looks like its does not work with details. Only https://eth3.trezor.io/api/v2/address/0x6bF7a492282Af792CA85EeB2dc72f3d5B687a5e9?filter=0 works for me. Fetch every transaction with a different request? Why do I even need explorer with indexed db then !?

**Comment by martinboehm** [comment]
It works fine for me: for example the tx `0xfff78b007fa72b75de902e90fc9eab85594d6648f5bfcc6a526e4880849eb9f2` is in this the unfiltered request https://eth3.trezor.io/api/v2/address/0x6bF7a492282Af792CA85EeB2dc72f3d5B687a5e9?details=txs and not in the filtered  https://eth3.trezor.io/api/v2/address/0x6bF7a492282Af792CA85EeB2dc72f3d5B687a5e9?filter=0. 

Be aware that if the address appears in the non token part, it is filtered in even if the tx is a token transfer.

**Comment by Pyxic** [comment]
https://eth3.trezor.io/api/v2/address/0x6bF7a492282Af792CA85EeB2dc72f3d5B687a5e9?filter=0 it works only for received transactions. "filter=0" doesn`t work for sent transactions. For example, the tx 0x284ff5ea69133ee86faea5c58630bb32b4bafad1e623f8db9b744b97f0ac7bd6 is in this the filtered request https://eth3.trezor.io/api/v2/address/0x6bF7a492282Af792CA85EeB2dc72f3d5B687a5e9?filter=0.

**Comment by Pyxic** [comment]
> 



> It works fine for me: for example the tx `0xfff78b007fa72b75de902e90fc9eab85594d6648f5bfcc6a526e4880849eb9f2` is in this the unfiltered request https://eth3.trezor.io/api/v2/address/0x6bF7a492282Af792CA85EeB2dc72f3d5B687a5e9?details=txs and not in the filtered https://eth3.trezor.io/api/v2/address/0x6bF7a492282Af792CA85EeB2dc72f3d5B687a5e9?filter=0.
> 
> Be aware that if the address appears in the non token part, it is filtered in even if the tx is a token transfer.


https://eth3.trezor.io/api/v2/address/0x6bF7a492282Af792CA85EeB2dc72f3d5B687a5e9?filter=0 it works only for received transactions. "filter=0" doesn`t work for sent transactions. For example, the tx 0x284ff5ea69133ee86faea5c58630bb32b4bafad1e623f8db9b744b97f0ac7bd6 is in this the filtered request https://eth3.trezor.io/api/v2/address/0x6bF7a492282Af792CA85EeB2dc72f3d5B687a5e9?filter=0.

**Comment by Balashov152** [comment]
Hi there. I try to use `filter=0` but it broke pagination. Maybe there are other ways?
