### ISSUE TITLE
UTXO Indexing?

### ISSUE THREAD

**Issue by moeadham** [trezor/blockbook#83]
Hello,

Any thoughts of a UTXO index, or the ability to query available UTXO's similar to how insight used to provide?

ex. https://btc.faa.st/insight-api/addr/1Hz96kJKF2HLPGY15JWLB5m9qGNxvt8tHJ/utxo

Thanks

**Comment by martinboehm** [comment]
Yes, we are probably going to implement it. We are now in the process of defining what API functions we need.

**Comment by moeadham** [comment]
Awesome @martinboehm; can we help?

**Comment by martinboehm** [comment]
I prioritised the development of the feature as we need it too. It is not 100% equal to the insight implementation but should be close enough. 

Usage:
`https://<server>/api/utxo/<address>[?confirmed=true]`. The optional `confirmed` parameter controls whether to include mempool transactions and remove confirmed transactions spent by mempool transactions. Example output:
```
[{"txid":"ca3d7f2a3b27bb1b92519320ae3ba5e5878747b93e102d62027e193d5cbddb78","vout":1,"amount":"10.31372305","satoshis":1031372305,"confirmations":0},
{"txid":"71500fb9f6a26e908f61938dc9ce9f6dbdc48b2ca753c1a2b3e333c1710b7e8a","vout":5,"amount":"676.99952628","satoshis":67699952628,"height":550197,"confirmations":1},
{"txid":"0d31ebbefa8f2a3bba60bd0a630c31f98ea96599df8a67a6eff7912fd5196f67","vout":7,"amount":"22.06042224","satoshis":2206042224,"height":550196,"confirmations":2},
{"txid":"b8aa3cf8ce0192114bbae7e765338b081594d2475bec5aede8b797bcbf36e68c","vout":15,"amount":"16.46825802","satoshis":1646825802,"height":550195,"confirmations":3}]
```
Mempool transactions have confirmations==0 and do not have height value.

_The feature is not yet released to our production servers, you have to build your own version._
