### ISSUE TITLE
What is message_queue_binding? 

### ISSUE THREAD

**Issue by lessless** [trezor/blockbook#830]
Hi,

Thank you for open-sourcing the project. I hope it'll make my life easier :) 

Would someone please help me to understand what `message_queue_binding` is about? I briefly searched through the repo but couldn't find much with just a quick scan :) 

I have a couple of lines related to the `zmq` in my bitcoind config: 

```
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333
```

Does it have to do something with that?

**Comment by martinboehm** [comment]
This defines the connection to the ZeroMQ provided by the Bitcoind to notify Blockbook about new blocks and transactions in mempool.
