### ISSUE TITLE
Run Blockbook with existing Node and exotic Blockchain

### ISSUE THREAD

**Issue by Frazer-dl** [trezor/blockbook#844]
According to this [question ](https://github.com/trezor/blockbook/issues/831)

I have bitcoin fork that is not in your blockchains list (its the same as Ltc just have different PUBKEY, SCRIPT ADDRESS, SECRET_KEY params) also I have node, I want to install blockbook on different machine and use your api.

So do I need just skip this step:
```
5. Go to blockbook/build directory and run:
> apt install ./<package name> (e.g., apt install ./backend-bitcoin_0.16.1-satoshilabs1_amd64.deb)
```
Then as [Dehumanizer77](https://github.com/Dehumanizer77) noticed:
```
Yes, it's possible, you need to edit /opt/coins/blockbook/bitcoin/config/blockchaincfg.json 
and replace 127.0.0.1 with the server of your choice.
```
So how do I need to add params to new configs/coins/anycoin.json if this build step skipped ?
If this node have auth, is it enough to add credentials to `/opt/coins/blockbook/bitcoin/config/blockchaincfg.json`  ?

I'm thinking that is pretty simple but I'm confused, can you please guide me ?

**Comment by Dehumanizer77** [comment]
There are two packages. The first one is backend, which, when you build it, creates a backend package (the actual bitcoin daemon running on the machine) and second one is blockbook, which is the frontend used for communication with the Trezor Suite. With Ethereum there is also consensus backend, but that's just ETH specific. 

Now, it depends on how different is your fork from the original Bitcoin. If it's just a simple copy with no changes, you can build and install bitcoin blockbook (make deb-blockbook-bitcoin creates the deb package for you) and then you can change the blockchaincfg.json as per my previous reply. You don't have to build the backend package, as you already have it running. 
But if the fork is different, then it might not work (or there will be unexpected behaviour, the blockchain will not be indexed correctly etc.) and there would be changes in the blockbook code needed.

**Comment by Frazer-dl** [comment]
Will try, thanks [Dehumanizer77](https://github.com/Dehumanizer77)
