### ISSUE TITLE
[Question]Build on ubuntu:bionic failed on debian/rules clean

### ISSUE THREAD

**Issue by Frazer-dl** [trezor/blockbook#845]
Build error while using make `deb-blockbook-bitcoin` . I didn't find solution [here ](https://github.com/trezor/blockbook/issues/45),
in `build/docker/bin/dockerfile` I changed `FROM ubuntu:bionic`

```
Package files for bitcoin generated to build/pkg-defs
dpkg-buildpackage: info: source package blockbook
dpkg-buildpackage: info: source version 0.3.6
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by IT <it@satoshilabs.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build blockbook
 debian/rules clean
: No such file or directory
'.  Stop. No rule to make target '
dpkg-buildpackage: error: debian/rules clean subprocess returned exit status 2
```

**Comment by Frazer-dl** [comment]
[Dehumanizer77](https://github.com/Dehumanizer77) if you have any suggestions it might help :)

**Comment by Dehumanizer77** [comment]
Oh, you are trying to start it with bitcoin.json, that's not correct. The json for running the blockbook is blockchaincfg.json and is generated during package build.

**Comment by Frazer-dl** [comment]
> Oh, you are trying to start it with bitcoin.json, that's not correct. The json for running the blockbook is blockchaincfg.json and is generated during package build.

Damn :) Thanks! Could you please send me generated one and path where it should be?

**Comment by Frazer-dl** [comment]
> Oh, you are trying to start it with bitcoin.json, that's not correct. The json for running the blockbook is blockchaincfg.json and is generated during package build.

Ok, I build it by myself, thanks!
