### ISSUE TITLE
blockbook (bitcoin) using 100% of a core *after* synchronizing

### ISSUE THREAD

**Issue by squiggles-the-penguin** [trezor/blockbook#846]
Hi, my blockbook is fully synced up and functioning (I can use it successfully with trezor desktop and browse it on the web), but the CPU is consistently riding around 100% for the blockbook process.

This did not happen before the November 1 btcd patch. I'm running 95eb699ccbaeef0ec6d8fd0486de3445b8405e8a.

I'm running on a google cloud vm with 4 cores and 32G RAM, Debian 11.

Prior to Nov 1, my typical CPU usage was like [this](https://ibb.co/qyJgpDX), and now it looks like [this](https://ibb.co/s5Nr4pW).

All I see in the blockbook logs is stuff like this:

```
I1209 14:38:27.813083    5297 mempool_bitcoin_type.go:203] mempool: resync finished in 39.552445ms, 3843 transactions in mempool
I1209 14:38:29.264333    5297 mempool_bitcoin_type.go:203] mempool: resync finished in 17.715773ms, 3845 transactions in mempool
I1209 14:38:30.741184    5297 mempool_bitcoin_type.go:203] mempool: resync finished in 16.259939ms, 3847 transactions in mempool
I1209 14:38:32.786242    5297 mempool_bitcoin_type.go:203] mempool: resync finished in 22.909271ms, 3852 transactions in mempool
I1209 14:38:36.509721    5297 mempool_bitcoin_type.go:203] mempool: resync finished in 22.338681ms, 3867 transactions in mempool
I1209 14:38:37.533070    5297 mempool_bitcoin_type.go:203] mempool: resync finished in 13.535015ms, 3867 transactions in mempool
I1209 14:38:38.665998    5297 xpub.go:97] Evicted 0 items from xpub cache, cache size 5
I1209 14:38:39.993350    5297 mempool_bitcoin_type.go:203] mempool: resync finished in 26.62914ms, 3874 transactions in mempool
I1209 14:38:41.146007    5297 mempool_bitcoin_type.go:203] mempool: resync finished in 19.129392ms, 3875 transactions in mempool
I1209 14:38:43.292091    5297 mempool_bitcoin_type.go:203] mempool: resync finished in 168.758547ms, 3879 transactions in mempool
```

**Comment by martinboehm** [comment]
Hi. We do not observe higher CPU usage with the newest commits of Blockbook and the BTCD patch should not cause any higher CPU utilisation as it contains only a constant change. The log you posted also does not show anything unusual.

**Comment by squiggles-the-penguin** [comment]
Thanks, I'm not sure what the cause was but it's back to normal now. I'll close the issue.
