### ISSUE TITLE
Latest dash update 404 on binary_url

### ISSUE THREAD

**Issue by mattmartinez** [trezor/blockbook#857]
from commit 18d76c9753eadd14a2f89c7f2908ae98ab4a30ec

The release file doesn't seem to exist:

https://github.com/dashpay/dash/releases/download/v18.2.0/dashcore-18.2.0-x86_64-linux-gnu.tar.gz

**Comment by mattmartinez** [comment]
> @Belkaar Recently released Dash Core v18.2.0 cannot sync past block 1800330 on mainnet. Developers are investigating, please do not upgrade to this version for now! Anyone who has already upgraded can revert to v18.1.0 and sync will complete without any further action.

Just noticed this over in the Dash issues -> https://github.com/dashpay/dash/issues/5140

**Comment by martinboehm** [comment]
Resolved by this commit https://github.com/trezor/blockbook/commit/0ebbf16f18551f1c73b59bec6cfcbbdc96ec47e8, which upgrades Dash to v18.2.1
