### ISSUE TITLE
 initializeMempool zmq4 was installed with ZeroMQ version 4.3.4, but the application links with version 4.3.5

### ISSUE THREAD

**Issue by Wbsba** [trezor/blockbook#862]
Debian GNU/Linux 11 
 systemctl start blockbook-bitcoin-regtest.service
E0113 12:06:14.432570   40213 bitcoinrpc.go:168] mq: zmq4 was installed with ZeroMQ version 4.3.4, but the application links with version 4.3.5
E0113 12:06:14.434278   40213 blockbook.go:306] initializeMempool zmq4 was installed with ZeroMQ version 4.3.4, but the application links with version 4.3.5
I0113 12:06:14.434688   40213 rocksdb.go:287] rocksdb: close

**Comment by Sotatek-AnhDao** [comment]
@Wbsba how did you resolve this error?

**Comment by timurgum** [comment]
Similar question? how did you solve this problem

**Comment by Sotatek-AnhDao** [comment]
> Similar question? how did you solve this problem

Maybe I can help, in this error message: 
"... zmq4 was installed with ZeroMQ version 4.3.4, but the application links with version 4.3.5"

It say your ZeroMQ installed version is 4.3.5, you just need downgrade to 4.3.4 to compatible with the version zmq4 used.

**Comment by vivekteega** [comment]
I am getting this error too

Did anyone manage to resolve this? How did you do it?

**Comment by martin-key** [comment]
still happening
