### ISSUE TITLE
Litecoin api and sync error

### ISSUE THREAD

**Issue by peterpan0708** [trezor/blockbook#875]
script witness item is larger than the max allowed size [count 151453, max 11000].

Our service is currently down,  may be need to update the btcd version?
@martinboehm 
<img width="1692" alt="image" src="https://user-images.githubusercontent.com/36805830/220037047-64f43c80-cfa4-4c57-a8e4-b75e959f3040.png">

**Comment by martinboehm** [comment]
Hi, what version do you run? Our Blockbook was able to index this block. And yes, I would assume that upgrade of btcd will help, the issue looks similar to issues with BTC Taproot transactions which were resolved in the btcd library.

**Comment by peterpan0708** [comment]
> Hi, what version do you run? Our Blockbook was able to index this block. And yes, I would assume that upgrade of btcd will help, the issue looks similar to issues with BTC Taproot transactions which were resolved in the btcd library.

OK thanks, i will try that.  By the way, i can't  how to shutdown the project gracefully? i try kill {PID}, but the program doesn't quit for a long time, will kill -9 {PID} may cause the data error(i met that before so i have to resync the blockchain data from the beginning)

**Comment by martinboehm** [comment]
If Blockbook was not in bulk (initial) sync mode, you can kill it without any issue.
