### ISSUE TITLE
[zcash] 5.4.0 hard fork on March 26th

### ISSUE THREAD

**Issue by bn-nr-rpc** [trezor/blockbook#876]
See https://github.com/zcash/zcash/releases/tag/v5.4.0
> After upgrading to v5.4.0, `zcashd` will start tracking changes in transparent pool value and chain supply from the height at which it is restarted. Block heights prior to this will not have any information recorded. To track changes from genesis, and thus monitor the total transparent pool size and chain supply, you would need to restart your node with the `-reindex` option.

Hi trezor team, may I know is there any plan to support this version? thanks

**Comment by Dehumanizer77** [comment]
We are waiting for 5.4.2 to be published as a binary tarball at https://zcash.readthedocs.io/en/latest/rtd_pages/install_binary_tarball.html , after that we'll bump the version. Hopefully at some point this week.

**Comment by bn-nr-rpc** [comment]
> We are waiting for 5.4.2 to be published as a binary tarball at https://zcash.readthedocs.io/en/latest/rtd_pages/install_binary_tarball.html , after that we'll bump the version. Hopefully at some point this week.

Hi @Dehumanizer77 I don't think next release will be 5.4.2, it's 5.5.0 actually, see the zcash [milestones page]( https://github.com/zcash/zcash/milestones?state=openhttps://github.com/zcash/zcash/milestones?state=open) for details. So are you saying the blockbook zcash will skip 5.4.x and jump into to 5.5.0 directly?

**Comment by Dehumanizer77** [comment]
That's strange, I was almost sure that I have seen an announcement of 5.4.2 on newreleases.io, but it's not there now. In that case, I'll prepare a pull request for 5.4.1
