### ISSUE TITLE
Ethereum sync very long time

### ISSUE THREAD

**Issue by Pyxic** [trezor/blockbook#879]
Now the blockbook has parsed approximately 1,220,000 blocks. The synchronization speed has dropped significantly and is 1-2 blocks per second. The server has dynamically expandable RAM, but the blockbook did not use more than 17 GB. What could be the problem with such a long synchronization?
![image](https://user-images.githubusercontent.com/30235155/221855398-7a3d26f3-140a-478d-8f22-2f61571b4533.png)
![image](https://user-images.githubusercontent.com/30235155/221855517-db41ec18-cd35-488d-931f-6923982694b9.png)

**Comment by martinboehm** [comment]
If you are syncing Ethereum archive version, it is very slow and takes months to sync. The bottleneck is in fetching debug info from the backend and I am not aware of any way how to speed it up.
