### ISSUE TITLE
blst error - question about development build

### ISSUE THREAD

**Issue by GBBx** [trezor/blockbook#882]
Hi,

I've been using Blockbook for a long time.
I used to be able to follow the [manual build](https://github.com/trezor/blockbook/blob/master/docs/build.md#manual-build) steps but I run into an issue since I updated to 0.4.0.
When I start blockbook I get this error message:
```
Caught SIGILL in blst_cgo_init, consult <blst>/bindings/go/README.md.
```

I found this [discussion](https://github.com/community/community/discussions/43153). They suggest to add `CGO_CFLAGS=-O -D__BLST_PORTABLE__`, so I tried this:
```
CFLAGS="-fPIC" CXXFLAGS="-fPIC" CGO_CFLAGS="-O -D__BLST_PORTABLE__" make release
```
when building rocksdb but it did not solve the issue.

I also tried to set `CGO_CFLAGS="-O -D__BLST_PORTABLE__" make release` globally but that failed, too.

I undertand `blst` is a dependency of a dependency of Blockbook but are you maybe familiar with this problem?

**Comment by martinboehm** [comment]
Hi, sorry, we do not have this build problem, neither in the manual build nor in the docker build. What version of go are you using? As it seems related to Avalanche dependencies, maybe @kaladinlight will have an idea.

**Comment by GBBx** [comment]
Hi @martinboehm , thanks for coming back to me.
I try to build it with Go 1.19.2 on Ubuntu 20.04 (I also tried Ubuntu 22.04 - didn't help).

**Comment by kaladinlight** [comment]
I have an i7 and not seeing any issues. I am using `go version go1.20 linux/amd64` locally if you want to give that a try? There was an additional `-lzstd` LDFLAG added with v0.4.0 as well just to make sure everything matches up.

**Comment by GBBx** [comment]
hi @kaladinlight, thanks for the hints.
I've tried:
- setting CGO_CFLAGS_ALLOW
- setting CGO_CFLAGS before building rocksdb, and after
- updating kernel
- adding -lzstd
All failed.

@XK4MiLX's finding is interesting. There are some comments about architecture at the [bottom of the page](https://github.com/supranational/blst/tree/master/bindings/go#build) I haven't tried yet.

**Comment by kaladinlight** [comment]
I would be curious about building and testing the blst go binding directly to reduce the scope of the problem a bit. https://github.com/supranational/blst/tree/master/bindings/go. According to https://github.com/supranational/blst#platform-and-language-compatibility it appears to have extensive os/platform support...

```bash
[~/github/blst] (master) $ ./build.sh 
+ cc -O2 -fno-builtin -fPIC -Wall -Wextra -Werror -D__ADX__ -mno-avx -c ./src/server.c
+ cc -O2 -fno-builtin -fPIC -Wall -Wextra -Werror -D__ADX__ -mno-avx -c ./build/assembly.S
+ ar rc libblst.a assembly.o server.o
[~/github/blst] (master) $ cd bindings/go/
[~/github/blst/bindings/go] (master) $ go build
[~/github/blst/bindings/go] (master) $ go test
PASS
ok  	github.com/supranational/blst/bindings/go	2.037s
```

worst case scenario if we are unable to resolve this issue and it appears common enough, I can rip out the `api/info` module and manually replace it to rid the blst indirect dependency

**Comment by kaladinlight** [comment]
Nice find! Confirmation on my side that my cpu does have ADX support.

**Comment by martinboehm** [comment]
@kaladinlight 
> worst case scenario if we are unable to resolve this issue and it appears common enough, I can rip out the `api/info` module and manually replace it to rid the blst indirect dependency

Wouldn't it be beneficial in any case? I would like to get rid of unnecessary dependencies. While I can build Blockbook on my Mac, I get these warnings, which also come from Avalanche dependencies

```
github.com/rjeczalik/notify
cgo-gcc-prolog:217:2: warning: 'FSEventStreamScheduleWithRunLoop' is deprecated: first deprecated in macOS 13.0 - Use FSEventStreamSetDispatchQueue instead. [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:1138:1: note: 'FSEventStreamScheduleWithRunLoop' has been explicitly marked deprecated here
# github.com/trezor/blockbook
ld: warning: could not create compact unwind for _blst_sha256_block_data_order: does not use RBP or RSP based frame
```

`github.com/ava-labs/avalanchego/api/info` is used for `GetNodeVersion` only, if I understand it right. Could we call the `info.getNodeVersion` directly using Ethereum RPC?

**Comment by kaladinlight** [comment]
Yeah that would be the idea @martinboehm. I will go ahead and get a PR up to resolve this and reduce the dependency tree.

**Comment by martinboehm** [comment]
@GBBx @XK4MiLX Hi, can you try to build and run a new version from master? Thanks to a quick change by @kaladinlight, we were able to remove the blst dependecies from Blockbook.

**Comment by XK4MiLX** [comment]
i tested that fix on my fork working fine :) but yes i can test master ;) on sec
