### ISSUE TITLE
Binance Smart Chain issue while synching

### ISSUE THREAD

**Issue by martin-key** [trezor/blockbook#888]
Hey! 

I've started a sync of the blockbook for BSC and I'm getting the following error:
`getBlockWorker 4 connect block error eth_getLogs blockNumber 0xf006c6: websocket: read limit exceeded. Retrying...`

Do you have any idea of a specific setup that I should execute in order to have that resolved?

Best regards,
MK.

**Comment by martinboehm** [comment]
Hi, yes, it is a known issue, see this: https://github.com/trezor/blockbook/pull/869#issuecomment-1458631796

**Comment by martin-key** [comment]
Ok, that makes perfect sense! Thanks!

One more thing - we are running the blockbook with a docker container and a run.sh file which is starting the instance with `exec ./blockbook`. If the sync is stuck at that message what is going to be the best way to stop the execution gracefully so we don't have to restart the sync process from zero? So far all the options that we have used in the past years were requiring us to start over again if we are stuck in initial sync.

**Comment by martinboehm** [comment]
Unfortunately, if sync breaks while doing initial synchronization in bulk mode, the DB is corrupted and you must start again from empty DB.

**Comment by martin-key** [comment]
@martinboehm if you have an idea how that could be prevented or how to do a graceful shutdown you may let me know and me and my team could potentially try to resolve that.

**Comment by martin-key** [comment]
I'm closing the ticket as the answer is available here - https://github.com/trezor/blockbook/pull/869#issuecomment-1458631796
