### ISSUE TITLE
Corruption: SST file is ahead of WALs in CF addressBalance

### ISSUE THREAD

**Issue by XK4MiLX** [trezor/blockbook#890]
Hi i have problem with blockbook in docker reproduct step:
( db directory is in bind mount outside docker layer => Persistent Storage )
- stop continer
- rm image
- pull new image
- start continer
in 6/10 cases i got error:
rocksDB: Corruption: SST file is ahead of WALs in CF addressBalance
any idea how fix it with no need of db clean ? something like "--rocksdb.wal-recovery-skip-corrupted true"

**Comment by martinboehm** [comment]
I would restore the db from a backup or resync the db.

**Comment by XK4MiLX** [comment]
i switched to RocksDB [v7.10.2] looks good still testing...
```
Bug Fixes
Fixed a bug in DB open/recovery from a compressed WAL that was caused due to incorrect handling of certain record fragments with the same offset within a WAL block.
 ```

**Comment by XK4MiLX** [comment]
i created script that after found "rocksDB: Corruption" in logs tiggering
 ./opt/blockbook/blockbook -repair -datadir=/root/blockbook-db
on old version hit "DB corrupted: Corruption: force_consistency_checks"
with new version db is fixed ;) and all working normal ;)

**Comment by martinboehm** [comment]
Thank you. Just to clarify, I have not seen this error in any Blockbook that we operate, the issue must be somehow specific to your setup. But it is good to know that the upgraded RocksDB resolves the issue.
