### ISSUE TITLE
Goerli sync issue after Shanghai upgrade

### ISSUE THREAD

**Issue by akme** [trezor/blockbook#891]
Blockbook stuck at block `8656122`

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/1006307/225230905-898d4848-96d3-4e10-afe5-7949538ad1d0.png">

In logs we see only
```
E0315 06:47:51.716213       1 sync.go:339] getBlockWorker 3 connect block error Block not found. Retrying...
```

**Comment by martinboehm** [comment]
Hi, this commit https://github.com/trezor/blockbook/commit/61cb657d78ed4de00edbd8fa6d745cac5710e16c fixes the issue. There are still some errors reported in the log but Blockbook is recovering from them and syncing. We will investigate the error logs further.

**Comment by martinboehm** [comment]
This commit e9134b04909b2e47eea081252cd4da6b6769d414 fixes the error logging, closing the issue.
