### ISSUE TITLE
Blockbook running servers

### ISSUE THREAD

**Issue by mgpnd** [trezor/blockbook#9]
Is there any ready-to-use blockbook server?
I'm trying to make requests to btc-bitcore1.trezor.io and btc-bitcore2.trezor.io but they always return `index` response.
According to code in https://github.com/trezor/blockbook/blob/master/server/https.go the next request should return unconfirmed transactions for given address: `https://btc-bitcore2.trezor.io/unconfirmedTransactions/3D9YzhPQ6xQRscNcRf9Nv9b78VLiv65s7L` but it (as any other request) returns only response from `index` method.

**Comment by martinboehm** [comment]
Sorry, blockbook is developed as backend for Trezor wallet only and will not support complete bitcore API. In addition to that, the implemented interfaces can change in future without notice. We discourage everybody from using it as general blockchain API.

**Comment by prusnak** [comment]
I was told that only API you can use from the backend server is the socket.io API.

**Comment by TJvrDev** [comment]
If I have an altcoin running blockbook on a server & wanted to communicate with it via REST, is that possible or would it only be possible via socket.io api?

**Comment by martinboehm** [comment]
Yes, see the [documentation](https://github.com/trezor/blockbook/blob/master/docs/api.md).

**Comment by artall64** [comment]
Thanks, a lot! I've just found exact list of ports here: https://github.com/trezor/blockbook/blob/master/docs/ports.md
