### ISSUE TITLE
 How can i configure my  blockbook server to use my public domain instead of the public ip?

### ISSUE THREAD

**Issue by NightCorpse** [trezor/blockbook#904]
I'm pointing the A record to my public ip server but I still can't make it so that I can open the explorer through the domain.

**Comment by vdovhanych** [comment]
You need to use a reverse proxy with a valid certificate for the domain. Or access the server with DNS record but with application port specified f.e `example.com:19121`. I suggest setting up a reverse proxy, though.

**Comment by NightCorpse** [comment]
i have a lets encrypt ssl certificate but im struggling to use on blockbook, also after reverse proxy with nginx im having bad gateway... someone know how to correct this?

**Comment by vdovhanych** [comment]
A quick google search and I found [this](https://gist.github.com/wakiyamap/15122fc22fdc4fda01cc34439824f7a0) Nginx configuration that you can use as your starting point.

**Comment by NightCorpse** [comment]
testing what you said, with public port i get bad gateway, with internal port, i get the json of the site, like this:

### {
    "blockbook": {
        "coin": "Dash",
        "host": "block",
        "version": "0.4.0",
        "gitCommit": "9c500e56-dirty",
        "buildTime": "2023-03-24T21:20:49+00:00",
        "syncMode": true,
        "initialSync": false,
        "inSync": true,
        "bestHeight": 1845617,
        "lastBlockTime": "2023-03-29T17:40:45.864305982Z",
        "inSyncMempool": true,
        "lastMempoolTime": "2023-03-29T17:44:26.581922831Z",
        "mempoolSize": 41,
        "decimals": 8,
        "dbSize": 28503602188,
        "hasFiatRates": true,
        "currentFiatRatesTime": "2023-03-29T09:00:11.258030358Z",
        "historicalFiatRatesTime": "2023-03-29T00:00:00Z",
        "dbColumns": [
            {
                "name": "default",
                "version": 6,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "height",
                "version": 6,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "addresses",
                "version": 6,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "blockTxs",
                "version": 6,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "transactions",
                "version": 6,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "fiatRates",
                "version": 6,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "addressBalance",
                "version": 6,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            },
            {
                "name": "txAddresses",
                "version": 6,
                "rows": 0,
                "keyBytes": 0,
                "valueBytes": 0,
                "updated": "0001-01-01T00:00:00Z"
            }
        ],
        "about": "Blockbook - blockchain indexer for Trezor Suite https://trezor.io/trezor-suite. Do not use for any other purpose."
    },
    "backend": {
        "chain": "main",
        "blocks": 1845617,
        "headers": 1845617,
        "bestBlockHash": "00000000000000077bdf979ca365ca4855f8e1f4b3d7f62a54260f68667ae0be",
        "difficulty": "139074787.904105",
        "sizeOnDisk": 33431511739,
        "version": "180202",
        "subversion": "/Dash Core:18.2.2/",
        "protocolVersion": "70224"
    }
}

**Comment by NightCorpse** [comment]
also trying to curl localling in the server using the public port get connection refused

**Comment by NightCorpse** [comment]
nvm i fixed the problem, it was a problem with the configuration of the public port (I included an address that I shouldn't), but I'm still having trouble putting my ssl certificate from lets encrypt in the blockbook (/opt/coins/blockbook/dash/cert)

I linked the certificate and the private key in .pem format with blockbook.crt and blockbook.key, after that the site does not open
