### ISSUE TITLE
How mush disk space I need for bsc full node?

### ISSUE THREAD

**Issue by Pyxic** [trezor/blockbook#912]
Will 4 TB be enough for me

**Comment by martinboehm** [comment]
It depends. Our bsc has this size at this moment:
```
478G	/data/blockbook/bsc_archive/blockbook
2.6T	/data/blockbook/bsc_archive/backend
3.1T	/data/blockbook/bsc_archive
```
It was created from the lastest public snapshot (geth-20230326.tar.lz4). We run it in archive mode (to be able to get the internal transactions from the latest blocks) and it grows very fast, I would say at least 1T in a month. If you run non-archive mode, it will not grow as fast and you will be able to run it for some time in 4TB but I would say it is kind of thight.

**Comment by Pyxic** [comment]
Thank you!
