### ISSUE TITLE
Does ETH version intentionally includes file type?

### ISSUE THREAD

**Issue by screw** [trezor/blockbook#918]
The last ETH version includes also filetype `tar.gz`. 
Is it intentional or just a typo? (it broke our less-than optimal pipeline :)).

https://github.com/trezor/blockbook/blob/2207bfc6c14c8be5d456c9ea46659ae5d91736af/configs/coins/ethereum.json#L25

**Comment by martinboehm** [comment]
@screw Thank you, it is a typo. Fixed by this commit https://github.com/trezor/blockbook/commit/1f10bd2bbcbecc77f775af43f39082f407549ffb?w=1. Strange enough the typo did not cause any issue for us.
