### ISSUE TITLE
/api/tx is missing locktime causing issues in some trezorlib dependencies

### ISSUE THREAD

**Issue by brianddk** [trezor/blockbook#92]
Added a PR https://github.com/trezor/python-trezor/pull/344 to assume `locktime:0` if none is provided.  This seems to break some trezorlib sign_tx apis for versions < 0.11.  Exposures may be limited to PAYTOADDRESS and `trezorctl`

Electrum does not seem to be effected.

**Comment by martinboehm** [comment]
Blockbook does return `locktime` provided it is not zero. Does it make sense to return `locktime` always or the fix of the test is enough?
