### ISSUE TITLE
Adopt sats standard to show amounts (for Bitcoin)

### ISSUE THREAD

**Issue by prusnak** [trezor/blockbook#924]
Currently we show amounts as this:

```
0.000 154 1 BTC
```

This is very confusing and unexpected.

I propose to show this instead:

```
0.00 015 410 BTC
```

this means two changes:
* group 0.AA BBB CCC instead of 0.AAA BBB CC
* always show trailing zeroes

To be clear, this is about Bitcoin and probably other coins that use 8 decimals. Not other coins which do not use 8 decimals.

**Comment by martinboehm** [comment]
Thank you. It is already in plan in this exact specification. It was already suggested to me by multiple people.

**Comment by martinboehm** [comment]
Done
