### ISSUE TITLE
Support querying balances / txs / utxos from xpub(ypub / zpub)

### ISSUE THREAD

**Issue by hewigovens** [trezor/blockbook#93]
Hi

Any ideas of support querying balances / txs / utxos from xpub( ypub / zpub)? I notice that trezor uses [fastxpub](https://github.com/trezor/hd-wallet/tree/master/fastxpub) to do account scanning locally, it may be faster on server side? 

Thanks

**Comment by martinboehm** [comment]
Sure, it is in the plan.

**Comment by martinboehm** [comment]
Implemented in v0.2.1

**Comment by hewigovens** [comment]
@martinboehm We're testing out the new xpub api, looks very good, great job. I wonder if there is an API to return all used addresses (tx > 0) for a xpub?

**Comment by martinboehm** [comment]
Hi, the API documentation is [here](https://github.com/trezor/blockbook/blob/master/docs/api.md#get-xpub). I hope it helps you.

**Comment by hewigovens** [comment]
Thanks for the documentation link, but I tried a few parameters, seems not working.
blockbook: 0.2.1 / efca04a
Dash Core:0.13.1

https://dash-rpc.binancechain.io/api/v2/xpub/xpub6CZTNN87eLJ7zzQRtvXZkPyguw4HLbdAt7vYAEFmbosKcSt2j2ttBeb5WSSKkakzxCHqcHqbU9cnFJpFrwuQZ7QX46cAMgQrAEwzychB5pw?details=txs&tokens=used

**Comment by martinboehm** [comment]
Please build a new version of Blockbook from the master.

**Comment by hewigovens** [comment]
Thanks, it works
