### ISSUE TITLE
misleading error when tx not found

### ISSUE THREAD

**Issue by matejcik** [trezor/blockbook#94]
the following url:
https://bch1.trezor.io/tx/send
gives the following error message:

> Tx not found, encoding/hex: invalid byte: U+0073 's'

This is misleading. A better reply would be something like:

> Transaction not found: "send"
> (encoding/hex: invalid byte: U+0073 's')

(alternately because `/tx/send` is Bitcore's send form, maybe this is worth special-casing?)

**Comment by martinboehm** [comment]
Fix will be released in Blockbook v0.2.0.
