### ISSUE TITLE
Parse contract Ethereum internal transactions

### ISSUE THREAD

**Issue by magmel48** [trezor/blockbook#944]
Hello,

the latest Blockbook version cannot parse contract Ethereum transactions like
https://etherscan.io/tx/0x390ece042f065dadee3ac495d6294e7bfb138458ae5cf54d1dac88c5ccdabae5

and the call to `<blockbook_url>/api/v2/tx/0x390ece042f065dadee3ac495d6294e7bfb138458ae5cf54d1dac88c5ccdabae5` will display only one vin and one vout which include only contract address without real internal txs.

Do you have some plans to improve the situation?

**Comment by martinboehm** [comment]
Hi, it is supported, see our instance https://eth1.trezor.io/tx/0x390ece042f065dadee3ac495d6294e7bfb138458ae5cf54d1dac88c5ccdabae5. However you have to run the archive version of the backend and synchronize Blockbook with [archive config](https://github.com/trezor/blockbook/blob/stakingpool/configs/coins/ethereum_archive.json) with it. Just to warn you, it is time and resource very intensive task to run this setup.

**Comment by magmel48** [comment]
If it's not sensitive info, could you provide your current hardware setup for the backend node and blockbook as well?

**Comment by Dehumanizer77** [comment]
@magmel48 It's pretty much standard 1U server hardware, a LOT of memory, ~20 CPU threads and of course, SSDs for databases. We have experimented with HDDs in various non-standard setups and only using SSD for cache, but it didn't work, SSDs are a must, thus running Ethereum in archive mode is quite expensive, currently the backend and blockbook database takes 15T (plus ~300 GB for the consensus node). 
Also, if you want to synchronize it from scratch, it will take several months.

**Comment by magmel48** [comment]
great, thank you

**Comment by alternativc** [comment]
I know this is a fairly old thread. But does someone have a HW spec needed to run erigon archive and blockbook in archive mode these days - if we can have ~ requirements for both services it would be great. 

A parallel question is: is there a database snapshot we can use to speed up blockbook sync?
