### ISSUE TITLE
When IsSync true server will go crazy

### ISSUE THREAD

**Issue by 4406arthur** [trezor/blockbook#954]
check the log 
<img width="907" alt="Screenshot 2023-07-28 at 3 43 08 PM" src="https://github.com/trezor/blockbook/assets/5071988/8eec5868-2f0e-4fbf-9902-c5f214490b3a">
<img width="1193" alt="image" src="https://github.com/trezor/blockbook/assets/5071988/cc057160-13ca-413a-b6b6-1ed0d2094180">

Our upstream node will be crashed after increasing requests from blockbook

**Comment by martinboehm** [comment]
Sorry, I do not understand what is the issue.

**Comment by 4406arthur** [comment]
@martinboehm Sorry, let me be more specific 

![image](https://github.com/trezor/blockbook/assets/5071988/4fcd8731-328e-4f15-8795-bd2c1abf1b6a)

I found that sometimes Blockbook cannot sync up with Mempool, which will affect the performance.
How do you think we could fix such a situation?

**Comment by martinboehm** [comment]
Is the `ZeroMQ` connection working? For Bitcoin mainnet it should be on the port 38330 in the default configuration. You should see in the Blockbook log something like `mq.go:60] MQ listening to tcp://127.0.0.1:38330` when you restart it.

**Comment by 4406arthur** [comment]
Yes, it is connected and sometimes works well.

**Comment by martinboehm** [comment]
Obsolete
