### ISSUE TITLE
bumpfee or RBF or Child-Pays-For-Parent 

### ISSUE THREAD

**Issue by ah2020b** [trezor/blockbook#956]
Hi

Please help! How can I use Blockbook API for one of this options? bumpfee or RBF or Child-Pays-For-Parent 

I have a transaction stucked since Jun 2023.

Hash
dc36-8ddf 
Time
21 Jun 2023 09:42:18
Age
1m 6d 2h 37m 18s
Inputs
307
Fee
0.00085179 BTC
$24.88
Fee/B
1.879 sat/B
Fee/VB
-
Size
45,321 Bytes
Weight
181,284
Weight Unit
0.470 sat/WU
Coinbase
No
Witness
No
RBF
No
Locktime
0
Version
2

**Comment by martinboehm** [comment]
You cannot use Blockbook for that.
