### ISSUE TITLE
Hardware Requirements for Running Ethereum Blockbook

### ISSUE THREAD

**Issue by ranjbar-dev** [trezor/blockbook#961]
Hello,

I'm currently running a Bitcoin Blockbook instance with 16GB of RAM and a 1500GB SSD, and it's working well.

I'm interested in also running an Ethereum Blockbook instance. Given the differences between the Bitcoin and Ethereum networks, I'm wondering whether the Ethereum Blockbook requires more resources than the Bitcoin one.

Can you provide some guidance on the hardware requirements for running Ethereum Blockbook, particularly if they're greater than the requirements for Bitcoin?

Thank you.

**Comment by vdovhanych** [comment]
Hi, Ethereum is much more storage-heavy, around 12TB in archive mode, so at least 14TB. And for full-node (1.2TB now), I'd go with at least 3TB of space. Blockbook will also use up some storage when it synchronizes all the data. It's in hundreds of GBs.

**Comment by ranjbar-dev** [comment]
> Hi, Ethereum is much more storage-heavy, around 12TB in archive mode, so at least 14TB. And for full-node (1.2TB now), I'd go with at least 3TB of space. Blockbook will also use up some storage when it synchronizes all the data. It's in hundreds of GBs.

Tnx!
