### ISSUE TITLE
Port mempool.space fee API for Bitcoin fee estimation?

### ISSUE THREAD

**Issue by sime** [trezor/blockbook#966]
mempool.space has a great fee estimation, could it be ported to Blockbook for Bitcoin?

I'm aware `api/v2/estimatefee/` is a proxy to bitcoind `estimatesmartfee`.

I'd suggest a new endpoint which is a port of the fee API mempool.space has?

Source: https://github.com/mempool/mempool/blob/master/backend/src/api/fee-api.ts

**Comment by martinboehm** [comment]
@sime Interesting, will check the feasibility.
