### ISSUE TITLE
Error when trying to run blockbook manually inside a Docker container

### ISSUE THREAD

**Issue by vivekteega** [trezor/blockbook#974]
I am trying to create a Docker image for Blockbook. Since systemd is not allowed inside I have to run both the backend and blockbook service manually. 

There is an error in the linking

```
root@d21a9577186c:/opt/coins/blockbook/bitcoin# su -s /bin/bash -c "/opt/coins/blockbook/bitcoin/bin/blockbook -blockchaincfg=/opt/coins/blockbook/bitcoin/config/blockchaincfg.json -datadir=/opt/coins/data/bitcoin/blockbook/db -sync -internal=:9066 -public=:9166 -certfile=/opt/coins/blockbook/bitcoin/cert/blockbook -explorer= -log_dir=/opt/coins/blockbook/bitcoin/logs -dbcache=1073741824" blockbook-bitcoin
```

**Comment by vivekteega** [comment]
Somebody opened this issue 3-4 years back but closed it without giving the solution. https://github.com/pebbe/zmq4/issues/124

**Comment by vdovhanych** [comment]
take a look at our other project where we run bitcoin regtest in docker image. https://github.com/trezor/trezor-user-env/tree/master/docker/bitcoin-regtest
