### ISSUE TITLE
ethereum update from geth to erigon

### ISSUE THREAD

**Issue by Pyxic** [trezor/blockbook#997]
Hello, I see that in the configurations the geth client has been changed to erigon. Do I need to resynchronize the node or can I just rebuild the services and restart?

**Comment by martinboehm** [comment]
Hi, if you want to use Erigon, you have to resync the Erigon backend. Blockbook does not have to be resynced.

**Comment by Pyxic** [comment]
Ok, thank you

**Comment by AlexanderPavlenko** [comment]
In case someone needs to urgently upgrade after the hardfork, the latest Blockbook seems to work fine with the latest Geth: https://github.com/mycelium-com/blockbook-geth

**Comment by benma** [comment]
What was the reason for switching from geth to erigon?

**Comment by martinboehm** [comment]
The disk requirements of the archive version of geth are much higher than erigon's.

**Comment by benma** [comment]
What about geth using snap sync? Last time I checked this worked with Blockbook and should be much smaller, and a lot faster to sync too. Did you consider using that?
