### ISSUE TITLE
Duplicated txs id with one address

### ISSUE THREAD

**Issue by yida-l** [trezor/blockbook#999]
Hello, we are running two blockbook nodes with Bitcoin, and we found out a weird issue about duplicated txs id existed in one address, snapshot as follows:

`api/v2/address/1CNT2kAGy2chgVKdZ7L28EoX1AnM2pvpAK`

![image](https://github.com/trezor/blockbook/assets/120190485/69c65500-bb11-4292-8474-b29b57ebf6a9)
Node1 got 587 txs

![image](https://github.com/trezor/blockbook/assets/120190485/55af80ea-46da-4ac1-860c-a5cbcb52007d)
Node2 got 588 txs with same address

Then we compare the all txs between these two nodes, got one duplicated txs id with Node2

`1e6da195ec78ba18b2d5455a6b2441dd4596206660f168dd2bc79e20d3e3b639` this is the duplicated txs id, any suggestion for this one? thanks

**Comment by martinboehm** [comment]
I tested on our production instances and all show the same data at this moment:
<img width="1330" alt="image" src="https://github.com/trezor/blockbook/assets/11609674/da28e788-f29c-45c0-8c87-4007a5ef8b71">
Unless the screenshots are several days old, it seems that your database is corrupted, as the number of transactions differs a lot from our instances. Obviously, a duplicate transaction is wrong.

**Comment by yida-l** [comment]
Yes, you are right, we did run many nodes cross different regions, only one node having this issue, but all of them using same version and spec, no idea about why this issue, could you please show us more hints about how to detect this one, or even prevent this issue happen again, thanks
